// @generated by recipe joern-effect.generated-template-registry
// projection: sync-joern-templates
// source: packages/attune/nx/src/generators/sync-joern-templates
// This file is generated by @attune/nx.
// Source: sync-joern-templates.
// Keep manual implementation in neighboring files.
import { dangerousCallTemplate } from "./dangerous-call.js"

export const joernTemplates = [dangerousCallTemplate] as const

export type JoernTemplate = (typeof joernTemplates)[number]
