// @generated by recipe cocoindex-effect.sync-mcp-tools
// projection: sync-cocoindex-mcp-tools
// source: packages/attune/nx/src/generators/sync-cocoindex-mcp-tools
// This file is generated by @attune/nx.
// Source: sync-cocoindex-mcp-tools.
// Keep manual implementation in neighboring files.
import { searchTool } from "./search.js"

export const cocoindexMcpTools = [searchTool] as const

export type CocoIndexMcpTool = (typeof cocoindexMcpTools)[number]
