/* @generated by @attune/nx:attune-repair. Do not edit directly. */
// @ts-nocheck
import {
  definePackageFuzzRpcGroup,
  defineTypeGuidance,
  type AttunePackageContract,
} from "@attune/framework-protocol"

export const createAttuneGenerated = <
  const Contract extends AttunePackageContract,
  const AtomFamilyLaws extends readonly string[],
  const CodecLaws extends readonly string[],
  const CommandLaws extends readonly string[],
  const DestructiveResourceProviderLaws extends readonly string[],
  const ProjectionLaws extends readonly string[],
  const QueryLaws extends readonly string[],
  const ResourceProviderLaws extends readonly string[],
  const Source extends { readonly PackageContract: Contract; readonly atomFamilyLaws: AtomFamilyLaws; readonly codecLaws: CodecLaws; readonly commandLaws: CommandLaws; readonly destructiveResourceProviderLaws: DestructiveResourceProviderLaws; readonly projectionLaws: ProjectionLaws; readonly queryLaws: QueryLaws; readonly resourceProviderLaws: ResourceProviderLaws } & Readonly<Record<string, unknown>>,
>(source: Source) => {
  const PackageContract = source.PackageContract
  const {
    alchemyStackResourceOperation,
    atomFamilyLaws,
    codecLaws,
    commandIntentBoundaryOperation,
    commandLaws,
    day0LifecycleProjectionOperation,
    deploymentConfigCodecOperation,
    destructiveResourceProviderLaws,
    homeDeploymentViewAtomsOperation,
    localStateCommandOperation,
    manualProofConfirmationOperation,
    nixosAnywhereInstallOperation,
    phaseSummaryQueryOperation,
    projectionLaws,
    providerTransitionOperation,
    queryLaws,
    resourceProviderLaws,
  } = source

  const PackageFuzzHandlers = {
    "deployment-config-codec": () => ({
      name: "thinkcentre-day0",
      hostnames: ["attune-cp-1", "attune-cp-2", "attune-cp-3"],
      localStateDir: ".attune/day0",
      secretRefs: ["thinkcentre-oauth-or-auth-key"],
      tailscaleAuthMaterialRequired: true,
    }),
    "day0-lifecycle-projection": () => ({
      name: "thinkcentre-day0",
      hostnames: ["attune-cp-1", "attune-cp-2", "attune-cp-3"],
      resourceIds: [
        "operator-machine",
        "tailscale-auth-material",
        "attune-cp-1:nixos-anywhere-install",
      ],
      phases: ["operator", "secrets", "hosts"],
      blockedResourceIds: ["attune-cp-1:nixos-anywhere-install"],
      destructiveResourceIds: ["attune-cp-1:nixos-anywhere-install"],
    }),
    "phase-summary-query": () => ({
      planned: 1,
      ready: 2,
      blocked: 1,
      nextAgentStepKind: "ManualGate" as const,
    }),
    "provider-transition": () => ({
      provider: "NixProvider",
      mode: "DryRun" as const,
      resourceId: "installer-image",
      operation: "safe" as const,
      status: "Planned" as const,
      mutated: false,
      command: ["nix", "build", "path:./nix/hosts#nixosConfigurations.attune-installer.config.system.build.isoImage"],
      display: "'nix' 'build' 'path:./nix/hosts#nixosConfigurations.attune-installer.config.system.build.isoImage'",
      evidence: [
        {
          ref: "NixProvider:DryRun:installer-image",
          summary: "DryRun transition for installer-image",
          secret: false,
        },
      ],
      blockers: [],
    }),
    "nixos-anywhere-install": () => ({
      provider: "NixosAnywhereProvider",
      mode: "Test" as const,
      resourceId: "attune-cp-1:nixos-anywhere-install",
      operation: "irreversible" as const,
      status: "Observed" as const,
      mutated: false,
      evidence: [
        {
          ref: "NixosAnywhereProvider:Test:attune-cp-1:nixos-anywhere-install:observed",
          summary:
            "Desired host state already observed; no repeated nixos-anywhere execution.",
          secret: false,
        },
      ],
      blockers: [],
    }),
    "alchemy-stack-resource": () => ({
      provider: "attune:alchemy:thinkcentre-day0-deployment" as const,
      deploymentResource: "attune:alchemy:ThinkCentreDay0Deployment",
      resourceCount: 3,
      bindingKinds: ["plan", "phase-summary", "manual-action"],
      liveExecution: false,
    }),
    "local-state-command": () => ({
      state: {
        confirmedGateIds: ["attune-cp-1:disk-wipe-confirmed"],
        completedResourceIds: [],
        failedResourceIds: [],
        records: [],
        gateEvidence: [
          {
            gateId: "attune-cp-1:disk-wipe-confirmed",
            evidence: { kind: "operator-confirmation" },
            confirmedAt: "2026-01-01T00:00:00.000Z",
          },
        ],
        evidence: [],
      },
      changedReactivityKeys: [
        "home-deployment.state-file.changed",
        "home-deployment.destructive-approval.changed",
      ],
    }),
    "manual-proof-confirmation": () => ({
      approvalId: "approval:attune-cp-1:nixos-anywhere-install",
      gateId: "attune-cp-1:disk-wipe-confirmed",
      resourceId: "attune-cp-1:nixos-anywhere-install",
      approvedBy: "operator",
      approvedAt: "2026-01-01T00:00:00.000Z",
      proofRef: "gate:attune-cp-1:disk-wipe-confirmed:2026-01-01T00:00:00.000Z",
      expiresAt: "2026-01-01T00:30:00.000Z",
    }),
    "command-intent-boundary": () => ({
      resourceId: "attune-cp-1:nixos-anywhere-install",
      command: ["nixos-anywhere", "--flake", "path:./nix/hosts#attune-cp-1", "root@attune-installer-cp-1.local"],
      display:
        "'nixos-anywhere' '--flake' 'path:./nix/hosts#attune-cp-1' 'root@attune-installer-cp-1.local'",
      executionBoundary: "rendered-only" as const,
      liveExecutionAllowed: false,
      redacted: true,
    }),
    "home-deployment-view-atoms": () => ({
      atomId: "destructiveApprovalAtom",
      reactivityKeys: [
        "home-deployment.destructive-approval.changed",
        "home-deployment.provider-gate.changed",
      ],
      dependsOnAtoms: ["providerGateAtom"],
      valueKind: "destructive-approval-state",
      readOnly: true,
    }),
  } as const satisfies { readonly [Id in HomeDeploymentOperationId]: () => unknown }
  type PackageFuzzHandlers = typeof PackageFuzzHandlers

  const PackageProperties = {
    "deployment-config-codec": {
      property:
        "Deployment config values decode through Effect Schema and surface redacted config facts through deploymentPlanAtom.",
    },
    "day0-lifecycle-projection": {
      property:
        "Day-0 plan and local state replay deterministically into lifecycle graph, phase summary, and next agent step views.",
    },
    "phase-summary-query": {
      property:
        "Phase summaries and provider blockers are deterministic read-only queries over lifecycle graph state.",
    },
    "provider-transition": {
      property:
        "DryRun and Test provider transitions observe desired state, never live-execute, and move host/provider readiness views.",
    },
    "nixos-anywhere-install": {
      property:
        "Already observed desired host state returns Observed or Applied evidence; otherwise current disk proof and destructive approval are required.",
    },
    "alchemy-stack-resource": {
      property:
        "Alchemy deployment resources materialize plan/resource bindings without executing live provider transitions in PackageTestLayer.",
    },
    "local-state-command": {
      property:
        "Local state updates are schema-backed command records that announce state, gate, and destructive approval freshness.",
    },
    "manual-proof-confirmation": {
      property:
        "Manual proof confirmation records exact gate evidence before destructive approval state can move.",
    },
    "command-intent-boundary": {
      property:
        "Typed command intents render deterministically and reserve execution for the provider/executor boundary.",
    },
    "home-deployment-view-atoms": {
      property:
        "Package atoms expose Day-0 runbook readiness views as read-only derived state over Reactivity keys.",
    },
  } as const satisfies {
    readonly [Id in HomeDeploymentOperationId]: { readonly property: string }
  }
  type PackageProperties = typeof PackageProperties

  const PackageTypeGuidance = defineTypeGuidance(PackageContract, {
    sourceLabels: [
      "contract.operation",
      "effect-schema.ast",
      "operation.kind.day0-resource-runbook",
      "resource-provider.destructive-gate",
      "package-view-graph",
    ],
    sources: [
      {
        id: "contract:home-deployment",
        label: "home-deployment package contract",
        kind: "contract-operation",
      },
      {
        id: "views:home-deployment",
        label: "home-deployment Reactivity and atom graph",
        kind: "declared-view",
      },
    ],
    operations: {
      "deployment-config-codec": operationGuidance(
        deploymentConfigCodecOperation,
        codecLaws,
        {
          inputPartitionId: "deployment-config-codec.source",
          outputPartitionId: "deployment-config-codec.hosts",
          coverageTargetId: "deploymentPlanAtom.moves",
          transformId: "deployment-config-codec.config-source-coverage",
        },
      ),
      "day0-lifecycle-projection": operationGuidance(
        day0LifecycleProjectionOperation,
        projectionLaws,
        {
          inputPartitionId: "day0-lifecycle-projection.gate-state",
          outputPartitionId: "day0-lifecycle-projection.resource-statuses",
          coverageTargetId: "deploymentPlanAtom.moves",
          transformId: "day0-lifecycle-projection.state-coverage",
        },
      ),
      "phase-summary-query": operationGuidance(
        phaseSummaryQueryOperation,
        queryLaws,
        {
          inputPartitionId: "phase-summary-query.phase",
          outputPartitionId: "phase-summary-query.next-agent-step",
          coverageTargetId: "phaseSummaryAtom.moves",
          transformId: "phase-summary-query.phase-coverage",
        },
      ),
      "provider-transition": operationGuidance(
        providerTransitionOperation,
        resourceProviderLaws,
        {
          inputPartitionId: "provider-transition.mode-resource-status",
          outputPartitionId: "provider-transition.result-status",
          coverageTargetId: "providerGateAtom.moves",
          transformId: "provider-transition.dry-run-test-coverage",
          filterId: "provider-transition.no-live-execution",
          partitions: [
            {
              id: "provider-transition.resource-status",
              kind: "resource-state",
              from: "resource.observationSchema",
              sourceId: "operation:provider-transition",
            },
          ],
        },
      ),
      "nixos-anywhere-install": operationGuidance(
        nixosAnywhereInstallOperation,
        destructiveResourceProviderLaws,
        {
          inputPartitionId: "nixos-anywhere-install.observed-proof-approval",
          outputPartitionId: "nixos-anywhere-install.observed-or-applied-evidence",
          coverageTargetId: "destructiveApprovalAtom.moves",
          transformId: "nixos-anywhere-install.destructive-gate-coverage",
          filterId: "nixos-anywhere-install.no-live-execution",
          partitions: [
            {
              id: "nixos-anywhere-install.desired-state-observed",
              kind: "resource-state",
              from: "resource.observationSchema",
              sourceId: "operation:nixos-anywhere-install",
            },
            {
              id: "nixos-anywhere-install.current-proof",
              kind: "destructive-gate",
              from: "destructive.proof",
              sourceId: "operation:nixos-anywhere-install",
            },
            {
              id: "nixos-anywhere-install.current-approval",
              kind: "destructive-gate",
              from: "destructive.approval",
              sourceId: "operation:nixos-anywhere-install",
            },
          ],
        },
      ),
      "alchemy-stack-resource": operationGuidance(
        alchemyStackResourceOperation,
        resourceProviderLaws,
        {
          inputPartitionId: "alchemy-stack-resource.provider-mode",
          outputPartitionId: "alchemy-stack-resource.binding-kinds",
          coverageTargetId: "deploymentPlanAtom.moves",
          transformId: "alchemy-stack-resource.resource-binding-coverage",
          filterId: "alchemy-stack-resource.no-live-execution",
        },
      ),
      "local-state-command": operationGuidance(
        localStateCommandOperation,
        commandLaws,
        {
          inputPartitionId: "local-state-command.action",
          outputPartitionId: "local-state-command.changed-keys",
          coverageTargetId: "destructiveApprovalAtom.moves",
          transformId: "local-state-command.state-action-coverage",
        },
      ),
      "manual-proof-confirmation": operationGuidance(
        manualProofConfirmationOperation,
        commandLaws,
        {
          inputPartitionId: "manual-proof-confirmation.gate-id",
          outputPartitionId: "manual-proof-confirmation.approval-record",
          coverageTargetId: "destructiveApprovalAtom.moves",
          transformId: "manual-proof-confirmation.gate-coverage",
        },
      ),
      "command-intent-boundary": operationGuidance(
        commandIntentBoundaryOperation,
        commandLaws,
        {
          inputPartitionId: "command-intent-boundary.action-mode",
          outputPartitionId: "command-intent-boundary.rendered-command",
          coverageTargetId: "providerGateAtom.moves",
          transformId: "command-intent-boundary.intent-coverage",
          filterId: "command-intent-boundary.no-live-execution",
        },
      ),
      "home-deployment-view-atoms": operationGuidance(
        homeDeploymentViewAtomsOperation,
        atomFamilyLaws,
        {
          inputPartitionId: "home-deployment-view-atoms.atom-id",
          outputPartitionId: "home-deployment-view-atoms.readonly-value-kind",
          coverageTargetId: "destructiveApprovalAtom.moves",
          transformId: "home-deployment-view-atoms.atom-coverage",
        },
      ),
    },
  } as const)
  type PackageTypeGuidance = typeof PackageTypeGuidance

  type OperationWithGuidance = {
    readonly id: string
    readonly kind: string
    readonly input: unknown
    readonly output: unknown
    readonly error?: unknown
    readonly views?: {
      readonly reactivityKeys?: readonly string[]
      readonly atoms?: readonly string[]
    }
    readonly laws?: readonly string[]
  }

  type LawPartition<Laws extends readonly string[]> = {
    readonly [Index in keyof Laws]: {
      readonly id: Laws[Index]
      readonly kind: "law"
      readonly from: "inferred-law"
    }
  }

  type GuidancePartition = {
    readonly id: string
    readonly kind:
      | "schema-boundary"
      | "resource-state"
      | "destructive-gate"
      | "custom"
    readonly from: string
    readonly sourceId?: string
  }

  function operationGuidance<
    const Operation extends OperationWithGuidance,
    const Laws extends readonly string[],
  >(
    operation: Operation,
    laws: Laws,
    options: {
      readonly inputPartitionId: string
      readonly outputPartitionId: string
      readonly coverageTargetId: string
      readonly transformId: string
      readonly filterId?: string
      readonly partitions?: readonly GuidancePartition[]
    },
  ) {
    return {
      sourceLabels: [
        `operation.kind.${operation.kind}`,
        "effect-schema.ast",
        "package-view-graph",
      ],
      sources: [
        {
          id: `operation:${operation.id}`,
          label: operation.id,
          kind: "contract-operation" as const,
          operationId: operation.id,
        },
      ],
      schemaSources: [
        schemaSource(operation.id, "input"),
        schemaSource(operation.id, "output"),
        schemaSource(operation.id, "error"),
      ],
      partitions: options.partitions ?? [],
      inputPartitions: [
        {
          id: options.inputPartitionId,
          kind: "schema-boundary" as const,
          from: "schema.input",
          sourceId: `schema:${operation.id}:input`,
          transformIds: [options.transformId],
          ...(options.filterId ? { filterIds: [options.filterId] } : {}),
        },
      ],
      outputPartitions: [
        {
          id: options.outputPartitionId,
          kind: "output-variant" as const,
          from: "schema.output",
          sourceId: `schema:${operation.id}:output`,
        },
      ],
      errorPartitions: [
        {
          id: `${operation.id}.typed-error`,
          kind: "typed-error-variant" as const,
          from: "schema.error",
          sourceId: `schema:${operation.id}:error`,
        },
      ],
      lawPartitions: lawPartitions(laws),
      viewPartitions: [
        ...viewPartitions(operation.id, "reactivity-key", operation.views?.reactivityKeys ?? []),
        ...viewPartitions(operation.id, "atom", operation.views?.atoms ?? []),
      ],
      coverageSearch: [
        {
          id: `coverage:${operation.id}:${options.coverageTargetId}`,
          targetPartitionId: options.coverageTargetId,
          tier: "commit" as const,
          required: true,
        },
      ],
      transforms: [
        {
          id: options.transformId,
          kind: "coverage-bias" as const,
          targetPartitionId: options.coverageTargetId,
          reason:
            "Bias generated cases toward missing Day-0 provider, gate, or package-view movement.",
        },
      ],
      filters: options.filterId
        ? [
          {
            id: options.filterId,
            kind: "operation-precondition" as const,
            reason:
              "Generated Day-0 audits stay on DryRun, Test, rendered-only, or already-observed paths; live provider execution remains waivered.",
            targetPartitionId: options.inputPartitionId,
            expectedAcceptanceRate: 0.95,
          },
        ]
        : [],
    } as const
  }

  function schemaSource(operationId: string, role: "input" | "output" | "error") {
    return {
      id: `schema:${operationId}:${role}`,
      role,
      label: `${operationId}.${role}`,
      source: "effect-schema" as const,
    }
  }

  function lawPartitions<const Laws extends readonly string[]>(laws: Laws): LawPartition<Laws> {
    return laws.map((id) => ({
      id,
      kind: "law",
      from: "inferred-law",
    })) as LawPartition<Laws>
  }

  function viewPartitions(
    operationId: string,
    kind: "reactivity-key" | "atom",
    values: readonly string[],
  ) {
    return values.map((value) => ({
      id: `${value}.moves`,
      kind,
      from: kind === "reactivity-key" ? "operation.views.reactivityKeys" : "operation.views.atoms",
      label: `${operationId}:${value}`,
    })) as readonly {
      readonly id: string
      readonly kind: "reactivity-key" | "atom"
      readonly from: "operation.views.reactivityKeys" | "operation.views.atoms"
      readonly label: string
    }[]
  }

  return {
    PackageFuzzHandlers,
    PackageProperties,
    PackageTypeGuidance,
  } as const
}
