import { readFileSync } from "node:fs"
import { Effect } from "effect"
import { describe, expect, it } from "vitest"
import {
  RecipeObservationView,
  RecipeRecordView,
  type RecipeDefinition,
} from "@attune/framework-protocol"
import {
  CocoIndexClient,
  CocoIndexClientFixture,
  CocoIndexEffectRecipes,
  normalizeCocoIndexHits,
  type AnchorCard,
} from "../src/index.js"

const runId = "run-local-001"
const repoSnapshotId = "repo-snapshot-001"

const fixtureAnchors: ReadonlyArray<AnchorCard> = [
  {
    anchorId: "anchor-http-source",
    runId,
    title: "HTTP request body source",
    vocabulary: ["typescript", "source", "request", "body", "handler"],
    score: 0.91,
    excerpt: "export function handler(req) { return req.body.command }",
    locations: [{ path: "src/routes/run.ts", startLine: 10, endLine: 13 }],
  },
  {
    anchorId: "anchor-spawn-sink",
    runId,
    title: "child_process spawn sink",
    vocabulary: ["typescript", "sink", "spawn", "child_process"],
    score: 0.88,
    excerpt: "spawn(command, args)",
    locations: [{ path: "src/shell/run.ts", startLine: 22, endLine: 22 }],
  },
  {
    anchorId: "anchor-react-cleanup",
    runId,
    title: "React effect cleanup",
    vocabulary: ["typescript", "react", "cleanup", "effect"],
    score: 0.67,
    excerpt: "return () => subscription.dispose()",
    locations: [{ path: "src/ui/useFeed.ts", startLine: 41, endLine: 44 }],
  },
]

describe("cocoindex-effect", () => {
  it("declares CocoIndex effect recipes from the package barrel", () => {
    const records = CocoIndexEffectRecipes.map((recipe) =>
      RecipeRecordView.fromRecipe(recipe as RecipeDefinition<unknown, unknown>)
    )

    expect(records.map((record) => record.recipeId)).toEqual([
      "cocoindex-effect.mcp-tool-generation",
      "cocoindex-effect.emit-mcp-schema",
      "cocoindex-effect.scaffold-mcp-tool",
      "cocoindex-effect.sync-mcp-tools",
      "cocoindex-effect.generated-surface-check",
      "cocoindex-effect.ensure-indexed",
      "cocoindex-effect.search-anchors",
      "cocoindex-effect.search-similar-anchors",
      "cocoindex-effect.repository-session",
    ])
    expect(records.at(-1)).toMatchObject({
      kind: "managed-recipe",
      resourceKind: "repository-intelligence-session",
      humanReviewRequired: true,
    })
  })

  it("makes generated MCP artifacts recipe-owned and freshness-observable", () => {
    const schemaPath = "packages/attune/cocoindex-effect/src/generated/cocoindex-code-mcp.ts"
    const registryPath = "packages/attune/cocoindex-effect/src/cocoindex/tools/ToolRegistry.generated.ts"
    const schemaSource = readFileSync(new URL(`../../../../${schemaPath}`, import.meta.url), "utf8")
    const registrySource = readFileSync(new URL(`../../../../${registryPath}`, import.meta.url), "utf8")

    expect(schemaSource).toContain("@generated by recipe cocoindex-effect.emit-mcp-schema")
    expect(registrySource).toContain("@generated by recipe cocoindex-effect.sync-mcp-tools")
    expect(CocoIndexEffectRecipes.find((recipe) => recipe.id === "cocoindex-effect.emit-mcp-schema")?.allowedFiles).toContain(
      "packages/attune/cocoindex-effect/src/generated/**",
    )
    expect(CocoIndexEffectRecipes.find((recipe) => recipe.id === "cocoindex-effect.sync-mcp-tools")?.allowedFiles).toContain(
      "packages/attune/cocoindex-effect/src/cocoindex/tools/**",
    )

    expect(RecipeObservationView.generatedArtifactFreshness({
      recipeId: "cocoindex-effect.emit-mcp-schema",
      artifactPath: schemaPath,
      fresh: true,
      observedAt: "2026-06-28T00:00:00.000Z",
      source: "cocoindex-effect:test",
    })).toMatchObject({
      recipeId: "cocoindex-effect.emit-mcp-schema",
      observationKind: "generated-artifact.freshness",
      payload: {
        artifactPath: schemaPath,
        ownerRecipeId: "cocoindex-effect.emit-mcp-schema",
        fresh: true,
      },
    })
  })

  it("normalizes raw CocoIndex hits into stable AnchorCards", () => {
    const anchors = normalizeCocoIndexHits(
      [
        {
          path: "src/shell/run.ts",
          startLine: 22,
          language: "typescript",
          kind: "sink",
          score: 1.4,
          code: "spawn(command, args)",
        },
      ],
      {
        repoSnapshotId,
        runId,
        query: "find process execution sinks",
        topK: 5,
      },
    )

    expect(anchors).toHaveLength(1)
    expect(anchors[0]?.anchorId).toMatch(/^anchor-/)
    expect(anchors[0]?.score).toBe(1)
    expect(anchors[0]?.vocabulary).toContain("sink")
    expect(anchors[0]?.locations[0]?.path).toBe("src/shell/run.ts")
  })

  it("provides deterministic fixture recall through the Effect service", async () => {
    const program = Effect.gen(function* recallAnchors() {
      const cocoindex = yield* CocoIndexClient
      yield* cocoindex.ensureIndexed({
        repoSnapshotId,
        repoPath: "/workspace/attune",
      })
      return yield* cocoindex.searchAnchors({
        repoSnapshotId,
        runId,
        query: "request body source",
        topK: 2,
        filters: {
          pathPrefix: "src/routes",
          language: "typescript",
        },
      })
    })

    const anchors = await Effect.runPromise(
      program.pipe(
        Effect.provide(CocoIndexClientFixture({ anchors: fixtureAnchors })),
      ),
    )

    expect(anchors.map((anchor) => anchor.anchorId)).toEqual([
      "anchor-http-source",
    ])
  })

  it("retrieves similar anchors by shared vocabulary", async () => {
    const program = Effect.gen(function* searchSimilarAnchors() {
      const cocoindex = yield* CocoIndexClient
      return yield* cocoindex.searchSimilarAnchors({
        repoSnapshotId,
        runId,
        anchorId: "anchor-http-source",
        topK: 1,
      })
    })

    const anchors = await Effect.runPromise(
      program.pipe(
        Effect.provide(CocoIndexClientFixture({ anchors: fixtureAnchors })),
      ),
    )

    expect(anchors[0]?.anchorId).toBe("anchor-spawn-sink")
  })

  it("fails explicitly when an anchor is missing", async () => {
    const program = Effect.gen(function* getMissingAnchor() {
      const cocoindex = yield* CocoIndexClient
      return yield* cocoindex.getAnchor({
        repoSnapshotId,
        runId,
        anchorId: "missing",
      })
    })

    await expect(
      Effect.runPromise(
        program.pipe(
          Effect.provide(CocoIndexClientFixture({ anchors: fixtureAnchors })),
        ),
      ),
    ).rejects.toMatchObject({ _tag: "CocoIndexAnchorNotFound" })
  })
})
