// This file is generated by @attune/nx.
// Source: sync-joern-templates.
// Keep manual implementation in neighboring files.
import { dangerousCallTemplate } from "./dangerous-call.js"

export const joernTemplates = [dangerousCallTemplate] as const

export type JoernTemplate = (typeof joernTemplates)[number]
