/* @generated by @attune/nx:attune-repair. Do not edit directly. */
/* Materialized package contract; edit ./attune.package.ts and run Nx repair. */
import { Layer, Schema } from "effect"
import {
  defineOperation,
  definePackageContract,
  definePackageViews,
  defineTypeGuidance,
  touches,
} from "@attune/framework-protocol"
import { createAttuneGenerated } from "./attune.generated.js"

export { PackageContractSchema } from "@attune/framework-protocol"

export const PolicyRuleIds = [
  "no-raw-process-env",
  "no-raw-node-apis",
  "no-arbitrary-package-manager-surfaces",
  "no-hand-authored-architecture-shapes",
] as const

export const PolicyRuleId = Schema.Literals(PolicyRuleIds)
export type PolicyRuleId = typeof PolicyRuleId.Type

export const PolicySeverity = Schema.Literals(["problem", "suggestion"] as const)
export type PolicySeverity = typeof PolicySeverity.Type

export const PolicyFinding = Schema.Struct({
  adapterBoundary: Schema.optional(Schema.Boolean),
  filename: Schema.String,
  message: Schema.String,
  nodeKind: Schema.optional(Schema.String),
  ruleFamily: Schema.String,
  ruleId: PolicyRuleId,
  severity: PolicySeverity,
})
export type PolicyFinding = typeof PolicyFinding.Type

export const PolicyRuleOutput = Schema.Struct({
  findings: Schema.Array(PolicyFinding),
  ruleId: PolicyRuleId,
})
export type PolicyRuleOutput = typeof PolicyRuleOutput.Type

export const PolicyRuleError = Schema.Struct({
  message: Schema.String,
  ruleId: PolicyRuleId,
})
export type PolicyRuleError = typeof PolicyRuleError.Type

export const UnsafeEnvProcessAccessInput = Schema.Struct({
  expressionPath: Schema.Array(Schema.String),
  filename: Schema.String,
  nodeKind: Schema.Literal("MemberExpression"),
})
export type UnsafeEnvProcessAccessInput = typeof UnsafeEnvProcessAccessInput.Type

export const DirectNodeApiInput = Schema.Struct({
  callPath: Schema.optional(Schema.Array(Schema.String)),
  filename: Schema.String,
  importSource: Schema.optional(Schema.String),
  nodeKind: Schema.Literals(["ImportDeclaration", "CallExpression"] as const),
})
export type DirectNodeApiInput = typeof DirectNodeApiInput.Type

export const ArbitraryPackageManagerSurfaceInput = Schema.Struct({
  command: Schema.optional(Schema.String),
  filename: Schema.String,
  surfaceKind: Schema.Literals([
    "package-script",
    "run-command",
    "package-manager-invocation",
    "nix-invocation",
    "tool-wrapper",
  ] as const),
})
export type ArbitraryPackageManagerSurfaceInput =
  typeof ArbitraryPackageManagerSurfaceInput.Type

export const NonGeneratedRepeatedShapeInput = Schema.Struct({
  filename: Schema.String,
  generatedBy: Schema.optional(Schema.String),
  shapeKind: Schema.Literals([
    "effect-service",
    "package-contract",
    "atom-view",
    "joern-template",
    "cocoindex-mcp-tool",
  ] as const),
})
export type NonGeneratedRepeatedShapeInput =
  typeof NonGeneratedRepeatedShapeInput.Type

export const PackageViews = definePackageViews({
  reactivityKeys: [
    "effect-oxlint-policy.rule-source.changed",
    "effect-oxlint-policy.oxlint-config.changed",
    "effect-oxlint-policy.adapter-allowlist.changed",
    "effect-oxlint-policy.scanned-source-partitions.changed",
    "effect-oxlint-policy.policy-results.changed",
  ],
  atoms: [
    "policyRuleRegistryAtom",
    "adapterAllowlistAtom",
    "policyResultAtom",
    "ruleFindingAtom",
    "waiverSummaryAtom",
    "rawEnvFindingAtom",
    "rawNodeApiFindingAtom",
    "packageManagerSurfaceFindingAtom",
    "serviceShapeFindingAtom",
  ],
} as const)

const policyRuleLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "policy.finding-schema",
  "policy.deterministic-findings",
  "policy.stable-diagnostic-ids",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const commonPolicyKeys = [
  "effect-oxlint-policy.rule-source.changed",
  "effect-oxlint-policy.scanned-source-partitions.changed",
  "effect-oxlint-policy.policy-results.changed",
] as const

const commonFindingAtoms = [
  "policyResultAtom",
  "ruleFindingAtom",
] as const

export const noRawProcessEnvOperation = defineOperation({
  id: "no-raw-process-env",
  name: "No raw process.env",
  kind: "policy-rule",
  input: UnsafeEnvProcessAccessInput,
  output: PolicyRuleOutput,
  error: PolicyRuleError,
  views: touches(PackageViews, {
    reactivityKeys: [
      ...commonPolicyKeys,
      "effect-oxlint-policy.adapter-allowlist.changed",
    ],
    atoms: [
      ...commonFindingAtoms,
      "adapterAllowlistAtom",
      "rawEnvFindingAtom",
      "waiverSummaryAtom",
    ],
  } as const),
  laws: policyRuleLaws,
  policy: {
    exportedRule: "noRawProcessEnv",
    findingSchema: "PolicyFinding",
    ruleFamily: "unsafe-env-process-access",
    ruleName: "no-raw-process-env",
  } as const,
} as const)

export const noRawNodeApisOperation = defineOperation({
  id: "no-raw-node-apis",
  name: "No raw Node APIs",
  kind: "policy-rule",
  input: DirectNodeApiInput,
  output: PolicyRuleOutput,
  error: PolicyRuleError,
  views: touches(PackageViews, {
    reactivityKeys: [
      ...commonPolicyKeys,
      "effect-oxlint-policy.adapter-allowlist.changed",
    ],
    atoms: [
      ...commonFindingAtoms,
      "adapterAllowlistAtom",
      "rawNodeApiFindingAtom",
      "waiverSummaryAtom",
    ],
  } as const),
  laws: policyRuleLaws,
  policy: {
    exportedRule: "noRawNodeApis",
    findingSchema: "PolicyFinding",
    rawSources: [
      "fs",
      "fs/promises",
      "node:fs",
      "node:fs/promises",
      "child_process",
      "node:child_process",
      "process",
      "node:process",
    ],
    ruleFamily: "direct-node-api-access",
    ruleName: "no-raw-node-apis",
  } as const,
} as const)

export const noArbitraryPackageManagerSurfacesOperation = defineOperation({
  id: "no-arbitrary-package-manager-surfaces",
  name: "No arbitrary package-manager surfaces",
  kind: "policy-rule",
  input: ArbitraryPackageManagerSurfaceInput,
  output: PolicyRuleOutput,
  error: PolicyRuleError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "effect-oxlint-policy.oxlint-config.changed",
      "effect-oxlint-policy.scanned-source-partitions.changed",
      "effect-oxlint-policy.policy-results.changed",
    ],
    atoms: [
      ...commonFindingAtoms,
      "packageManagerSurfaceFindingAtom",
      "waiverSummaryAtom",
    ],
  } as const),
  laws: policyRuleLaws,
  policy: {
    exportedRule: null,
    findingSchema: "PolicyFinding",
    ruleFamily: "arbitrary-package-manager-script-surfaces",
    ruleName: "no-arbitrary-package-manager-surfaces",
  } as const,
} as const)

export const noHandAuthoredArchitectureShapesOperation = defineOperation({
  id: "no-hand-authored-architecture-shapes",
  name: "No hand-authored architecture shapes",
  kind: "policy-rule",
  input: NonGeneratedRepeatedShapeInput,
  output: PolicyRuleOutput,
  error: PolicyRuleError,
  views: touches(PackageViews, {
    reactivityKeys: [
      ...commonPolicyKeys,
    ],
    atoms: [
      ...commonFindingAtoms,
      "serviceShapeFindingAtom",
      "waiverSummaryAtom",
    ],
  } as const),
  laws: policyRuleLaws,
  policy: {
    exportedRule: "noHandAuthoredArchitectureShapes",
    findingSchema: "PolicyFinding",
    ruleFamily: "non-generated-repeated-shapes",
    ruleName: "no-hand-authored-architecture-shapes",
    requiredGenerator: "@attune/nx",
  } as const,
} as const)

export const PackageContract = definePackageContract({
  packageId: "effect-oxlint-policy",
  sourceRoot: "framework/oxlint-policy",
  packageKind: "policy-plugin",
  views: PackageViews,
  services: [] as const,
  operations: [
    noRawProcessEnvOperation,
    noRawNodeApisOperation,
    noArbitraryPackageManagerSurfacesOperation,
    noHandAuthoredArchitectureShapesOperation,
  ] as const,
  provenance: {
    generator: "@attune/nx:package-contract",
    project: "effect-oxlint-policy",
  } as const,
  waivers: [
    {
      id: "effect-oxlint-policy/no-arbitrary-package-manager-surfaces-runtime",
      category: "legacy-boundary",
      owner: "effect-oxlint-policy-migration-agent",
      reason:
        "The package contract reserves the policy-rule boundary requested by Phase 4; the concrete oxlint rule is owned by the command-surface policy follow-up.",
      review: "standardize-effect-package-contracts phase4 tooling-command-surface-agent",
    },
  ] as const,
})
export type PackageContract = typeof PackageContract

export const PackageLayer = Layer.empty
export type PackageLayer = typeof PackageLayer

export const PackageTestLayer = Layer.empty
export type PackageTestLayer = typeof PackageTestLayer

const PackageGenerated = createAttuneGenerated({
  PackageContract,
  PolicyFinding,
  PolicyRuleId,
  policyRuleLaws,
} as const)
export const PackageFuzzHandlers = PackageGenerated.PackageFuzzHandlers
export const PackageProperties = PackageGenerated.PackageProperties
export const PackageTypeGuidance = PackageGenerated.PackageTypeGuidance
export type PackageFuzzHandlers = typeof PackageFuzzHandlers
export type PackageProperties = typeof PackageProperties
export type PackageTypeGuidance = typeof PackageTypeGuidance
