import type { ForkConfig } from "./packages/fork/src/config.js"

const pkg = "packages/joern-effect"

const config: ForkConfig = {
  project: "joern-effect",
  pack: "joern-effect",
  invariants: [
    {
      id: "pure-does-not-know-runtime",
      title: "Pure Does Not Know Runtime",
      description: "Pure code describes Joern DSLs, query plans, schemas, and evidence meanings without touching runtime effects.",
      pack: "joern-effect",
      phase: "pure",
      zone: "pure",
      claim: "Generated DSL, builder, and pure evidence code remain deterministic and descriptive.",
      forkRules: ["effect(noRuntimeExecution)", "effect(noPromise)", "effect(noNodeBuiltinImport)"],
      forkTargets: ["fork:pure"],
      properties: ["query rendering is deterministic", "evidence graph fingerprints are stable"],
      propertyTargets: ["property:pure"],
      telemetryQueries: [],
      allowedPaths: [`${pkg}/src/pure/**`],
      forbiddenPaths: [`${pkg}/src/edge/**`],
    },
    {
      id: "bridge-describes-boundaries-only",
      title: "Bridge Describes Boundaries Only",
      description: "Bridge code defines schemas, ports, events, observations, and typed errors without implementing live adapters.",
      pack: "joern-effect",
      phase: "bridge",
      zone: "bridge",
      claim: "Foreign values are represented as Effect Schema contracts before they cross into durable code.",
      forkRules: ["effect(noRuntimeExecution)", "effect(noNodeBuiltinImport)"],
      forkTargets: ["fork:bridge"],
      properties: ["schema decode encode roundtrips", "event envelope schema is stable"],
      propertyTargets: ["property:bridge"],
      telemetryQueries: [],
      allowedPaths: [`${pkg}/src/bridge/**`, "packages/eventing/src/bridge/**"],
      forbiddenPaths: [`${pkg}/src/edge/**`],
    },
    {
      id: "harness-generates-evidence-without-io",
      title: "Harness Generates Evidence Without IO",
      description: "Harness TypeScript builds scenarios, arbitraries, laws, and property suites without owning runtime side effects.",
      pack: "joern-effect",
      phase: "harness",
      zone: "source-sink",
      claim: "FastCheck pressure is structured as evidence generation, while real execution belongs to edge/Nix.",
      forkRules: ["effect(noRuntimeExecution)", "effect(noNodeBuiltinImport)"],
      forkTargets: ["fork:harness"],
      properties: ["source sink generators produce coherent scenarios", "shrinking preserves validity"],
      propertyTargets: ["property:harness"],
      telemetryQueries: [],
      allowedPaths: [`${pkg}/harness/**`],
      forbiddenPaths: [`${pkg}/src/edge/**`],
    },
    {
      id: "edge-impurity-is-contained",
      title: "Edge Impurity Is Contained",
      description: "Edge code may touch Joern, env, processes, and filesystems, but only behind Effect services and decoded outputs.",
      pack: "joern-effect",
      phase: "edge",
      zone: "runtime",
      claim: "Real-world interaction is explicit, scoped, and decoded through bridge contracts.",
      forkRules: ["effect(noThrowStatement)", "effect(noTryCatch)"],
      forkTargets: ["fork:edge"],
      properties: ["runtime failures are typed", "edge outputs decode through bridge"],
      propertyTargets: ["property:edge"],
      telemetryQueries: [],
      allowedPaths: [`${pkg}/src/edge/**`, `${pkg}/examples/**`, `${pkg}/scripts/**`, `${pkg}/test/**`],
      forbiddenPaths: [`${pkg}/src/pure/**`],
    },
  ],
  phases: [
    {
      name: "pure",
      zone: "pure",
      description: "Deterministic generated DSL, builder, query, and evidence meaning layer.",
      targets: [`${pkg}/src/pure`],
      invariants: ["pure-does-not-know-runtime"],
      minimumSeverity: "error",
      allowedRules: ["effect(noClasses)", "effect(noInterfaces)", "effect(noMutableCollections)"],
      zones: [
        { name: "generated", paths: [`${pkg}/src/pure/generated/**`] },
        { name: "builder", paths: [`${pkg}/src/pure/builder/**`] },
        { name: "program", paths: [`${pkg}/src/pure/program/**`] },
        { name: "codegen", paths: [`${pkg}/src/pure/codegen/**`] },
      ],
    },
    {
      name: "bridge",
      zone: "bridge",
      description: "Schema, event, observation, port, and typed boundary contracts.",
      targets: [`${pkg}/src/bridge`, "packages/eventing/src/bridge"],
      invariants: ["bridge-describes-boundaries-only"],
      minimumSeverity: "error",
      allowedRules: ["effect(noInterfaces)", "effect(noClasses)"],
      zones: [{ name: "schema", paths: [`${pkg}/src/bridge/**`, "packages/eventing/src/bridge/**"] }],
    },
    {
      name: "harness",
      zone: "harness",
      description: "FastCheck arbitraries, laws, fixtures, and source/sink evidence generation.",
      targets: [`${pkg}/harness`],
      invariants: ["harness-generates-evidence-without-io"],
      minimumSeverity: "error",
      allowedRules: ["vitest(no-conditional-in-test)", "vitest(no-conditional-expect)"],
      zones: [{ name: "source-sink", paths: [`${pkg}/harness/source-sink/**`] }],
    },
    {
      name: "edge",
      zone: "edge",
      description: "Runtime Joern/process/env/filesystem contact and executable entrypoints.",
      targets: [`${pkg}/src/edge`, `${pkg}/examples`, `${pkg}/scripts`, `${pkg}/test`],
      invariants: ["edge-impurity-is-contained"],
      minimumSeverity: "error",
      allowedRules: ["effect(noPromise)", "effect(noUnknown)"],
      zones: [
        { name: "runtime", paths: [`${pkg}/src/edge/runtime/**`] },
        { name: "script", paths: [`${pkg}/scripts/**`] },
        { name: "test", paths: [`${pkg}/test/**`] },
        { name: "example", paths: [`${pkg}/examples/**`] },
      ],
    },
    {
      name: "all",
      zone: "all",
      description: "Aggregate four-phase Fork baseline.",
      targets: [`${pkg}/src`, `${pkg}/harness`, `${pkg}/examples`, `${pkg}/scripts`, `${pkg}/test`],
      invariants: [
        "pure-does-not-know-runtime",
        "bridge-describes-boundaries-only",
        "harness-generates-evidence-without-io",
        "edge-impurity-is-contained",
      ],
      minimumSeverity: "error",
      allowedRules: [],
      zones: [
        { name: "pure", paths: [`${pkg}/src/pure/**`] },
        { name: "bridge", paths: [`${pkg}/src/bridge/**`, "packages/eventing/src/bridge/**"] },
        { name: "harness", paths: [`${pkg}/harness/**`] },
        { name: "edge", paths: [`${pkg}/src/edge/**`, `${pkg}/examples/**`, `${pkg}/scripts/**`, `${pkg}/test/**`] },
      ],
    },
  ],
}

export default config
