// This file is generated by @attune/nx.
// Source: sync-k8s-resources.
// Keep manual implementation in neighboring files.
import { AttuneArtifact } from "./attune-artifact.js"
import { AttuneBudget } from "./attune-budget.js"
import { AttuneDiscoveryRun } from "./attune-discovery-run.js"
import { AttunePhase } from "./attune-phase.js"
import { AttunePolicy } from "./attune-policy.js"
import { AttuneReport } from "./attune-report.js"
import { AttuneToolJob } from "./attune-tool-job.js"
import { BudgetClass } from "./budget-policy.js"
import { BudgetPolicy } from "./budget-policy.js"
import { AttuneControlPlane } from "./control-plane.js"
import { AttuneCustomResources } from "./custom-resources.js"
import { AttuneDiscoveryWorkflow } from "./discovery-workflow.js"
import { JoernQuery } from "./joern-query.js"
import { LocalComputeStack } from "./local-compute-stack.js"
import { LocalPostgres } from "./postgres.js"
import { RepoSandbox } from "./repo-sandbox.js"
import { ResourceClass } from "./resource-class.js"
import { RunNamespace } from "./run-namespace.js"
import { WorkerPool } from "./worker-pool.js"

export const k8sResourceModules = [AttuneArtifact, AttuneBudget, AttuneDiscoveryRun, AttunePhase, AttunePolicy, AttuneReport, AttuneToolJob, BudgetClass, BudgetPolicy, AttuneControlPlane, AttuneCustomResources, AttuneDiscoveryWorkflow, JoernQuery, LocalComputeStack, LocalPostgres, RepoSandbox, ResourceClass, RunNamespace, WorkerPool] as const

export type K8sResourceModule = (typeof k8sResourceModules)[number]
