import { readText, writeTextIfChanged, type GeneratorTree } from "./tree.js"

export const upsertExport = (tree: GeneratorTree, indexPath: string, modulePath: string): void => {
  const line = `export * from "${modulePath}"`
  const current = readText(tree, indexPath)
  const lines = current === null ? [] : current.split(/\r?\n/u).filter((entry) => entry.trim().length > 0)

  if (!lines.includes(line)) {
    lines.push(line)
  }

  writeTextIfChanged(tree, indexPath, lines.sort().join("\n"))
}

export const generatedHeader = (
  label: string,
  owner: {
    readonly recipeId?: string
    readonly projectionId?: string
    readonly source?: string
  } = {},
): string => {
  const ownerLines = [
    ...(owner.recipeId === undefined ? [] : [`// @generated by recipe ${owner.recipeId}`]),
    ...(owner.projectionId === undefined ? [] : [`// projection: ${owner.projectionId}`]),
    ...(owner.source === undefined ? [] : [`// source: ${owner.source}`]),
  ]
  return [
    ...ownerLines,
    "// This file is generated by @attune/nx.",
    `// Source: ${label}.`,
    "// Keep manual implementation in neighboring files.",
    "",
  ].join("\n")
}
