/* @generated by @attune/nx:attune-repair. Do not edit directly. */
/* Materialized package contract; edit ./attune.package.ts and run Nx repair. */
import { Layer, Schema } from "effect"

import {
  OperationKindSchema,
  PackageContractSchema,
  defineOperation,
  definePackageContract,
  definePackageFuzzRpcGroup,
  definePackageViews,
  defineTypeGuidance,
  touches,
} from "../../protocol/src/package-contract/index.js"
import { createAttuneGenerated } from "./attune.generated.js"

export { PackageContractSchema } from "../../protocol/src/package-contract/index.js"

export const PackageViews = definePackageViews({
  reactivityKeys: [
    "architecture.policy-findings",
    "architecture.waiver-summary",
    "architecture.package-contract-coverage",
    "architecture.command-surface-findings",
    "architecture.generator-shape-findings",
    "architecture.source-bom-findings",
    "architecture.rpc-descriptors",
    "architecture.type-guidance-coverage",
    "architecture.law-inference-findings",
    "architecture.workspace-policy-summary",
  ],
  atoms: [
    "policyFindingsAtom",
    "waiverSummaryAtom",
    "packageContractCoverageAtom",
    "commandSurfaceFindingsAtom",
    "generatorShapeFindingsAtom",
    "sourceBomPolicyFindingsAtom",
    "rpcDescriptorAtom",
    "typeGuidanceCoverageAtom",
    "lawInferenceAtom",
    "workspacePolicySummaryAtom",
  ],
} as const)

const PolicySeverity = Schema.Literals(["error", "warning"] as const)

export const ArchitectureFinding = Schema.Struct({
  ruleId: Schema.String,
  severity: PolicySeverity,
  filePath: Schema.optional(Schema.String),
  message: Schema.String,
})
export type ArchitectureFinding = Schema.Schema.Type<typeof ArchitectureFinding>

const PolicyReportOutput = Schema.Struct({
  ok: Schema.Boolean,
  diagnostics: Schema.Array(ArchitectureFinding),
})

export const PackageContractDecodeInput = Schema.Struct({
  contract: Schema.Unknown,
})
export type PackageContractDecodeInput = Schema.Schema.Type<typeof PackageContractDecodeInput>

export const PackageContractDecodeOutput = Schema.Struct({
  packageId: Schema.String,
  packageKind: Schema.String,
  operationCount: Schema.Number,
  valid: Schema.Boolean,
})
export type PackageContractDecodeOutput = Schema.Schema.Type<typeof PackageContractDecodeOutput>

export const PackageContractAssertionInput = Schema.Struct({
  packageId: Schema.String,
  operationIds: Schema.Array(Schema.String),
})
export type PackageContractAssertionInput = Schema.Schema.Type<typeof PackageContractAssertionInput>

export const LawInferenceInput = Schema.Struct({
  operationId: Schema.String,
  operationKind: OperationKindSchema,
  touchedReactivityKeys: Schema.optional(Schema.Array(Schema.String)),
  touchedAtoms: Schema.optional(Schema.Array(Schema.String)),
})
export type LawInferenceInput = Schema.Schema.Type<typeof LawInferenceInput>

export const LawInferenceOutput = Schema.Struct({
  operationId: Schema.String,
  laws: Schema.Array(Schema.String),
})
export type LawInferenceOutput = Schema.Schema.Type<typeof LawInferenceOutput>

export const TypeGuidanceValidationInput = Schema.Struct({
  packageId: Schema.String,
  operationIds: Schema.Array(Schema.String),
  guidanceOperationIds: Schema.Array(Schema.String),
})
export type TypeGuidanceValidationInput = Schema.Schema.Type<typeof TypeGuidanceValidationInput>

export const RpcDescriptorDerivationInput = Schema.Struct({
  packageId: Schema.String,
  operationIds: Schema.Array(Schema.String),
})
export type RpcDescriptorDerivationInput = Schema.Schema.Type<typeof RpcDescriptorDerivationInput>

export const RpcDescriptorDerivationOutput = Schema.Struct({
  packageId: Schema.String,
  groupId: Schema.String,
  rpcIds: Schema.Array(Schema.String),
  adapterStatus: Schema.Literals(["blocked", "available"] as const),
})
export type RpcDescriptorDerivationOutput = Schema.Schema.Type<typeof RpcDescriptorDerivationOutput>

export const CommandSurfaceConformanceInput = Schema.Struct({
  files: Schema.Array(Schema.Struct({
    path: Schema.String,
    content: Schema.String,
    classification: Schema.optional(Schema.Literals(["public", "internal", "bootstrap"] as const)),
  })),
  finalRatchet: Schema.optional(Schema.Boolean),
})
export type CommandSurfaceConformanceInput = Schema.Schema.Type<typeof CommandSurfaceConformanceInput>

export const GeneratorShapeConformanceInput = Schema.Struct({
  workspaceRoot: Schema.String,
  manifestPath: Schema.optional(Schema.String),
  sourceBomIndexPath: Schema.optional(Schema.String),
})
export type GeneratorShapeConformanceInput = Schema.Schema.Type<typeof GeneratorShapeConformanceInput>

export const GeneratorShapeConformanceOutput = Schema.Struct({
  ok: Schema.Boolean,
  generated: Schema.Number,
  manual: Schema.Number,
  migrate: Schema.Number,
  diagnostics: Schema.Array(ArchitectureFinding),
})
export type GeneratorShapeConformanceOutput = Schema.Schema.Type<typeof GeneratorShapeConformanceOutput>

export const SourceBomPolicyScanInput = Schema.Struct({
  shardPaths: Schema.Array(Schema.String),
})
export type SourceBomPolicyScanInput = Schema.Schema.Type<typeof SourceBomPolicyScanInput>

export const WorkspacePolicySummaryInput = Schema.Struct({
  workspaceRoot: Schema.String,
  changedFiles: Schema.optional(Schema.Array(Schema.String)),
})
export type WorkspacePolicySummaryInput = Schema.Schema.Type<typeof WorkspacePolicySummaryInput>

export const WorkspacePolicySummaryOutput = Schema.Struct({
  ok: Schema.Boolean,
  packageCount: Schema.Number,
  migratedPackageCount: Schema.Number,
  diagnostics: Schema.Array(ArchitectureFinding),
})
export type WorkspacePolicySummaryOutput = Schema.Schema.Type<typeof WorkspacePolicySummaryOutput>

const CodecViewLaws = [
  "schema.decode",
  "schema.encode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const QueryViewLaws = [
  "schema.decode",
  "schema.encode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const PolicyRuleViewLaws = [
  "schema.decode",
  "schema.encode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "policy.finding-schema",
  "policy.deterministic-findings",
  "policy.stable-diagnostic-ids",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const policyMetadata = (ruleId: string, findingSchema = "ArchitectureFinding") => ({
  ruleId,
  findingSchema,
} as const)

export const PackageContractDecodeOperation = defineOperation({
  id: "package-contract-decode",
  kind: "codec",
  input: PackageContractDecodeInput,
  output: PackageContractDecodeOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.package-contract-coverage"],
    atoms: ["packageContractCoverageAtom"],
  } as const),
  laws: CodecViewLaws,
  metadata: {
    schema: PackageContractSchema,
  },
} as const)

export const PackageContractAssertionsOperation = defineOperation({
  id: "package-contract-assertions",
  kind: "policy-rule",
  input: PackageContractAssertionInput,
  output: PolicyReportOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.package-contract-coverage", "architecture.policy-findings"],
    atoms: ["packageContractCoverageAtom", "policyFindingsAtom"],
  } as const),
  laws: PolicyRuleViewLaws,
  policy: policyMetadata("attune/package-contract/assertions"),
} as const)

export const InferOperationLawsOperation = defineOperation({
  id: "infer-operation-laws",
  kind: "query",
  input: LawInferenceInput,
  output: LawInferenceOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.law-inference-findings"],
    atoms: ["lawInferenceAtom"],
  } as const),
  laws: QueryViewLaws,
  metadata: {
    source: "package-contract/laws",
  },
} as const)

export const TypeGuidanceValidationOperation = defineOperation({
  id: "type-guidance-validate",
  kind: "policy-rule",
  input: TypeGuidanceValidationInput,
  output: PolicyReportOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.type-guidance-coverage", "architecture.policy-findings"],
    atoms: ["typeGuidanceCoverageAtom", "policyFindingsAtom"],
  } as const),
  laws: PolicyRuleViewLaws,
  policy: policyMetadata("attune/package-contract/type-guidance"),
} as const)

export const RpcDescriptorDerivationOperation = defineOperation({
  id: "derive-rpc-descriptors",
  kind: "query",
  input: RpcDescriptorDerivationInput,
  output: RpcDescriptorDerivationOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.rpc-descriptors"],
    atoms: ["rpcDescriptorAtom"],
  } as const),
  laws: QueryViewLaws,
  metadata: {
    adapter: "@effect/rpc",
    runtimeImport: "blocked-until-effect-4-compatible",
  },
} as const)

export const CommandSurfaceConformanceOperation = defineOperation({
  id: "command-surface-conformance",
  kind: "policy-rule",
  input: CommandSurfaceConformanceInput,
  output: PolicyReportOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.command-surface-findings", "architecture.policy-findings"],
    atoms: ["commandSurfaceFindingsAtom", "policyFindingsAtom"],
  } as const),
  laws: PolicyRuleViewLaws,
  policy: policyMetadata("attune/command-surface/conformance"),
} as const)

export const GeneratorShapeConformanceOperation = defineOperation({
  id: "generator-shape-conformance",
  kind: "policy-rule",
  input: GeneratorShapeConformanceInput,
  output: GeneratorShapeConformanceOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.generator-shape-findings", "architecture.policy-findings"],
    atoms: ["generatorShapeFindingsAtom", "policyFindingsAtom"],
  } as const),
  laws: PolicyRuleViewLaws,
  policy: policyMetadata("attune/generator-shape/conformance"),
} as const)

export const SourceBomPolicyScanOperation = defineOperation({
  id: "source-bom-policy-scan",
  kind: "policy-rule",
  input: SourceBomPolicyScanInput,
  output: PolicyReportOutput,
  views: touches(PackageViews, {
    reactivityKeys: ["architecture.source-bom-findings", "architecture.waiver-summary"],
    atoms: ["sourceBomPolicyFindingsAtom", "waiverSummaryAtom"],
  } as const),
  laws: PolicyRuleViewLaws,
  policy: policyMetadata("attune/source-bom/policy-scan"),
} as const)

export const WorkspacePolicySummaryOperation = defineOperation({
  id: "workspace-policy-summary",
  kind: "query",
  input: WorkspacePolicySummaryInput,
  output: WorkspacePolicySummaryOutput,
  views: touches(PackageViews, {
    reactivityKeys: [
      "architecture.workspace-policy-summary",
      "architecture.policy-findings",
      "architecture.waiver-summary",
    ],
    atoms: ["workspacePolicySummaryAtom", "policyFindingsAtom", "waiverSummaryAtom"],
  } as const),
  laws: QueryViewLaws,
  metadata: {
    source: "attune-architecture workspace policy summary",
  },
} as const)

export const PackageContract = definePackageContract({
  packageId: "attune-architecture",
  sourceRoot: "framework/architecture/src",
  packageKind: "architecture-policy",
  views: PackageViews,
  services: [] as const,
  operations: [
    PackageContractDecodeOperation,
    PackageContractAssertionsOperation,
    InferOperationLawsOperation,
    TypeGuidanceValidationOperation,
    RpcDescriptorDerivationOperation,
    CommandSurfaceConformanceOperation,
    GeneratorShapeConformanceOperation,
    SourceBomPolicyScanOperation,
    WorkspacePolicySummaryOperation,
  ] as const,
  provenance: {
    generator: "@attune/nx:package-contract",
    project: "attune-architecture",
    physicalProjectRoot: "framework/architecture",
    openspecChangeId: "standardize-effect-package-contracts",
  } as const,
  waivers: [] as const,
})
export type PackageContract = typeof PackageContract

export const PackageLayer = Layer.empty
export type PackageLayer = typeof PackageLayer

export const PackageTestLayer = Layer.empty
export type PackageTestLayer = typeof PackageTestLayer

export type ArchitectureOperationId = (typeof PackageContract.operations)[number]["id"]

const PackageGenerated = createAttuneGenerated({
  PackageContract,
  CodecViewLaws,
  PolicyRuleViewLaws,
  QueryViewLaws,
} as const)
export const PackageFuzzRpcGroup = PackageGenerated.PackageFuzzRpcGroup
export const PackageFuzzHandlers = PackageGenerated.PackageFuzzHandlers
export const PackageProperties = PackageGenerated.PackageProperties
export const PackageTypeGuidance = PackageGenerated.PackageTypeGuidance
export type PackageFuzzRpcGroup = typeof PackageFuzzRpcGroup
export type PackageFuzzHandlers = typeof PackageFuzzHandlers
export type PackageProperties = typeof PackageProperties
export type PackageTypeGuidance = typeof PackageTypeGuidance
