import { describe, expect, it } from "vitest"

import atomViewGenerator from "../src/generators/atom-view/generator.js"
import type { GeneratorTree } from "../src/internal/tree.js"

class MemoryTree implements GeneratorTree {
  readonly files = new Map<string, string>()

  exists(path: string): boolean {
    return (
      this.files.has(path) ||
      [...this.files.keys()].some((file) => file.startsWith(`${path}/`))
    )
  }

  read(path: string): string | null {
    return this.files.get(path) ?? null
  }

  write(path: string, content: string): void {
    this.files.set(path, content)
  }

  children(path: string): string[] {
    const prefix = `${path}/`
    return [...this.files.keys()]
      .filter((file) => file.startsWith(prefix))
      .map((file) => file.slice(prefix.length))
      .filter((file) => !file.includes("/"))
  }
}

const runGenerator = (): MemoryTree => {
  const tree = new MemoryTree()

  atomViewGenerator(tree, {
    name: "Host Readiness",
    projectId: "home-deployment",
    symbolId: "nixos-anywhere-install",
    directory: "packages/home-deployment/src/atoms",
    project: "home-deployment",
    reactivityKey: "host-readiness",
    generatorVersion: "0.0.0-test",
  })

  return tree
}

describe("atom-view generator", () => {
  it("generates Reactivity keys for a symbol", () => {
    const tree = runGenerator()
    const source =
      tree.files.get(
        "packages/home-deployment/src/atoms/host-readiness.reactivity.ts",
      ) ?? ""

    expect(source).toContain("Generated by @attune/nx:atom-view")
    expect(source).toContain(
      'export const hostReadinessSymbolId = "nixos-anywhere-install" as const',
    )
    expect(source).toContain(
      'hostReadiness: "host-readiness"',
    )
    expect(source).toContain("hostReadinessSymbolReactivityEdges")
  })

  it("generates base, derived, and project atom shells", () => {
    const tree = runGenerator()
    const base =
      tree.files.get(
        "packages/home-deployment/src/atoms/host-readiness.base-atom.ts",
      ) ?? ""
    const derived =
      tree.files.get(
        "packages/home-deployment/src/atoms/host-readiness.derived-atom.ts",
      ) ?? ""
    const packageView =
      tree.files.get(
        "packages/home-deployment/src/atoms/host-readiness.project-atom.ts",
      ) ?? ""

    expect(base).toContain(
      'export const hostReadinessBaseAtomId = "hostReadinessBaseAtom" as const',
    )
    expect(base).toContain("readonly reactivityKey: HostReadinessReactivityKey")
    expect(base).toContain("read: (scope: Scope) => Value")
    expect(derived).toContain(
      'export const hostReadinessDerivedAtomId = "hostReadinessDerivedAtom" as const',
    )
    expect(derived).toContain(
      "baseAtom: HostReadinessBaseAtom<Scope, Input>",
    )
    expect(packageView).toContain(
      'export const hostReadinessProjectAtomId = "hostReadinessProjectAtom" as const',
    )
    expect(packageView).toContain(
      "derivedAtom: HostReadinessDerivedAtom<Scope, Input, Input>",
    )
  })

  it("generates the project atom graph registration spine", () => {
    const tree = runGenerator()
    const graph =
      tree.files.get(
        "packages/home-deployment/src/atoms/host-readiness.atom-graph.ts",
      ) ?? ""

    expect(graph).toContain('projectId: "home-deployment"')
    expect(graph).toContain("symbol -> Reactivity key -> base atom")
    expect(graph).toContain('kind: "symbol-reactivity"')
    expect(graph).toContain('kind: "reactivity-base-atom"')
    expect(graph).toContain('kind: "base-derived-atom"')
    expect(graph).toContain('kind: "derived-project-atom"')
    expect(graph).toContain("export type HostReadinessAtomGraph")
  })

  it("updates an export barrel for generated atom-view modules", () => {
    const tree = runGenerator()

    expect(
      tree.files.get("packages/home-deployment/src/atoms/index.ts"),
    ).toEqual(
      [
        'export * from "./host-readiness.atom-graph.js"',
        'export * from "./host-readiness.base-atom.js"',
        'export * from "./host-readiness.derived-atom.js"',
        'export * from "./host-readiness.project-atom.js"',
        'export * from "./host-readiness.reactivity.js"',
        "",
      ].join("\n"),
    )
  })

  it("records artifact provenance for atom-view ownership", () => {
    const tree = runGenerator()
    const shard = JSON.parse(
      tree.files.get("packages/home-deployment/attune.source-bom.json") ?? "{}",
    )

    expect(shard).toMatchObject({
      schemaVersion: 1,
      project: "home-deployment",
      projectRoot: "packages/home-deployment",
    })
    expect(shard.entries[0]).toMatchObject({
      generatorName: "@attune/nx:atom-view",
      generatorVersion: "0.0.0-test",
      owningProject: "home-deployment",
      sourceShapeKind: "atom-view",
      options: {
        directory: "packages/home-deployment/src/atoms",
        name: "Host Readiness",
        symbolId: "nixos-anywhere-install",
        projectId: "home-deployment",
        reactivityKey: "host-readiness",
      },
      checkTargets: [
        { project: "home-deployment", target: "atom-graph-conformance" },
      ],
      syncTargets: [
        { project: "home-deployment", target: "sync-project-facts" },
      ],
    })
    expect(shard.entries[0].ownedFiles).toEqual([
      "packages/home-deployment/src/atoms/host-readiness.atom-graph.ts",
      "packages/home-deployment/src/atoms/host-readiness.base-atom.ts",
      "packages/home-deployment/src/atoms/host-readiness.derived-atom.ts",
      "packages/home-deployment/src/atoms/host-readiness.project-atom.ts",
      "packages/home-deployment/src/atoms/host-readiness.reactivity.ts",
      "packages/home-deployment/src/atoms/index.ts",
    ])
  })

  it("emits deterministic output across repeated runs", () => {
    const tree = runGenerator()
    const first = new Map(tree.files)

    atomViewGenerator(tree, {
      name: "Host Readiness",
      projectId: "home-deployment",
      symbolId: "nixos-anywhere-install",
      directory: "packages/home-deployment/src/atoms",
      project: "home-deployment",
      reactivityKey: "host-readiness",
      generatorVersion: "0.0.0-test",
    })

    expect(tree.files).toEqual(first)
  })
})
