import { execFileSync } from "node:child_process"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { describe, expect, it } from "vitest"

import packageContractGenerator from "../src/generators/package-contract/generator.js"
import type { GeneratorTree } from "../src/internal/tree.js"

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..")

class MemoryTree implements GeneratorTree {
  readonly files = new Map<string, string>()

  exists(path: string): boolean {
    return (
      this.files.has(path) ||
      [...this.files.keys()].some((file) => file.startsWith(`${path}/`))
    )
  }

  read(path: string): string | null {
    return this.files.get(path) ?? null
  }

  write(path: string, content: string): void {
    this.files.set(path, content)
  }

  children(path: string): string[] {
    const prefix = `${path}/`
    return [...this.files.keys()]
      .filter((file) => file.startsWith(prefix))
      .map((file) => file.slice(prefix.length))
      .filter((file) => !file.includes("/"))
  }
}

describe("@attune/nx package-contract generator", () => {
  it("exposes a source-local .js bridge for Nx source mode", async () => {
    const sourceLocal = await import(
      "../src/generators/package-contract/generator.js"
    )

    expect(sourceLocal.default).toBe(packageContractGenerator)
  })

  it("is executable through the real Nx generator surface in local source mode", () => {
    const nxBin = resolve(repositoryRoot, "node_modules/.bin/nx")
    const output = execFileSync(
      nxBin,
      [
        "generate",
        "@attune/nx:package-contract",
        "--packageId",
        "generator-smoke",
        "--packageKind",
        "generator-tooling",
        "--directory",
        "packages/attune-nx/src/generated-smoke",
        "--dry-run",
      ],
      {
        cwd: repositoryRoot,
        encoding: "utf8",
        env: {
          ...process.env,
          NX_DAEMON: "false",
        },
      },
    )

    expect(output).toContain("CREATE packages/attune-nx/src/generated-smoke/attune.package.ts")
    expect(output).not.toContain("Cannot find module")
  })

  it("generates an Effect Schema-backed package contract and compile-only assertions", () => {
    const tree = new MemoryTree()

    packageContractGenerator(tree, {
      packageId: "attune-nx",
      packageKind: "generator-tooling",
      sourceRoot: "packages/attune-nx",
      project: "attune-nx",
      operationId: "package-contract-generator",
      operationKind: "generator",
      operationName: "Package Contract Generator",
      generatorVersion: "0.0.0-test",
    })

    const contract =
      tree.files.get("packages/attune-nx/src/attune.package.ts") ?? ""
    const generated =
      tree.files.get("packages/attune-nx/src/attune.package.generated.ts") ??
      ""
    const property =
      tree.files.get("packages/attune-nx/src/attune.package.property.ts") ??
      ""
    const typecheck =
      tree.files.get("packages/attune-nx/src/attune.package.typecheck.ts") ??
      ""

    expect(contract).toContain(
      "Generated by @attune/nx:package-contract",
    )
    expect(contract).toContain('from "@attune/framework-protocol"')
    expect(contract).toContain("export { PackageContractSchema }")
    expect(contract).toContain("definePackageContract")
    expect(contract).toContain("definePackageViews")
    expect(contract).toContain("defineTypeGuidance")
    expect(contract).toContain(
      'packageKind: "generator-tooling"',
    )
    expect(contract).toContain(
      'id: "package-contract-generator"',
    )
    expect(contract).toContain('kind: "generator"')
    expect(contract).toContain(
      'generator.provenance-recorded',
    )
    expect(contract).toContain(
      'export const PackageLayer = Layer.empty',
    )
    expect(contract).toContain(
      "export const PackageHarnessAccessors",
    )
    expect(contract).toContain(
      "publicAccessors: PackageHarnessAccessors",
    )
    expect(contract).toContain(
      "export const PackageTypeGuidance = defineTypeGuidance",
    )
    expect(contract).toContain('kind: "contract-operation"')
    expect(contract).toContain('kind: "generator-metadata"')
    expect(contract).toContain('kind: "operation-id"')
    expect(contract).toContain('kind: "operation-kind"')
    expect(contract).toContain('kind: "generator-provenance"')
    expect(contract).toContain(
      'transformIds: ["package-contract-generator.schema-guided"]',
    )
    expect(contract).toContain('transforms: [')
    expect(contract).toContain('filters: []')
    expect(contract).toContain(
      '"coverage:package-contract-generator:package-view"',
    )

    expect(generated).toContain("PackageOperationRegistry")
    expect(generated).toContain("createPackageHarnessClient")
    expect(generated).toContain("PackageHarnessHandlers")
    expect(generated).toContain("publicAccessorHandler(\"package-contract-generator\")")
    expect(generated).toContain("PackageHarnessEvidenceProducers")
    expect(generated).toContain("PackageHarnessClient")
    expect(generated).toContain("PackageHarnessControls")
    expect(generated).toContain("typeGuidancePartitionEvidence")
    expect(generated).toContain("PackagePropertyEvidencePlan")
    expect(generated).toContain('harness: "PackageHarnessClient"')
    expect(generated).toContain('handlerMap: "PackageHarnessHandlers"')
    expect(generated).toContain('evidenceProducerMap: "PackageHarnessEvidenceProducers"')
    expect(generated).toContain('"harness.control.observe"')
    expect(generated).toContain('"harness.schema-coded-client"')
    expect(generated).toContain('"evidence.producer-map"')
    expect(generated).toContain('"type-guidance.partitions"')
    expect(generated).toContain('partitionKind: "schema-boundary"')
    expect(generated).toContain('partitionKind: "reactivity-key"')
    expect(generated).toContain('status: "miss"')
    expect(generated).toContain("PackageAtomViewGraph")
    expect(generated).toContain("PackageProtocolReportPolicy")
    expect(generated).toContain('workerModule: "./attune.package.property.js"')
    expect(generated).toContain('evidenceRoot: ".attune/cache/property-evidence"')
    expect(generated).toContain("checkedInProtocolReports: false")
    expect(generated).not.toContain("ProtocolDelta.md")
    expect(generated).not.toContain("protocol-report")

    expect(property).toContain('from "@fast-check/worker"')
    expect(property).toContain("propertyFor(new URL(import.meta.url)")
    expect(property).toContain('randomSource: "worker"')
    expect(property).toContain("PackageWorkerProperties")

    expect(typecheck).toContain("AssertPackageContract")
    expect(typecheck).toContain("AssertTypeGuidanceComplete")
    expect(typecheck).toContain("AssertExactHandlers")
    expect(typecheck).toContain("AssertPropertyHarnesses")
    expect(typecheck).toContain('from "./attune.package.generated.js"')
    expect(typecheck).toContain(
      "PackageFuzzHandlers",
    )
  })

  it("supports pure/minimal package layer output for non-service packages", () => {
    const tree = new MemoryTree()

    packageContractGenerator(tree, {
      packageId: "effect-oxlint-policy",
      packageKind: "policy-plugin",
      directory: "packages/effect-oxlint-policy/src",
      operationId: "scan-effect-policy",
      operationKind: "policy-rule",
    })

    const contract =
      tree.files.get("packages/effect-oxlint-policy/src/attune.package.ts") ??
      ""
    const shard = JSON.parse(
      tree.files.get(
        "packages/effect-oxlint-policy/attune.source-bom.json",
      ) ?? "{}",
    )

    expect(contract).toContain('sourceRoot: "packages/effect-oxlint-policy"')
    expect(contract).toContain('packageKind: "policy-plugin"')
    expect(contract).toContain('policy: {')
    expect(contract).toContain('services: [] as const')
    expect(contract).toContain('export const PackageLayer = Layer.empty')
    expect(contract).toContain('publicAccessors: PackageHarnessAccessors')
    expect(shard).toMatchObject({
      schemaVersion: 1,
      project: "effect-oxlint-policy",
      projectRoot: "packages/effect-oxlint-policy",
    })
    expect(shard.entries[0]).toMatchObject({
      generatorName: "@attune/nx:package-contract",
      owningProject: "effect-oxlint-policy",
      sourceShapeKind: "package-contract",
      options: {
        directory: "packages/effect-oxlint-policy/src",
        operationId: "scan-effect-policy",
        operationKind: "policy-rule",
        packageId: "effect-oxlint-policy",
        packageKind: "policy-plugin",
        project: "effect-oxlint-policy",
        sourceRoot: "packages/effect-oxlint-policy",
      },
      ownedFiles: [
        "packages/effect-oxlint-policy/src/attune.package.generated.ts",
        "packages/effect-oxlint-policy/src/attune.package.property.ts",
        "packages/effect-oxlint-policy/src/attune.package.ts",
        "packages/effect-oxlint-policy/src/attune.package.typecheck.ts",
      ],
      syncTargets: [
        {
          project: "effect-oxlint-policy",
          target: "sync-package-contract",
        },
      ],
      checkTargets: [
        {
          project: "effect-oxlint-policy",
          target: "typecheck",
        },
        {
          project: "workspace",
          target: "package-contracts-check",
        },
      ],
      openspecChangeId: "standardize-effect-package-contracts",
    })
  })

  it("emits deterministic output for the same package contract options", () => {
    const first = new MemoryTree()
    const second = new MemoryTree()
    const options = {
      packageId: "home-deployment",
      packageKind: "day0-resource-runbook" as const,
      sourceRoot: "packages/home-deployment",
      project: "home-deployment",
      operationId: "nixos-anywhere-install",
      operationKind: "resource-provider" as const,
      operationName: "Nixos Anywhere Install",
    }

    packageContractGenerator(first, options)
    packageContractGenerator(second, options)
    packageContractGenerator(second, options)

    expect([...second.files.keys()].sort()).toEqual([
      "attune.source-bom.index.json",
      "packages/home-deployment/attune.source-bom.json",
      "packages/home-deployment/src/attune.package.generated.ts",
      "packages/home-deployment/src/attune.package.property.ts",
      "packages/home-deployment/src/attune.package.ts",
      "packages/home-deployment/src/attune.package.typecheck.ts",
    ])
    expect(second.files).toEqual(first.files)
    expect(
      second.files.get("packages/home-deployment/src/attune.package.ts"),
    ).toContain('observes: {')
    expect(
      second.files.get("packages/home-deployment/src/attune.package.ts"),
    ).toContain('"nixos-anywhere-install.resource.observed"')
    expect(
      second.files.get("packages/home-deployment/src/attune.package.ts"),
    ).toContain('"nixos-anywhere-install.destructive.gate"')
  })
})
