import { execFileSync } from "node:child_process"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { describe, expect, it } from "vitest"

import projectFactsGenerator from "../src/generators/project-facts/generator.js"
import type { GeneratorTree } from "../src/internal/tree.js"

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..")

class MemoryTree implements GeneratorTree {
  readonly files = new Map<string, string>()

  exists(path: string): boolean {
    return (
      this.files.has(path) ||
      [...this.files.keys()].some((file) => file.startsWith(`${path}/`))
    )
  }

  read(path: string): string | null {
    return this.files.get(path) ?? null
  }

  write(path: string, content: string): void {
    this.files.set(path, content)
  }

  children(path: string): string[] {
    const prefix = `${path}/`
    return [...this.files.keys()]
      .filter((file) => file.startsWith(prefix))
      .map((file) => file.slice(prefix.length))
      .filter((file) => !file.includes("/"))
  }
}

describe("@attune/nx project-facts generator", () => {
  it("exposes a source-local .js bridge for Nx source mode", async () => {
    const sourceLocal = await import(
      "../src/generators/project-facts/generator.js"
    )

    expect(sourceLocal.default).toBe(projectFactsGenerator)
  })

  it("is executable through the real Nx generator surface in local source mode", () => {
    const nxBin = resolve(repositoryRoot, "node_modules/.bin/nx")
    const output = execFileSync(
      nxBin,
      [
        "generate",
        "@attune/nx:project-facts",
        "--projectId",
        "generator-smoke",
        "--projectKind",
        "generator-tooling",
        "--directory",
        "packages/attune-nx/src/generated-smoke",
        "--dry-run",
      ],
      {
        cwd: repositoryRoot,
        encoding: "utf8",
        env: {
          ...process.env,
          NX_DAEMON: "false",
        },
      },
    )

    expect(output).toContain("CREATE packages/attune-nx/src/generated-smoke/attune.package.ts")
    expect(output).not.toContain("Cannot find module")
  })

  it("generates mechanical project facts without old compatibility helper objects", () => {
    const tree = new MemoryTree()

    projectFactsGenerator(tree, {
      projectId: "attune-nx",
      projectKind: "generator-tooling",
      sourceRoot: "packages/attune-nx",
      owningProject: "attune-nx",
      symbolId: "project-facts-generator",
      symbolKind: "generator",
      symbolName: "Project Facts Generator",
      generatorVersion: "0.0.0-test",
    })

    const facts =
      tree.files.get("packages/attune-nx/src/attune.package.ts") ?? ""
    const generated =
      tree.files.get("packages/attune-nx/src/attune.project-facts.generated.ts") ??
      ""
    const observations =
      tree.files.get("packages/attune-nx/src/attune.project-observations.ts") ??
      ""

    expect(facts).toContain(
      "Generated by @attune/nx:project-facts",
    )
    expect(facts).toContain('from "@attune/framework-protocol"')
    expect(facts).toContain("defineAttuneProjectFacts")
    expect(facts).toContain("mechanical project/source_file/symbol")
    expect(facts).toContain('kind: "generator-tooling"')
    expect(facts).toContain('id: "project-facts-generator"')
    expect(facts).toContain('kind: "generator"')
    expect(facts).toContain('id: "attune-nx.project-facts-generator.changed"')
    expect(facts).toContain("ProgramSymbolAccessors")
    expect(facts).toContain("ProjectLayer")
    expect(facts).not.toContain("definePackageContract")
    expect(facts).not.toContain("definePackageViews")
    expect(facts).not.toContain("defineTypeGuidance")
    expect(facts).not.toContain("PackageContract")

    expect(generated).toContain("ProgramSymbolRegistry")
    expect(generated).toContain("ProgramObservationPlan")
    expect(generated).toContain("ProgramRuntimeGraph")
    expect(generated).toContain("ProgramGeneratedArtifacts")
    expect(generated).toContain("ProgramReportPolicy")
    expect(generated).toContain('workerModule: "./attune.project-observations.js"')
    expect(generated).toContain('observationRoot: ".attune/cache/observations"')
    expect(generated).toContain("checkedInReports: false")
    expect(generated).not.toContain("PackageOperationRegistry")
    expect(generated).not.toContain("PackageFuzzHandlers")
    expect(generated).not.toContain("PackageProperties")
    expect(generated).not.toContain("PackagePropertyEvidencePlan")
    expect(generated).not.toContain("PackageAtomViewGraph")
    expect(generated).not.toContain("PackageProtocolReportPolicy")
    expect(generated).not.toContain("ProtocolDelta.md")
    expect(generated).not.toContain("protocol-report")

    expect(observations).toContain('from "@fast-check/worker"')
    expect(observations).toContain("propertyFor(new URL(import.meta.url)")
    expect(observations).toContain('randomSource: "worker"')
    expect(observations).toContain("ProgramWorkerObservations")
    expect(observations).not.toContain("PackageWorkerProperties")

    expect(tree.files.has("packages/attune-nx/src/attune.package.typecheck.ts")).toBe(false)
  })

  it("supports pure/minimal project layer output for non-service projects", () => {
    const tree = new MemoryTree()

    projectFactsGenerator(tree, {
      projectId: "effect-oxlint-policy",
      projectKind: "policy-plugin",
      directory: "framework/oxlint-policy/src",
      owningProject: "effect-oxlint-policy",
      symbolId: "scan-effect-policy",
      symbolKind: "policy-rule",
    })

    const facts =
      tree.files.get("framework/oxlint-policy/src/attune.package.ts") ??
      ""
    const shard = JSON.parse(
      tree.files.get(
        "framework/oxlint-policy/attune.source-bom.json",
      ) ?? "{}",
    )

    expect(facts).toContain('kind: "policy-plugin"')
    expect(facts).toContain('kind: "policy-rule"')
    expect(facts).toContain("ProjectLayer")
    expect(facts).toContain("ProgramSymbolAccessors")
    expect(facts).not.toContain("PackageLayer")
    expect(facts).not.toContain("definePackageContract")
    expect(shard).toMatchObject({
      schemaVersion: 1,
      project: "effect-oxlint-policy",
      projectRoot: "framework/oxlint-policy",
    })
    expect(shard.entries[0]).toMatchObject({
      generatorName: "@attune/nx:project-facts",
      owningProject: "effect-oxlint-policy",
      sourceShapeKind: "project-facts",
      options: {
        directory: "framework/oxlint-policy/src",
        owningProject: "effect-oxlint-policy",
        projectId: "effect-oxlint-policy",
        projectKind: "policy-plugin",
        sourceRoot: "framework/oxlint-policy",
        symbolId: "scan-effect-policy",
        symbolKind: "policy-rule",
      },
      ownedFiles: [
        "framework/oxlint-policy/src/attune.package.ts",
        "framework/oxlint-policy/src/attune.project-facts.generated.ts",
        "framework/oxlint-policy/src/attune.project-observations.ts",
      ],
      syncTargets: [
        {
          project: "effect-oxlint-policy",
          target: "sync-project-facts",
        },
      ],
      checkTargets: [
        {
          project: "effect-oxlint-policy",
          target: "typecheck",
        },
        {
          project: "workspace",
          target: "attune-check",
        },
      ],
      openspecChangeId: "promote-program-index-runtime-substrate",
    })
  })

  it("emits deterministic output for the same project facts options", () => {
    const first = new MemoryTree()
    const second = new MemoryTree()
    const options = {
      projectId: "home-deployment",
      projectKind: "day0-resource-runbook" as const,
      sourceRoot: "packages/home-deployment",
      owningProject: "home-deployment",
      symbolId: "nixos-anywhere-install",
      symbolKind: "resource-provider" as const,
      symbolName: "Nixos Anywhere Install",
    }

    projectFactsGenerator(first, options)
    projectFactsGenerator(second, options)
    projectFactsGenerator(second, options)

    expect([...second.files.keys()].sort()).toEqual([
      "attune.source-bom.index.json",
      "packages/home-deployment/attune.source-bom.json",
      "packages/home-deployment/src/attune.package.ts",
      "packages/home-deployment/src/attune.project-facts.generated.ts",
      "packages/home-deployment/src/attune.project-observations.ts",
    ])
    expect(second.files).toEqual(first.files)
    expect(
      second.files.get("packages/home-deployment/src/attune.package.ts"),
    ).toContain('"nixos-anywhere-install.resource.observed"')
    expect(
      second.files.get("packages/home-deployment/src/attune.package.ts"),
    ).toContain('"nixos-anywhere-install.destructive.gate"')
  })
})
