/* @generated by @attune/nx:attune-repair. Do not edit directly. */
/* Materialized package contract; edit ./attune.package.ts and run Nx repair. */
import { Layer, Schema } from "effect"
import {
  defineOperation,
  definePackageContract,
  definePackageViews,
  defineTypeGuidance,
  touches,
} from "@attune/framework-protocol"
import { createAttuneGenerated } from "./attune.generated.js"

export { PackageContractSchema } from "@attune/framework-protocol"

export const PackageViews = definePackageViews({
  reactivityKeys: [
    "joern-effect-properties.property-run.changed",
    "joern-effect-properties.fuzz-run.changed",
    "joern-effect-properties.corpus.changed",
    "joern-effect-properties.counterexample.changed",
    "joern-effect-properties.worker-shard.changed",
    "joern-effect-properties.workspace-pool.changed",
    "joern-effect-properties.coverage-feedback.changed",
    "joern-effect-properties.weak-oracle.changed",
    "joern-effect-properties.telemetry.changed",
  ],
  atoms: [
    "propertyRunAtom",
    "fuzzRunAtom",
    "corpusAtom",
    "counterexampleAtom",
    "workerShardAtom",
    "workspacePoolAtom",
    "coverageFeedbackAtom",
    "weakOracleFindingAtom",
    "telemetryEventAtom",
  ],
} as const)

export const PropertyProofServices = [
  "joern-effect-properties/PropertyHarnessRuntime",
  "joern-effect-properties/SemanticCorpusStore",
  "joern-effect-properties/CounterexampleStore",
  "joern-effect-properties/SemanticMutator",
  "joern-effect-properties/SemanticFuzzScheduler",
  "joern-effect-properties/JoernWorkspacePool",
  "joern-effect-properties/FuzzOracle",
  "joern-effect-properties/FuzzTelemetry",
  "joern-effect-properties/CoverageSearch",
  "joern-effect-properties/WorkerProperty",
] as const

export const PropertyProofRequiredServices = [
  "joern-effect/Joern",
  "joern-effect/CpgProgramBuilder",
  "attune.property-event-runtime",
  "filesystem.temp-workspace",
] as const

export const PropertyProofContractError = Schema.Struct({
  code: Schema.Literal(
    "property-harness-failed",
    "corpus-unavailable",
    "counterexample-record-failed",
    "mutation-rejected",
    "scheduler-failed",
    "workspace-pool-failed",
    "oracle-disagreement",
    "telemetry-emit-failed",
    "coverage-feedback-failed",
    "worker-property-failed",
    "package-view-unavailable",
  ),
  message: Schema.String,
  operationId: Schema.optional(Schema.String),
  replayId: Schema.optional(Schema.String),
})
export type PropertyProofContractError = typeof PropertyProofContractError.Type

export const FuzzPreset = Schema.Literal("smoke", "workbench", "nightly", "campaign")
export type FuzzPreset = typeof FuzzPreset.Type

export const JoernExecutionMode = Schema.Literal("none", "import", "query")
export type JoernExecutionMode = typeof JoernExecutionMode.Type

export const SyntaxFlavor = Schema.Literal("js", "ts", "jsx", "tsx")
export type SyntaxFlavor = typeof SyntaxFlavor.Type

export const CorpusOrigin = Schema.Literal(
  "curated",
  "typescript-docs",
  "parser-fixture",
  "promoted-counterexample",
)
export type CorpusOrigin = typeof CorpusOrigin.Type

export const MutationKind = Schema.Literal(
  "module-split",
  "function-wrap",
  "async-boundary",
  "generic-decode",
  "object-destructure",
  "optional-chain",
  "jsx-prop-flow",
  "source-sink-flow",
  "class-method",
  "import-export-shape",
)
export type MutationKind = typeof MutationKind.Type

export const WorkerResourceTier = Schema.Literal(
  "commit",
  "push",
  "proof-pressure",
  "nightly",
)
export type WorkerResourceTier = typeof WorkerResourceTier.Type

export const WorkerEvidenceStatus = Schema.Literal(
  "passed",
  "failed",
  "timed-out",
  "skipped",
)
export type WorkerEvidenceStatus = typeof WorkerEvidenceStatus.Type

export const CoverageFindingKind = Schema.Literal(
  "high-rejection-filter",
  "missing-atom-graph-movement",
  "dead-harness",
  "weak-oracle",
)
export type CoverageFindingKind = typeof CoverageFindingKind.Type

export const PropertyHarnessRuntimeInput = Schema.Struct({
  localEvents: Schema.Boolean,
  mode: FuzzPreset,
  runId: Schema.optional(Schema.String),
  workerCount: Schema.Number,
  workspaceRootPath: Schema.optional(Schema.String),
})
export type PropertyHarnessRuntimeInput = typeof PropertyHarnessRuntimeInput.Type

export const PropertyHarnessRuntimeOutput = Schema.Struct({
  deterministic: Schema.Boolean,
  eventRuntime: Schema.Literal("local", "axiom", "disabled"),
  localEvents: Schema.Boolean,
  runId: Schema.String,
  workerCount: Schema.Number,
})
export type PropertyHarnessRuntimeOutput = typeof PropertyHarnessRuntimeOutput.Type

export const SemanticCorpusStoreInput = Schema.Struct({
  includePromoted: Schema.Boolean,
  limit: Schema.optional(Schema.Number),
  origin: Schema.optional(CorpusOrigin),
})
export type SemanticCorpusStoreInput = typeof SemanticCorpusStoreInput.Type

export const SemanticCorpusStoreOutput = Schema.Struct({
  corpusAtomId: Schema.String,
  origins: Schema.Array(Schema.String),
  promotedSeedCount: Schema.Number,
  seedCount: Schema.Number,
})
export type SemanticCorpusStoreOutput = typeof SemanticCorpusStoreOutput.Type

export const CounterexampleStoreInput = Schema.Struct({
  action: Schema.Literal("list", "record", "promote"),
  failureClass: Schema.optional(Schema.String),
  seedId: Schema.optional(Schema.String),
  syntaxFlavor: Schema.optional(SyntaxFlavor),
})
export type CounterexampleStoreInput = typeof CounterexampleStoreInput.Type

export const CounterexampleStoreOutput = Schema.Struct({
  candidateCount: Schema.Number,
  counterexampleAtomId: Schema.String,
  latestSeedId: Schema.optional(Schema.String),
  promotedSeedCount: Schema.Number,
})
export type CounterexampleStoreOutput = typeof CounterexampleStoreOutput.Type

export const SemanticMutatorInput = Schema.Struct({
  mutationKinds: Schema.Array(MutationKind),
  replayPath: Schema.optional(Schema.String),
  seedId: Schema.String,
  syntaxFlavor: SyntaxFlavor,
})
export type SemanticMutatorInput = typeof SemanticMutatorInput.Type

export const SemanticMutatorOutput = Schema.Struct({
  appliedMutations: Schema.Array(Schema.String),
  caseId: Schema.String,
  rejectedMutations: Schema.Array(Schema.String),
  sourceFiles: Schema.Number,
})
export type SemanticMutatorOutput = typeof SemanticMutatorOutput.Type

export const SemanticFuzzSchedulerInput = Schema.Struct({
  batches: Schema.optional(Schema.Number),
  cases: Schema.Number,
  joernMode: JoernExecutionMode,
  mode: FuzzPreset,
  queryFeedback: Schema.Boolean,
  seed: Schema.Number,
  workerCount: Schema.Number,
  workspaceRootPath: Schema.optional(Schema.String),
})
export type SemanticFuzzSchedulerInput = typeof SemanticFuzzSchedulerInput.Type

export const SemanticFuzzSchedulerOutput = Schema.Struct({
  accepted: Schema.Number,
  batches: Schema.optional(Schema.Number),
  cases: Schema.Number,
  mode: FuzzPreset,
  rejected: Schema.Number,
  runId: Schema.String,
  target: Schema.String,
  workerShards: Schema.Number,
})
export type SemanticFuzzSchedulerOutput = typeof SemanticFuzzSchedulerOutput.Type

export const JoernWorkspacePoolInput = Schema.Struct({
  importProject: Schema.Boolean,
  rootPath: Schema.optional(Schema.String),
  workerId: Schema.optional(Schema.String),
})
export type JoernWorkspacePoolInput = typeof JoernWorkspacePoolInput.Type

export const JoernWorkspacePoolOutput = Schema.Struct({
  cleanedUp: Schema.Boolean,
  imported: Schema.Boolean,
  projectName: Schema.String,
  workerId: Schema.String,
  workspacePath: Schema.String,
})
export type JoernWorkspacePoolOutput = typeof JoernWorkspacePoolOutput.Type

export const FuzzOracleInput = Schema.Struct({
  caseCount: Schema.Number,
  mode: Schema.Literal("import", "query"),
  queryBudget: Schema.optional(Schema.Number),
  queryFeedback: Schema.Boolean,
})
export type FuzzOracleInput = typeof FuzzOracleInput.Type

export const FuzzOracleOutput = Schema.Struct({
  expectationFailures: Schema.Number,
  oracleAtomId: Schema.String,
  projectName: Schema.String,
  queryResultCount: Schema.Number,
  workerId: Schema.String,
})
export type FuzzOracleOutput = typeof FuzzOracleOutput.Type

export const FuzzTelemetryInput = Schema.Struct({
  eventType: Schema.String,
  localEvents: Schema.Boolean,
  runId: Schema.optional(Schema.String),
  target: Schema.String,
})
export type FuzzTelemetryInput = typeof FuzzTelemetryInput.Type

export const FuzzTelemetryOutput = Schema.Struct({
  emitted: Schema.Boolean,
  eventType: Schema.String,
  flushed: Schema.Boolean,
  telemetryAtomId: Schema.String,
})
export type FuzzTelemetryOutput = typeof FuzzTelemetryOutput.Type

export const CoverageSearchFeedbackInput = Schema.Struct({
  includeAtomGraph: Schema.Boolean,
  includeV8: Schema.Boolean,
  includeWeakOracle: Schema.Boolean,
  operationIds: Schema.Array(Schema.String),
})
export type CoverageSearchFeedbackInput = typeof CoverageSearchFeedbackInput.Type

export const CoverageSearchFeedbackOutput = Schema.Struct({
  atomGraphMovements: Schema.Number,
  coverageDeltas: Schema.Number,
  coverageFeedbackAtomId: Schema.String,
  findings: Schema.Number,
  retainedSeeds: Schema.Number,
  weakOracleFindings: Schema.Number,
})
export type CoverageSearchFeedbackOutput = typeof CoverageSearchFeedbackOutput.Type

export const WorkerPropertyWrapperInput = Schema.Struct({
  generatedValuesSerializable: Schema.Boolean,
  operationId: Schema.optional(Schema.String),
  propertyId: Schema.String,
  resourceTier: WorkerResourceTier,
  seed: Schema.Number,
  timeoutMs: Schema.Number,
  workerCount: Schema.Number,
})
export type WorkerPropertyWrapperInput = typeof WorkerPropertyWrapperInput.Type

export const WorkerPropertyWrapperOutput = Schema.Struct({
  descriptorKind: Schema.Literal("attune.worker-property"),
  preservesShrinking: Schema.Boolean,
  propertyId: Schema.String,
  randomSource: Schema.Literal("main-thread", "worker"),
  shardId: Schema.String,
  status: WorkerEvidenceStatus,
  workerCount: Schema.Number,
})
export type WorkerPropertyWrapperOutput = typeof WorkerPropertyWrapperOutput.Type

export const PackageViewAtomInput = Schema.Struct({
  atomId: Schema.Literal(
    "propertyRunAtom",
    "fuzzRunAtom",
    "corpusAtom",
    "counterexampleAtom",
    "workerShardAtom",
    "workspacePoolAtom",
    "coverageFeedbackAtom",
    "weakOracleFindingAtom",
    "telemetryEventAtom",
  ),
  operationId: Schema.optional(Schema.String),
})
export type PackageViewAtomInput = typeof PackageViewAtomInput.Type

export const PackageViewAtomOutput = Schema.Struct({
  atomId: Schema.String,
  dependsOnAtoms: Schema.Array(Schema.String),
  observed: Schema.Boolean,
  reactivityKeys: Schema.Array(Schema.String),
  summary: Schema.String,
  valueKind: Schema.Literal(
    "property-run",
    "fuzz-run",
    "corpus",
    "counterexample",
    "worker-shard",
    "workspace-pool",
    "coverage-feedback",
    "weak-oracle",
    "telemetry",
  ),
})
export type PackageViewAtomOutput = typeof PackageViewAtomOutput.Type

export const ProofEvidenceTier = Schema.Literal(
  "commit",
  "push",
  "proof-pressure",
  "nightly",
)
export type ProofEvidenceTier = typeof ProofEvidenceTier.Type

export const ProofPropertyEvidenceSummary = Schema.Struct({
  packageId: Schema.Literal("joern-effect-properties"),
  operationId: Schema.String,
  tier: ProofEvidenceTier,
  status: WorkerEvidenceStatus,
  runId: Schema.String,
  seed: Schema.Number,
  shardId: Schema.String,
  workerId: Schema.optional(Schema.String),
  lawIds: Schema.Array(Schema.String),
  reactivityKeys: Schema.Array(Schema.String),
  atomIds: Schema.Array(Schema.String),
  coveragePointIds: Schema.Array(Schema.String),
  counterexampleSeedId: Schema.optional(Schema.String),
})
export type ProofPropertyEvidenceSummary = typeof ProofPropertyEvidenceSummary.Type

export const ProofAtomGraphCoverageSummary = Schema.Struct({
  operationId: Schema.String,
  requiredEdges: Schema.Array(Schema.String),
  movedEdges: Schema.Array(Schema.String),
  missingEdges: Schema.Array(Schema.String),
  reactivityKeysHit: Schema.Array(Schema.String),
  atomsRefreshed: Schema.Array(Schema.String),
  viewAtomsChanged: Schema.Array(Schema.String),
})
export type ProofAtomGraphCoverageSummary =
  typeof ProofAtomGraphCoverageSummary.Type

export const ProofTypedTargetIntent = Schema.Struct({
  targetName: Schema.String,
  intendedExecutor: Schema.Literal(
    "attune:package-check",
    "attune:generated",
    "attune:toolchain",
  ),
  resourceTier: ProofEvidenceTier,
  commandSurfaceWaiverId: Schema.optional(Schema.String),
  operationIds: Schema.Array(Schema.String),
  typedOptions: Schema.Record({ key: Schema.String, value: Schema.Unknown }),
})
export type ProofTypedTargetIntent = typeof ProofTypedTargetIntent.Type

const propertyRunKeys = [
  "joern-effect-properties.property-run.changed",
  "joern-effect-properties.telemetry.changed",
] as const

const fuzzRunKeys = [
  "joern-effect-properties.fuzz-run.changed",
  "joern-effect-properties.worker-shard.changed",
  "joern-effect-properties.workspace-pool.changed",
  "joern-effect-properties.telemetry.changed",
] as const

const corpusKeys = [
  "joern-effect-properties.corpus.changed",
] as const

const counterexampleKeys = [
  "joern-effect-properties.counterexample.changed",
  "joern-effect-properties.corpus.changed",
] as const

const coverageKeys = [
  "joern-effect-properties.coverage-feedback.changed",
  "joern-effect-properties.weak-oracle.changed",
] as const

const workerKeys = [
  "joern-effect-properties.worker-shard.changed",
  "joern-effect-properties.property-run.changed",
  "joern-effect-properties.counterexample.changed",
] as const

const schemaLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
] as const

const queryLaws = [
  ...schemaLaws,
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const commandLaws = [
  ...schemaLaws,
  "side-effect.declared-boundary",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const generatorLaws = [
  ...schemaLaws,
  "determinism.same-input-same-output",
  "side-effect.virtual-tree-only",
  "generator.options-decode",
  "generator.deterministic-output",
  "generator.provenance-recorded",
  "generator.no-untracked-output",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const resourceProviderLaws = [
  ...schemaLaws,
  "side-effect.declared-boundary",
  "resource.observe-before-apply",
  "resource.observed-idempotence",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const joernTemplateLaws = [
  ...schemaLaws,
  "determinism.same-input-same-output",
  "side-effect.declared-boundary",
  "joern.template-binding-schema",
  "joern.evidence-schema",
  "joern.deterministic-template",
  "joern.normalized-evidence",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const eventFacadeLaws = [
  ...schemaLaws,
  "side-effect.declared-boundary",
  "event-facade.event-schema",
  "event-facade.append-boundary",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const projectionLaws = [
  ...schemaLaws,
  "side-effect.declared-boundary",
  "projection.event-decode",
  "projection.state-decode",
  "projection.deterministic-replay",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

const atomFamilyLaws = [
  ...schemaLaws,
  "side-effect.no-durable-atom-write",
  "atom-family.base-refresh",
  "atom-family.derived-composes",
  "view.reactivity-key-moves",
  "view.atom-moves",
  "view.package-view-moves",
] as const

export const propertyHarnessRuntimeOperation = defineOperation({
  id: "property-harness-runtime",
  name: "Property harness runtime configuration",
  kind: "command",
  input: PropertyHarnessRuntimeInput,
  output: PropertyHarnessRuntimeOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: propertyRunKeys,
    atoms: ["propertyRunAtom", "telemetryEventAtom"],
  } as const),
  laws: commandLaws,
  metadata: {
    service: "joern-effect-properties/PropertyHarnessRuntime",
    boundary: "makePropertyHarnessRuntimeLayer",
    eventRuntime: "local-or-axiom",
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const semanticCorpusStoreOperation = defineOperation({
  id: "semantic-corpus-store",
  name: "Semantic corpus store boundary",
  kind: "query",
  input: SemanticCorpusStoreInput,
  output: SemanticCorpusStoreOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: corpusKeys,
    atoms: ["corpusAtom"],
  } as const),
  laws: queryLaws,
  metadata: {
    service: "joern-effect-properties/SemanticCorpusStore",
    boundary: "curated-plus-promoted-seeds",
    cache: "private framework/runtime or in-memory fixture",
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const counterexampleStoreOperation = defineOperation({
  id: "counterexample-store",
  name: "Counterexample store and promotion boundary",
  kind: "command",
  input: CounterexampleStoreInput,
  output: CounterexampleStoreOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: counterexampleKeys,
    atoms: ["counterexampleAtom", "corpusAtom"],
  } as const),
  laws: commandLaws,
  metadata: {
    service: "joern-effect-properties/CounterexampleStore",
    boundary: "record-list-promote-counterexamples",
    storage: "in-memory fixture now; private protocol cache later",
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const semanticMutatorOperation = defineOperation({
  id: "semantic-mutator",
  name: "Semantic project mutator",
  kind: "generator",
  input: SemanticMutatorInput,
  output: SemanticMutatorOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "joern-effect-properties.fuzz-run.changed",
      "joern-effect-properties.corpus.changed",
    ],
    atoms: ["fuzzRunAtom", "corpusAtom"],
  } as const),
  laws: generatorLaws,
  generator: {
    name: "joern-effect-properties:semantic-mutator",
    project: "joern-effect-properties",
    output: "in-memory-fuzz-case",
    generatedFiles: [] as const,
    intendedExecutor: "attune:generated",
    typedOptionsSchema: "ProofTypedTargetIntent",
  } as const,
} as const)

export const semanticFuzzSchedulerOperation = defineOperation({
  id: "semantic-fuzz-scheduler",
  name: "Semantic fuzz scheduler and shard runner",
  kind: "command",
  input: SemanticFuzzSchedulerInput,
  output: SemanticFuzzSchedulerOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: fuzzRunKeys,
    atoms: [
      "fuzzRunAtom",
      "workerShardAtom",
      "workspacePoolAtom",
      "telemetryEventAtom",
    ],
  } as const),
  laws: commandLaws,
  metadata: {
    service: "joern-effect-properties/SemanticFuzzScheduler",
    boundary: "runFuzzer",
    schedules: ["corpus", "mutator", "workspace-pool", "oracle", "telemetry"],
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const joernWorkspacePoolOperation = defineOperation({
  id: "joern-workspace-pool",
  name: "Joern workspace pool worker boundary",
  kind: "resource-provider",
  observes: true,
  input: JoernWorkspacePoolInput,
  output: JoernWorkspacePoolOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "joern-effect-properties.workspace-pool.changed",
      "joern-effect-properties.worker-shard.changed",
    ],
    atoms: ["workspacePoolAtom", "workerShardAtom"],
  } as const),
  laws: resourceProviderLaws,
  resource: {
    observes: true,
    provider: "joern-effect/Joern",
    desiredStateSchema: "JoernWorkspaceWorker",
    observationSchema: "ImportedProjectWorkspace",
    liveApply: false,
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const fuzzOracleOperation = defineOperation({
  id: "fuzz-oracle",
  name: "Fuzz oracle and Joern query recipe boundary",
  kind: "joern-template",
  input: FuzzOracleInput,
  output: FuzzOracleOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "joern-effect-properties.weak-oracle.changed",
      "joern-effect-properties.coverage-feedback.changed",
    ],
    atoms: ["weakOracleFindingAtom", "coverageFeedbackAtom"],
  } as const),
  laws: joernTemplateLaws,
  joern: {
    registry: "compileGeneratedDslPrograms",
    templateKinds: ["query-recipe", "oracle-comparison"],
    evidence: ["FuzzQueryRecipeResult", "FuzzExpectationMismatchError"],
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const fuzzTelemetryOperation = defineOperation({
  id: "fuzz-telemetry",
  name: "Fuzz telemetry event facade",
  kind: "event-facade",
  input: FuzzTelemetryInput,
  output: FuzzTelemetryOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: ["joern-effect-properties.telemetry.changed"],
    atoms: ["telemetryEventAtom"],
  } as const),
  laws: eventFacadeLaws,
  event: {
    eventTypes: [
      "attune.fuzz.case_generated",
      "attune.fuzz.counterexample_found",
      "attune.fuzz.shrink_completed",
      "attune.fuzz.fixture_candidate",
    ],
    appendBoundary: "emitFuzzEvent",
    sink: "local-events-or-axiom",
  } as const,
} as const)

export const coverageSearchFeedbackOperation = defineOperation({
  id: "coverage-search-feedback",
  name: "Coverage search and weak-oracle feedback",
  kind: "projection",
  input: CoverageSearchFeedbackInput,
  output: CoverageSearchFeedbackOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: coverageKeys,
    atoms: ["coverageFeedbackAtom", "weakOracleFindingAtom"],
  } as const),
  laws: projectionLaws,
  projection: {
    inputEvent: "CoverageSearchMergeInput",
    state: "CoverageSearchSummary",
    replay: "mergeCoverageSearchEvidence",
    evidenceShape: "ProofAtomGraphCoverageSummary",
  } as const,
} as const)

export const workerPropertyWrapperOperation = defineOperation({
  id: "worker-property-wrapper",
  name: "Worker property wrapper boundary",
  kind: "command",
  input: WorkerPropertyWrapperInput,
  output: WorkerPropertyWrapperOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: workerKeys,
    atoms: ["workerShardAtom", "propertyRunAtom", "counterexampleAtom"],
  } as const),
  laws: commandLaws,
  metadata: {
    service: "joern-effect-properties/WorkerProperty",
    boundary: "defineWorkerPropertyDescriptor",
    workerBackend: "@fast-check/worker",
    rpcBackend: "future optional; no runtime @effect/rpc import",
    evidenceShape: "ProofPropertyEvidenceSummary",
  } as const,
} as const)

export const propertyProofViewAtomsOperation = defineOperation({
  id: "property-proof-view-atoms",
  name: "Property proof runtime package view atoms",
  kind: "atom-family",
  input: PackageViewAtomInput,
  output: PackageViewAtomOutput,
  error: PropertyProofContractError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "joern-effect-properties.property-run.changed",
      "joern-effect-properties.fuzz-run.changed",
      "joern-effect-properties.corpus.changed",
      "joern-effect-properties.counterexample.changed",
      "joern-effect-properties.worker-shard.changed",
      "joern-effect-properties.workspace-pool.changed",
      "joern-effect-properties.coverage-feedback.changed",
      "joern-effect-properties.weak-oracle.changed",
      "joern-effect-properties.telemetry.changed",
    ],
    atoms: [
      "propertyRunAtom",
      "fuzzRunAtom",
      "corpusAtom",
      "counterexampleAtom",
      "workerShardAtom",
      "workspacePoolAtom",
      "coverageFeedbackAtom",
      "weakOracleFindingAtom",
      "telemetryEventAtom",
    ],
  } as const),
  laws: atomFamilyLaws,
  atom: {
    family: "property-proof-runtime",
    baseAtoms: [
      "propertyRunAtom",
      "fuzzRunAtom",
      "corpusAtom",
      "counterexampleAtom",
      "workerShardAtom",
      "workspacePoolAtom",
      "coverageFeedbackAtom",
      "telemetryEventAtom",
    ],
    derivedAtoms: ["weakOracleFindingAtom"],
    composes: true,
  } as const,
} as const)

export const PackageOperations = [
  propertyHarnessRuntimeOperation,
  semanticCorpusStoreOperation,
  counterexampleStoreOperation,
  semanticMutatorOperation,
  semanticFuzzSchedulerOperation,
  joernWorkspacePoolOperation,
  fuzzOracleOperation,
  fuzzTelemetryOperation,
  coverageSearchFeedbackOperation,
  workerPropertyWrapperOperation,
  propertyProofViewAtomsOperation,
] as const

export type JoernEffectPropertiesOperationId =
  (typeof PackageOperations)[number]["id"]

const evidenceFor = (
  operation: (typeof PackageOperations)[number],
  tier: ProofEvidenceTier,
  coveragePointIds: readonly string[],
) => ({
  packageId: "joern-effect-properties",
  operationId: operation.id,
  tier,
  status: "passed",
  runId: "joern-effect-properties-fixture-run",
  seed: 1_337,
  shardId: "shard-0-of-1",
  lawIds: operation.laws ?? [],
  reactivityKeys: operation.views?.reactivityKeys ?? [],
  atomIds: operation.views?.atoms ?? [],
  coveragePointIds,
} as const satisfies ProofPropertyEvidenceSummary)

export const PackageEvidenceShapes = {
  "property-harness-runtime": evidenceFor(
    propertyHarnessRuntimeOperation,
    "commit",
    ["src/attuneProperty.ts:checkAttuneProperty"],
  ),
  "semantic-corpus-store": evidenceFor(
    semanticCorpusStoreOperation,
    "commit",
    ["src/fuzz/services/corpus.ts:listSeeds"],
  ),
  "counterexample-store": {
    ...evidenceFor(
      counterexampleStoreOperation,
      "commit",
      ["src/fuzz/services/counterexamples.ts:record"],
    ),
    counterexampleSeedId: "promoted-counterexample-fixture",
  },
  "semantic-mutator": evidenceFor(
    semanticMutatorOperation,
    "push",
    ["src/fuzz/services/mutator.ts:mutate"],
  ),
  "semantic-fuzz-scheduler": evidenceFor(
    semanticFuzzSchedulerOperation,
    "proof-pressure",
    ["src/fuzz/pipeline/runner.ts:runFuzzPipeline"],
  ),
  "joern-workspace-pool": {
    ...evidenceFor(
      joernWorkspacePoolOperation,
      "proof-pressure",
      ["src/fuzz/services/workspacePool.ts:withWorkspace"],
    ),
    workerId: "joern-fuzz-worker-fixture",
  },
  "fuzz-oracle": {
    ...evidenceFor(
      fuzzOracleOperation,
      "proof-pressure",
      ["src/fuzz/services/oracle.ts:queryOracle"],
    ),
    workerId: "joern-fuzz-worker-fixture",
  },
  "fuzz-telemetry": evidenceFor(
    fuzzTelemetryOperation,
    "commit",
    ["src/events.ts:writePropertyEvent"],
  ),
  "coverage-search-feedback": evidenceFor(
    coverageSearchFeedbackOperation,
    "commit",
    ["src/coverageSearch.ts:mergeCoverageSearchEvidence"],
  ),
  "worker-property-wrapper": {
    ...evidenceFor(
      workerPropertyWrapperOperation,
      "push",
      ["src/workerProperty.ts:defineWorkerPropertyDescriptor"],
    ),
    workerId: "worker-0",
  },
  "property-proof-view-atoms": evidenceFor(
    propertyProofViewAtomsOperation,
    "commit",
    ["src/coverageSearch.ts:mergeAtomGraphMovements"],
  ),
} as const satisfies {
  readonly [Id in JoernEffectPropertiesOperationId]: ProofPropertyEvidenceSummary
}
export type PackageEvidenceShapes = typeof PackageEvidenceShapes

export const PackageAtomGraphCoverage = {
  "property-harness-runtime": {
    operationId: "property-harness-runtime",
    requiredEdges: ["property-harness-runtime->propertyRunAtom"],
    movedEdges: ["property-harness-runtime->propertyRunAtom"],
    missingEdges: [],
    reactivityKeysHit: propertyRunKeys,
    atomsRefreshed: ["propertyRunAtom"],
    viewAtomsChanged: ["propertyRunAtom", "telemetryEventAtom"],
  },
  "semantic-fuzz-scheduler": {
    operationId: "semantic-fuzz-scheduler",
    requiredEdges: ["semantic-fuzz-scheduler->fuzzRunAtom"],
    movedEdges: ["semantic-fuzz-scheduler->fuzzRunAtom"],
    missingEdges: [],
    reactivityKeysHit: fuzzRunKeys,
    atomsRefreshed: ["fuzzRunAtom", "workerShardAtom", "workspacePoolAtom"],
    viewAtomsChanged: ["fuzzRunAtom", "workerShardAtom", "workspacePoolAtom"],
  },
  "coverage-search-feedback": {
    operationId: "coverage-search-feedback",
    requiredEdges: ["coverage-search-feedback->coverageFeedbackAtom"],
    movedEdges: ["coverage-search-feedback->coverageFeedbackAtom"],
    missingEdges: [],
    reactivityKeysHit: coverageKeys,
    atomsRefreshed: ["coverageFeedbackAtom", "weakOracleFindingAtom"],
    viewAtomsChanged: ["coverageFeedbackAtom", "weakOracleFindingAtom"],
  },
  "worker-property-wrapper": {
    operationId: "worker-property-wrapper",
    requiredEdges: ["worker-property-wrapper->workerShardAtom"],
    movedEdges: ["worker-property-wrapper->workerShardAtom"],
    missingEdges: [],
    reactivityKeysHit: workerKeys,
    atomsRefreshed: ["workerShardAtom", "propertyRunAtom", "counterexampleAtom"],
    viewAtomsChanged: ["workerShardAtom", "propertyRunAtom", "counterexampleAtom"],
  },
} as const satisfies Readonly<Record<string, ProofAtomGraphCoverageSummary>>
export type PackageAtomGraphCoverage = typeof PackageAtomGraphCoverage

export const PackageTargetIntents = [
  {
    targetName: "property",
    intendedExecutor: "attune:package-check",
    resourceTier: "commit",
    commandSurfaceWaiverId: "joern-effect-properties/typed-executor-migration",
    operationIds: ["property-harness-runtime", "worker-property-wrapper"],
    typedOptions: {
      runner: "vitest",
      evidenceOutput: ".attune/cache/joern-effect-properties/property-evidence.jsonl",
      localEvents: true,
      workerCount: 1,
    },
  },
  {
    targetName: "fuzz:smoke",
    intendedExecutor: "attune:toolchain",
    resourceTier: "commit",
    commandSurfaceWaiverId: "joern-effect-properties/typed-executor-migration",
    operationIds: ["semantic-fuzz-scheduler", "semantic-mutator", "fuzz-telemetry"],
    typedOptions: {
      preset: "smoke",
      joernMode: "none",
      queryFeedback: false,
      evidenceOutput: ".attune/cache/joern-effect-properties/fuzz-smoke.jsonl",
    },
  },
  {
    targetName: "fuzz:workbench",
    intendedExecutor: "attune:toolchain",
    resourceTier: "push",
    commandSurfaceWaiverId: "joern-effect-properties/typed-executor-migration",
    operationIds: [
      "semantic-fuzz-scheduler",
      "joern-workspace-pool",
      "fuzz-oracle",
      "coverage-search-feedback",
    ],
    typedOptions: {
      preset: "workbench",
      joernMode: "query",
      queryFeedback: true,
      workerCount: 2,
    },
  },
  {
    targetName: "fuzz:campaign",
    intendedExecutor: "attune:toolchain",
    resourceTier: "proof-pressure",
    commandSurfaceWaiverId: "joern-effect-properties/typed-executor-migration",
    operationIds: [
      "semantic-fuzz-scheduler",
      "joern-workspace-pool",
      "fuzz-oracle",
      "coverage-search-feedback",
      "worker-property-wrapper",
    ],
    typedOptions: {
      preset: "campaign",
      joernMode: "query",
      queryFeedback: true,
      workerCount: 2,
      timeoutMs: 14_400_000,
      arion: true,
      nixImage: "joern-effect-property-image",
    },
  },
] as const satisfies readonly ProofTypedTargetIntent[]
export type PackageTargetIntents = typeof PackageTargetIntents

export const PackageContract = definePackageContract({
  packageId: "joern-effect-properties",
  sourceRoot: "packages/joern-effect-properties/src",
  packageKind: "property-proof-runtime",
  views: PackageViews,
  services: PropertyProofServices,
  providedServices: PropertyProofServices,
  requiredServices: PropertyProofRequiredServices,
  operations: PackageOperations,
  provenance: {
    generator: "@attune/nx:package-contract",
    customizedFor: "Joern property proof runtime and workerized fuzz harness",
    openspecChangeId: "standardize-effect-package-contracts",
    evidenceShapes: "PackageEvidenceShapes",
    atomGraphCoverage: "PackageAtomGraphCoverage",
    targetIntents: "PackageTargetIntents",
  } as const,
  waivers: [
    {
      id: "joern-effect-properties/context-tag-services",
      category: "legacy-boundary",
      owner: "joern-effect-properties-migration-agent",
      reason:
        "Property proof services still use lower-level Context.Tag service definitions until canonical Effect.Service scaffolds land for the proof package.",
      review: "standardize-effect-package-contracts task 11.4",
    },
    {
      id: "joern-effect-properties/live-joern-oracle-boundary",
      category: "hidden-configuration",
      owner: "joern-effect-properties-migration-agent",
      reason:
        "Live oracle and workspace pool runs depend on Joern toolchain, temp workspaces, and optional event sinks; PackageTestLayer uses dry fixture behavior.",
      review: "standardize-effect-package-contracts task 11.3",
    },
    {
      id: "joern-effect-properties/typed-executor-migration",
      category: "temporary-migration-adapter",
      owner: "joern-effect-properties-migration-agent",
      reason:
        "Existing property, fuzz, Nix, Arion, and wrapper command strings remain until proof targets move behind typed Nx executors.",
      review: "standardize-effect-package-contracts task 11.4",
    },
  ] as const,
} as const)
export type PackageContract = typeof PackageContract

export const PackageLayer = {
  layer: Layer.empty,
  provides: PropertyProofServices,
  requires: PropertyProofRequiredServices,
  metadata: {
    packageId: "joern-effect-properties",
    role: "property-proof-runtime-boundary",
  },
} as const
export type PackageLayer = typeof PackageLayer

export const PackageTestLayer = {
  layer: Layer.empty,
  provides: [
    ...PropertyProofServices,
    ...PropertyProofRequiredServices,
  ] as const,
  requires: [] as const,
  metadata: {
    packageId: "joern-effect-properties",
    role: "dry-fixture-property-proof-boundary",
    eventRuntime: "local",
    liveJoern: false,
    workerResourceTier: "commit",
  },
} as const
export type PackageTestLayer = typeof PackageTestLayer

const PackageGenerated = createAttuneGenerated({
  PackageContract,
  atomFamilyLaws,
  commandLaws,
  counterexampleStoreOperation,
  coverageSearchFeedbackOperation,
  eventFacadeLaws,
  fuzzOracleOperation,
  fuzzTelemetryOperation,
  generatorLaws,
  joernTemplateLaws,
  joernWorkspacePoolOperation,
  projectionLaws,
  propertyHarnessRuntimeOperation,
  propertyProofViewAtomsOperation,
  queryLaws,
  resourceProviderLaws,
  semanticCorpusStoreOperation,
  semanticFuzzSchedulerOperation,
  semanticMutatorOperation,
  workerPropertyWrapperOperation,
} as const)
export const PackageFuzzHandlers = PackageGenerated.PackageFuzzHandlers
export const PackageProperties = PackageGenerated.PackageProperties
export const PackageTypeGuidance = PackageGenerated.PackageTypeGuidance
export type PackageFuzzHandlers = typeof PackageFuzzHandlers
export type PackageProperties = typeof PackageProperties
export type PackageTypeGuidance = typeof PackageTypeGuidance
