/* @generated by @attune/nx:attune-repair. Do not edit directly. */
// @ts-nocheck
import {
  definePackageFuzzRpcGroup,
  defineTypeGuidance,
  type AttunePackageContract,
} from "@attune/framework-protocol"

export const createAttuneGenerated = <
  const Contract extends AttunePackageContract,
  const AtomFamilyLaws extends readonly string[],
  const CommandLaws extends readonly string[],
  const EventFacadeLaws extends readonly string[],
  const GeneratorLaws extends readonly string[],
  const JoernTemplateLaws extends readonly string[],
  const ProjectionLaws extends readonly string[],
  const QueryLaws extends readonly string[],
  const ResourceProviderLaws extends readonly string[],
  const Source extends { readonly PackageContract: Contract; readonly atomFamilyLaws: AtomFamilyLaws; readonly commandLaws: CommandLaws; readonly eventFacadeLaws: EventFacadeLaws; readonly generatorLaws: GeneratorLaws; readonly joernTemplateLaws: JoernTemplateLaws; readonly projectionLaws: ProjectionLaws; readonly queryLaws: QueryLaws; readonly resourceProviderLaws: ResourceProviderLaws } & Readonly<Record<string, unknown>>,
>(source: Source) => {
  const PackageContract = source.PackageContract
  const {
    atomFamilyLaws,
    commandLaws,
    counterexampleStoreOperation,
    coverageSearchFeedbackOperation,
    eventFacadeLaws,
    fuzzOracleOperation,
    fuzzTelemetryOperation,
    generatorLaws,
    joernTemplateLaws,
    joernWorkspacePoolOperation,
    projectionLaws,
    propertyHarnessRuntimeOperation,
    propertyProofViewAtomsOperation,
    queryLaws,
    resourceProviderLaws,
    semanticCorpusStoreOperation,
    semanticFuzzSchedulerOperation,
    semanticMutatorOperation,
    workerPropertyWrapperOperation,
  } = source

  const PackageFuzzHandlers = {
    "property-harness-runtime": () => ({
      deterministic: true,
      eventRuntime: "local" as const,
      localEvents: true,
      runId: "joern-effect-properties-fixture-run",
      workerCount: 1,
    }),
    "semantic-corpus-store": () => ({
      corpusAtomId: "corpusAtom",
      origins: ["curated", "parser-fixture"],
      promotedSeedCount: 0,
      seedCount: 8,
    }),
    "counterexample-store": () => ({
      candidateCount: 1,
      counterexampleAtomId: "counterexampleAtom",
      latestSeedId: "promoted-counterexample-fixture",
      promotedSeedCount: 1,
    }),
    "semantic-mutator": () => ({
      appliedMutations: ["function-wrap", "source-sink-flow"],
      caseId: "semantic-fixture-case",
      rejectedMutations: [],
      sourceFiles: 1,
    }),
    "semantic-fuzz-scheduler": () => ({
      accepted: 2,
      batches: 1,
      cases: 2,
      mode: "smoke" as const,
      rejected: 0,
      runId: "joern-effect-properties-fixture-run",
      target: "joern-effect-properties:fuzz:smoke",
      workerShards: 1,
    }),
    "joern-workspace-pool": () => ({
      cleanedUp: true,
      imported: false,
      projectName: "fixture-project",
      workerId: "joern-fuzz-worker-fixture",
      workspacePath: "/tmp/attune/joern-effect-properties/fixture",
    }),
    "fuzz-oracle": () => ({
      expectationFailures: 0,
      oracleAtomId: "weakOracleFindingAtom",
      projectName: "fixture-project",
      queryResultCount: 0,
      workerId: "joern-fuzz-worker-fixture",
    }),
    "fuzz-telemetry": () => ({
      emitted: true,
      eventType: "attune.fuzz.case_generated",
      flushed: true,
      telemetryAtomId: "telemetryEventAtom",
    }),
    "coverage-search-feedback": () => ({
      atomGraphMovements: 1,
      coverageDeltas: 1,
      coverageFeedbackAtomId: "coverageFeedbackAtom",
      findings: 0,
      retainedSeeds: 1,
      weakOracleFindings: 0,
    }),
    "worker-property-wrapper": () => ({
      descriptorKind: "attune.worker-property" as const,
      preservesShrinking: true,
      propertyId: "joern-effect-properties.fixture-property",
      randomSource: "main-thread" as const,
      shardId: "shard-0-of-1",
      status: "passed" as const,
      workerCount: 1,
    }),
    "property-proof-view-atoms": () => ({
      atomId: "propertyRunAtom",
      dependsOnAtoms: ["workerShardAtom", "coverageFeedbackAtom"],
      observed: true,
      reactivityKeys: [
        "joern-effect-properties.property-run.changed",
        "joern-effect-properties.worker-shard.changed",
      ],
      summary: "Fixture property proof runtime atom movement.",
      valueKind: "property-run" as const,
    }),
  } as const satisfies {
    readonly [Id in JoernEffectPropertiesOperationId]: () => unknown
  }
  type PackageFuzzHandlers = typeof PackageFuzzHandlers

  const PackageProperties = {
    "property-harness-runtime": {
      property:
        "Property harness runtime selects deterministic fixture event sinks and bounded worker counts for generated audits.",
    },
    "semantic-corpus-store": {
      property:
        "Curated and promoted semantic corpus seeds decode through Schema-backed corpus boundaries without checked-in report state.",
    },
    "counterexample-store": {
      property:
        "Counterexamples record, list, and promote into corpus seeds with replay metadata retained in private cache boundaries.",
    },
    "semantic-mutator": {
      property:
        "Semantic mutators produce deterministic project cases from declared corpus seeds and mutation plans.",
    },
    "semantic-fuzz-scheduler": {
      property:
        "Fuzz scheduler runs bounded fixture campaigns through corpus, mutator, workspace, oracle, and telemetry services.",
    },
    "joern-workspace-pool": {
      property:
        "Workspace pool workers create and clean temporary Joern workspaces without exposing durable cache paths as source truth.",
    },
    "fuzz-oracle": {
      property:
        "Oracle query recipes normalize Joern evidence and weak-oracle findings through declared template boundaries.",
    },
    "fuzz-telemetry": {
      property:
        "Fuzz telemetry emits schema-backed events through local or Axiom event sinks and flushes deterministically in fixtures.",
    },
    "coverage-search-feedback": {
      property:
        "Coverage search merges type partitions, atom graph movement, V8 deltas, filters, and weak-oracle findings deterministically.",
    },
    "worker-property-wrapper": {
      property:
        "Worker property descriptors declare worker budget, random source, timeout, shard, and cleanup metadata.",
    },
    "property-proof-view-atoms": {
      property:
        "Property proof package atoms compose run, corpus, counterexample, worker, coverage, weak-oracle, and telemetry views.",
    },
  } as const satisfies {
    readonly [Id in JoernEffectPropertiesOperationId]: { readonly property: string }
  }
  type PackageProperties = typeof PackageProperties

  type OperationWithGuidance = {
    readonly id: string
    readonly kind: string
    readonly input: unknown
    readonly output: unknown
    readonly error?: unknown
    readonly views?: {
      readonly reactivityKeys?: readonly string[]
      readonly atoms?: readonly string[]
    }
    readonly laws?: readonly string[]
  }

  const lawPartitions = <const Laws extends readonly string[]>(laws: Laws) =>
    laws.map((id) => ({
      id,
      kind: "law" as const,
      from: "inferred-law",
    })) as {
      readonly [Index in keyof Laws]: {
        readonly id: Laws[Index]
        readonly kind: "law"
        readonly from: "inferred-law"
      }
    }

  const schemaSources = (operation: OperationWithGuidance) => [
    {
      id: `schema:${operation.id}:input`,
      role: "input" as const,
      label: `${operation.id}.input`,
      source: "effect-schema",
    },
    {
      id: `schema:${operation.id}:output`,
      role: "output" as const,
      label: `${operation.id}.output`,
      source: "effect-schema",
    },
    {
      id: `schema:${operation.id}:error`,
      role: "error" as const,
      label: `${operation.id}.error`,
      source: "effect-schema",
    },
  ] as const

  const viewPartitions = (operation: OperationWithGuidance) => [
    ...(operation.views?.reactivityKeys ?? []).map((id) => ({
      id: `${id}.moves`,
      kind: "reactivity-key" as const,
      from: "operation.views.reactivityKeys",
    })),
    ...(operation.views?.atoms ?? []).map((id) => ({
      id: `${id}.moves`,
      kind: "atom" as const,
      from: "operation.views.atoms",
    })),
  ]

  const operationGuidance = <
    const Operation extends OperationWithGuidance,
    const Laws extends readonly string[],
  >(
    operation: Operation,
    laws: Laws,
    options: {
      readonly inputPartitionId: string
      readonly outputPartitionId: string
      readonly coverageTargetId: string
      readonly transformId: string
      readonly filterId?: string
    },
  ) => ({
    sourceLabels: [
      `operation.kind.${operation.kind}`,
      "effect-schema.ast",
      "property-proof-runtime",
      "package-view-graph",
    ],
    sources: [
      {
        id: `operation:${operation.id}`,
        label: operation.id,
        kind: "contract-operation" as const,
        operationId: operation.id,
      },
    ],
    schemaSources: schemaSources(operation),
    partitions: [
      {
        id: `${operation.id}.operation-id`,
        kind: "operation-id" as const,
        from: "contract.operation.id",
        sourceId: `operation:${operation.id}`,
      },
      {
        id: `${operation.id}.operation-kind.${operation.kind}`,
        kind: "operation-kind" as const,
        from: "contract.operation.kind",
        sourceId: `operation:${operation.id}`,
      },
    ],
    inputPartitions: [
      {
        id: options.inputPartitionId,
        kind: "schema-boundary" as const,
        from: "schema.input",
        sourceId: `schema:${operation.id}:input`,
        transformIds: [options.transformId],
        ...(options.filterId ? { filterIds: [options.filterId] } : {}),
      },
    ],
    outputPartitions: [
      {
        id: options.outputPartitionId,
        kind: "output-variant" as const,
        from: "schema.output",
        sourceId: `schema:${operation.id}:output`,
      },
    ],
    errorPartitions: [
      {
        id: `${operation.id}.typed-error`,
        kind: "typed-error-variant" as const,
        from: "schema.error",
        sourceId: `schema:${operation.id}:error`,
      },
    ],
    lawPartitions: lawPartitions(laws),
    viewPartitions: viewPartitions(operation),
    coverageSearch: [
      {
        id: `coverage:${operation.id}:${options.coverageTargetId}`,
        targetPartitionId: options.coverageTargetId,
        tier: "commit" as const,
        required: true,
      },
    ],
    transforms: [
      {
        id: options.transformId,
        kind: "coverage-bias" as const,
        targetPartitionId: options.coverageTargetId,
        reason:
          "Bias generated proof-runtime cases toward missing property evidence and package view movement.",
      },
    ],
    filters: options.filterId
      ? [
        {
          id: options.filterId,
          kind: "operation-precondition" as const,
          reason:
            "Keep generated proof-runtime audits on deterministic fixture or dry Joern boundaries.",
          targetPartitionId: options.inputPartitionId,
          expectedAcceptanceRate: 0.9,
        },
      ]
      : [],
  } as const)

  const PackageTypeGuidance = defineTypeGuidance(PackageContract, {
    sourceLabels: [
      "contract.operation",
      "effect-schema.ast",
      "operation.kind.property-proof-runtime",
      "fast-check-worker",
      "coverage-feedback",
      "declared-view",
    ],
    sources: [
      {
        id: "contract:joern-effect-properties",
        label: "joern-effect-properties package contract",
        kind: "contract-operation",
      },
      {
        id: "views:joern-effect-properties",
        label: "joern-effect-properties Reactivity and atom graph",
        kind: "declared-view",
      },
    ],
    operations: {
      "property-harness-runtime": operationGuidance(
        propertyHarnessRuntimeOperation,
        commandLaws,
        {
          inputPartitionId: "property-harness-runtime.event-runtime",
          outputPartitionId: "property-harness-runtime.fixture-layer",
          coverageTargetId: "propertyRunAtom.moves",
          transformId: "property-harness-runtime.local-event-runtime",
          filterId: "property-harness-runtime.fixture-events",
        },
      ),
      "semantic-corpus-store": operationGuidance(
        semanticCorpusStoreOperation,
        queryLaws,
        {
          inputPartitionId: "semantic-corpus-store.origin",
          outputPartitionId: "semantic-corpus-store.seed-count",
          coverageTargetId: "corpusAtom.moves",
          transformId: "semantic-corpus-store.origin-coverage",
        },
      ),
      "counterexample-store": operationGuidance(
        counterexampleStoreOperation,
        commandLaws,
        {
          inputPartitionId: "counterexample-store.action",
          outputPartitionId: "counterexample-store.promoted-seed",
          coverageTargetId: "counterexampleAtom.moves",
          transformId: "counterexample-store.replay-candidate",
        },
      ),
      "semantic-mutator": operationGuidance(
        semanticMutatorOperation,
        generatorLaws,
        {
          inputPartitionId: "semantic-mutator.mutation-kind",
          outputPartitionId: "semantic-mutator.semantic-case",
          coverageTargetId: "fuzzRunAtom.moves",
          transformId: "semantic-mutator.mutation-kind-coverage",
        },
      ),
      "semantic-fuzz-scheduler": operationGuidance(
        semanticFuzzSchedulerOperation,
        commandLaws,
        {
          inputPartitionId: "semantic-fuzz-scheduler.preset",
          outputPartitionId: "semantic-fuzz-scheduler.summary",
          coverageTargetId: "fuzzRunAtom.moves",
          transformId: "semantic-fuzz-scheduler.preset-coverage",
          filterId: "semantic-fuzz-scheduler.fixture-preset",
        },
      ),
      "joern-workspace-pool": operationGuidance(
        joernWorkspacePoolOperation,
        resourceProviderLaws,
        {
          inputPartitionId: "joern-workspace-pool.workspace-root",
          outputPartitionId: "joern-workspace-pool.worker",
          coverageTargetId: "workspacePoolAtom.moves",
          transformId: "joern-workspace-pool.worker-coverage",
          filterId: "joern-workspace-pool.fixture-workspace",
        },
      ),
      "fuzz-oracle": operationGuidance(
        fuzzOracleOperation,
        joernTemplateLaws,
        {
          inputPartitionId: "fuzz-oracle.mode",
          outputPartitionId: "fuzz-oracle.query-results",
          coverageTargetId: "weakOracleFindingAtom.moves",
          transformId: "fuzz-oracle.query-recipe-coverage",
          filterId: "fuzz-oracle.fixture-joern",
        },
      ),
      "fuzz-telemetry": operationGuidance(
        fuzzTelemetryOperation,
        eventFacadeLaws,
        {
          inputPartitionId: "fuzz-telemetry.event-type",
          outputPartitionId: "fuzz-telemetry.flush",
          coverageTargetId: "telemetryEventAtom.moves",
          transformId: "fuzz-telemetry.event-type-coverage",
        },
      ),
      "coverage-search-feedback": operationGuidance(
        coverageSearchFeedbackOperation,
        projectionLaws,
        {
          inputPartitionId: "coverage-search-feedback.finding-kind",
          outputPartitionId: "coverage-search-feedback.retained-seeds",
          coverageTargetId: "coverageFeedbackAtom.moves",
          transformId: "coverage-search-feedback.weak-oracle-bias",
        },
      ),
      "worker-property-wrapper": operationGuidance(
        workerPropertyWrapperOperation,
        commandLaws,
        {
          inputPartitionId: "worker-property-wrapper.resource-tier",
          outputPartitionId: "worker-property-wrapper.worker-evidence",
          coverageTargetId: "workerShardAtom.moves",
          transformId: "worker-property-wrapper.commit-tier-budget",
          filterId: "worker-property-wrapper.serializable-values",
        },
      ),
      "property-proof-view-atoms": operationGuidance(
        propertyProofViewAtomsOperation,
        atomFamilyLaws,
        {
          inputPartitionId: "property-proof-view-atoms.atom-id",
          outputPartitionId: "property-proof-view-atoms.summary",
          coverageTargetId: "weakOracleFindingAtom.moves",
          transformId: "property-proof-view-atoms.graph-coverage",
        },
      ),
    },
  } as const)
  type PackageTypeGuidance = typeof PackageTypeGuidance

  return {
    PackageFuzzHandlers,
    PackageProperties,
    PackageTypeGuidance,
  } as const
}
