import { upsertExport } from "../../internal/barrel.js"
import { joinPath, relativeModulePath } from "../../internal/paths.js"
import {
  type GeneratorTask,
  type GeneratorTree,
  writeTextIfChanged,
} from "../../internal/tree.js"
import {
  inferProjectRootFromDirectory,
  upsertSourceBom,
} from "../../internal/source-bom.js"
import { toNames } from "../../internal/names.js"

export interface EffectServiceGeneratorSchema {
  readonly name: string
  readonly directory?: string
  readonly export?: boolean
  readonly tag?: string
  readonly operationId?: string
  readonly operationKind?: EffectServiceOperationKind
  readonly project?: string
  readonly generatorVersion?: string
  readonly generatorRevision?: string
  readonly openspecChangeId?: string
}

export type EffectServiceOperationKind =
  | "codec"
  | "query"
  | "command"
  | "projection"
  | "event-facade"
  | "atom-family"
  | "resource-provider"
  | "generator"
  | "policy-rule"
  | "joern-template"

const operationBuilderNames: Record<EffectServiceOperationKind, string> = {
  "atom-family": "atomFamilyOperation",
  codec: "codecOperation",
  command: "commandOperation",
  "event-facade": "eventFacadeOperation",
  generator: "generatorOperation",
  "joern-template": "joernTemplateOperation",
  "policy-rule": "policyRuleOperation",
  projection: "projectionOperation",
  query: "queryOperation",
  "resource-provider": "resourceProviderOperation",
}

interface EffectServiceTemplateSchema
  extends Required<
    Pick<
      EffectServiceGeneratorSchema,
      "operationId" | "operationKind" | "tag"
    >
  > {
  readonly operationBuilderName: string
}

const serviceTemplate = (
  schema: EffectServiceTemplateSchema,
  names: ReturnType<typeof toNames>,
): string => `import { Effect, Schema } from "effect"

/**
 * Generated by @attune/nx:effect-service.
 * Ownership: world-changing effects live in Effect services, not atoms.
 * Add fake/test layers here for closed-loop validation; keep durable writes behind
 * service boundaries instead of UI or derived-view code.
 * Project facts lift the symbol registration below into src/attune.package.ts.
 */
export interface ${names.className}Service {
  readonly run: () => Effect.Effect<void>
}

export const make${names.className} = (): ${names.className}Service => ({
  run: () => Effect.void,
})

export class ${names.className} extends Effect.Service<${names.className}>()(
  "${schema.tag}",
  {
    accessors: true,
    effect: Effect.succeed(make${names.className}()),
  },
) {}

export const ${names.className}RunInput = Schema.Void
export const ${names.className}RunOutput = Schema.Void

export const ${names.className}RunOperation = {
  id: "${schema.operationId}",
  kind: "${schema.operationKind}",
  input: ${names.className}RunInput,
  output: ${names.className}RunOutput,
  inferredDiagnosticRules: "inferDiagnosticRules()",
  diagnosticRuleExtensions: [],
  registration:
    "${schema.operationBuilderName}({ id, input, output, diagnosticRules: inferDiagnosticRules(), edges: touches(...) })",
} as const

export const ${names.className}Live = ${names.className}.Default
export const PackageLayer = ${names.className}Live
export const PackageTestLayer = ${names.className}Live
`

export default function effectServiceGenerator(
  tree: GeneratorTree,
  schema: EffectServiceGeneratorSchema,
): GeneratorTask {
  const names = toNames(schema.name)
  const directory = schema.directory ?? "src/effect/services"
  const filePath = joinPath(directory, `${names.fileName}.ts`)
  const tag = schema.tag ?? `@attune/service/${names.className}`
  const operationId = schema.operationId ?? `${names.fileName}.run`
  const operationKind = schema.operationKind ?? "command"

  writeTextIfChanged(
    tree,
    filePath,
    serviceTemplate(
      {
        operationBuilderName: operationBuilderNames[operationKind],
        operationId,
        operationKind,
        tag,
      },
      names,
    ),
  )

  const shouldExport = schema.export ?? true

  if (shouldExport) {
    const indexPath = joinPath(directory, "index.ts")
    upsertExport(tree, indexPath, relativeModulePath(indexPath, filePath))
  }

  const projectRoot = inferProjectRootFromDirectory(directory)
  const owningProject =
    schema.project ??
    (projectRoot === "."
      ? "workspace"
      : (projectRoot.split("/").at(-1) ?? projectRoot))
  upsertSourceBom(tree, {
    generatorName: "@attune/nx:effect-service",
    generatorVersion: schema.generatorVersion,
    generatorRevision: schema.generatorRevision,
    owningProject,
    projectRoot,
    sourceShapeKind: "effect-service",
    options: {
      directory,
      export: shouldExport,
      name: schema.name,
      operationId,
      operationKind,
      tag,
    },
    ownedFiles: shouldExport
      ? [filePath, joinPath(directory, "index.ts")]
      : [filePath],
    editableRegions: [
      {
        file: filePath,
        marker: "Generated by @attune/nx:effect-service",
        description:
          "Service module scaffold; implementation may extend the generated service boundary.",
      },
    ],
    syncTargets: [{ project: owningProject, target: "sync-effect-layers" }],
    checkTargets: [{ project: owningProject, target: "typecheck" }],
    openspecChangeId:
      schema.openspecChangeId ?? "promote-program-index-runtime-substrate",
  })
}
