import { upsertExport } from "../../internal/barrel.js"
import { joinPath, relativeModulePath } from "../../internal/paths.js"
import { type GeneratorTask, type GeneratorTree, writeTextIfChanged } from "../../internal/tree.js"
import { toNames } from "../../internal/names.js"

export interface DiscoveryEventGeneratorSchema {
  readonly name: string
  readonly directory?: string
  readonly export?: boolean
  readonly eventType?: string
  readonly viewKey?: string
}

const eventSource = (
  names: ReturnType<typeof toNames>,
  eventType: string,
  viewKey: string,
): string => `import { Effect, Schema } from "effect"

/**
 * Generated by @attune/nx:discovery-event.
 * Ownership: raw EventLog writes stay behind DiscoveryEvents/facade boundaries.
 * Ownership: projection handlers mutate durable read models and announce Reactivity
 * ViewKeys for durable facts, not UI components.
 */
export const ${names.className}Event = Schema.Struct({
  type: Schema.Literal("${eventType}"),
  discoveryId: Schema.String,
  occurredAt: Schema.DateFromSelf,
})
export type ${names.className}Event = Schema.Schema.Type<typeof ${names.className}Event>

export const ${names.propertyName}ViewKey = "${viewKey}" as const

export interface ${names.className}ProjectionStore {
  readonly record${names.className}: (event: ${names.className}Event) => Effect.Effect<void>
}

export interface ${names.className}ReactivitySink {
  readonly announce: (key: typeof ${names.propertyName}ViewKey) => Effect.Effect<void>
}

export const append${names.className} = (
  discoveryEvents: {
    readonly append: (event: ${names.className}Event) => Effect.Effect<void>
  },
  event: ${names.className}Event,
): Effect.Effect<void> =>
  // Keep world-changing EventLog writes inside DiscoveryEventsLive/facade code.
  discoveryEvents.append(event)

export const project${names.className} = (
  store: ${names.className}ProjectionStore,
  reactivity: ${names.className}ReactivitySink,
  event: ${names.className}Event,
): Effect.Effect<void> =>
  // Drizzle tables belong behind this persistence/read-model boundary.
  Effect.zipRight(store.record${names.className}(event), reactivity.announce(${names.propertyName}ViewKey))

export const ${names.propertyName}ReplayFixture = [
  {
    type: "${eventType}",
    discoveryId: "fixture-discovery",
    occurredAt: new Date("2026-01-01T00:00:00.000Z"),
  },
] satisfies ReadonlyArray<${names.className}Event>
`

export default function discoveryEventGenerator(
  tree: GeneratorTree,
  schema: DiscoveryEventGeneratorSchema,
): GeneratorTask {
  const names = toNames(schema.name)
  const directory = schema.directory ?? "src/discovery/events"
  const eventType = schema.eventType ?? names.fileName
  const viewKey = schema.viewKey ?? `discovery.${names.fileName}`
  const filePath = joinPath(directory, `${names.fileName}.ts`)

  writeTextIfChanged(tree, filePath, eventSource(names, eventType, viewKey))

  if (schema.export ?? true) {
    const indexPath = joinPath(directory, "index.ts")
    upsertExport(tree, indexPath, relativeModulePath(indexPath, filePath))
  }
}
