import { mkdir, rm, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import {
  defineAlchemyResource,
  defineInvocationRecipe,
  defineProjectionRecipe,
  defineRecipeHandler,
  defineRecipeLayer,
  type RecipeInvocation,
} from "@attune/framework-protocol"
import { Context, Effect, Layer, Schema } from "effect"
import type { CustomResourceDefinition } from "kubernetes-types/apiextensions/v1.d.ts"

import { attuneCrdDefinitions, type AttuneCrdDefinition } from "../../crds/definitions.js"
import { LocalComputeStackRecipeId } from "../../resources/local-compute-stack.js"

const PlatformAlchemyK8sProjectId = "platform-alchemy-k8s" as const
const CrdGenerationCliInvocationRecipeId =
  "platform-alchemy-k8s.crd-generation-cli-invocation" as const
const CrdTypeGenerationRecipeId =
  "platform-alchemy-k8s.crd-type-generation" as const
const KubernetesCrdDefinitionCatalogResourceId =
  "platform-alchemy-k8s.crd-definition-catalog.resource" as const
const KubernetesCrdGenerationWorkflowResourceId =
  "platform-alchemy-k8s.crd-generation-workflow.resource" as const
const KubernetesGeneratedCrdArtifactResourceId =
  "platform-alchemy-k8s.generated-crd-artifacts.resource" as const
const CrdGenerationRuntimeLayerId =
  "platform-alchemy-k8s.crd-generation-runtime.layer" as const
const CrdGenerationRuntimeServiceId =
  "platform-alchemy-k8s.crd-generation-runtime" as const
const CrdGenerationCliHandlerId =
  "platform-alchemy-k8s.crd-generation-cli-invocation.handler" as const
const CrdTypeGenerationHandlerId =
  "platform-alchemy-k8s.crd-type-generation.handler" as const
const CrdGenerationSourcePath =
  "packages/canopy/platform-alchemy-k8s/src/internal/generation/CrdGenerationCli.ts" as const

interface JsonSchema {
  readonly type?: string | readonly string[]
  readonly enum?: readonly string[]
  readonly properties?: Readonly<Record<string, JsonSchema>>
  readonly items?: JsonSchema
  readonly required?: readonly string[]
  readonly anyOf?: readonly JsonSchema[]
  readonly $ref?: string
  readonly $defs?: Readonly<Record<string, JsonSchema>>
  readonly additionalProperties?: boolean | JsonSchema
}

const generatedHeader = `// @generated by recipe ${CrdTypeGenerationRecipeId}
// projection: kubernetes-crd-types
// source: .attune/cache/generated/platform-alchemy-k8s/crds/*.crd.json
// This file is generated by platform-alchemy-k8s CRD codegen.
// Source CRDs live under src/crds.

export interface KubernetesObjectMeta {
  readonly name: string
  readonly namespace?: string
  readonly labels?: Readonly<Record<string, string>>
  readonly annotations?: Readonly<Record<string, string>>
}
`

const pascal = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/gu, "$1 $2")
    .split(/[^A-Za-z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")

const camel = (value: string): string => {
  const name = pascal(value)
  return `${name[0]?.toLowerCase() ?? "c"}${name.slice(1)}`
}

const schemaDocument = (schema: Schema.Top): JsonSchema =>
  normalizeJsonSchema(Schema.toJsonSchemaDocument(schema, { additionalProperties: false }).schema as JsonSchema)

const schemaForKubernetes = (schema: Schema.Top): JsonSchema => {
  const document = Schema.toJsonSchemaDocument(schema, { additionalProperties: false })
  const root = normalizeJsonSchema(document.schema as JsonSchema)
  if (Object.keys(document.definitions).length === 0) {
    return root
  }
  return {
    ...root,
    $defs: Object.fromEntries(
      Object.entries(document.definitions).map(([key, value]) => [key, normalizeJsonSchema(value as JsonSchema)]),
    ),
  }
}

const isNullSchema = (schema: JsonSchema): boolean => schema.type === "null"

const isSpecialNumberString = (schema: JsonSchema): boolean =>
  schema.type === "string" &&
  Array.isArray(schema.enum) &&
  schema.enum.every((item) => item === "NaN" || item === "Infinity" || item === "-Infinity")

const normalizeJsonSchema = (schema: JsonSchema): JsonSchema => {
  if (schema.anyOf) {
    const anyOf = schema.anyOf.map(normalizeJsonSchema).filter((item) => !isNullSchema(item) && !isSpecialNumberString(item))
    if (anyOf.length === 1) {
      return anyOf[0] ?? {}
    }
    return {
      ...schema,
      anyOf,
    }
  }
  return {
    ...schema,
    ...(schema.properties
      ? {
          properties: Object.fromEntries(
            Object.entries(schema.properties).map(([key, value]) => [key, normalizeJsonSchema(value)]),
          ),
        }
      : {}),
    ...(schema.items ? { items: normalizeJsonSchema(schema.items) } : {}),
    ...(schema.additionalProperties && typeof schema.additionalProperties === "object"
      ? { additionalProperties: normalizeJsonSchema(schema.additionalProperties) }
      : {}),
  }
}

const propertyType = (schema: JsonSchema | undefined): string => {
  if (!schema) {
    return "unknown"
  }
  if (schema.$ref) {
    return pascal(schema.$ref.split("/").at(-1) ?? "Referenced")
  }
  if (schema.anyOf) {
    return schema.anyOf.filter((item) => !isNullSchema(item) && !isSpecialNumberString(item)).map(propertyType).join(" | ")
  }
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((item) => JSON.stringify(item)).join(" | ")
  }
  const schemaType = Array.isArray(schema.type) ? schema.type.find((item) => item !== "null") : schema.type
  if (schema.type === "array") {
    return `ReadonlyArray<${propertyType(schema.items)}>`
  }
  if (schemaType === "array") {
    return `ReadonlyArray<${propertyType(schema.items)}>`
  }
  if (schemaType === "integer" || schemaType === "number") {
    return "number"
  }
  if (schemaType === "boolean") {
    return "boolean"
  }
  if (schemaType === "object") {
    if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
      return `Readonly<Record<string, ${propertyType(schema.additionalProperties)}>>`
    }
    return "Readonly<Record<string, unknown>>"
  }
  return "string"
}

const renderInterface = (name: string, schema: JsonSchema | undefined): string => {
  const properties = schema?.properties ?? {}
  const required = new Set(schema?.required ?? [])
  const lines = Object.entries(properties).map(([key, value]) => {
    const optional = required.has(key) ? "" : "?"
    return `  readonly ${key}${optional}: ${propertyType(value)}`
  })

  return `export interface ${name} {
${lines.join("\n")}
}
`
}

const makeCrd = (definition: AttuneCrdDefinition): CustomResourceDefinition => ({
  apiVersion: "apiextensions.k8s.io/v1",
  kind: "CustomResourceDefinition",
  metadata: {
    name: `${definition.plural}.attune.dev`,
  },
  spec: {
    group: "attune.dev",
    scope: "Namespaced",
    names: {
      plural: definition.plural,
      singular: definition.singular,
      kind: definition.kind,
      shortNames: [...definition.shortNames],
    },
    versions: [
      {
        name: "v1alpha1",
        served: true,
        storage: true,
        schema: {
          openAPIV3Schema: {
            type: "object",
            properties: {
              spec: schemaForKubernetes(definition.spec),
              status: schemaForKubernetes(definition.status),
            },
          } as any,
        },
      },
    ],
  },
})

const renderTypes = (definition: AttuneCrdDefinition): string => {
  const specSchema = schemaDocument(definition.spec)
  const statusSchema = schemaDocument(definition.status)
  const kind = definition.kind
  const apiVersion = "attune.dev/v1alpha1"
  return `
export const ${camel(kind)}CrdMetadata = {
  apiVersion: ${JSON.stringify(apiVersion)},
  group: "attune.dev",
  version: "v1alpha1",
  kind: ${JSON.stringify(kind)},
  plural: ${JSON.stringify(definition.plural)},
  scope: "Namespaced",
} as const

export interface ${kind} {
  readonly apiVersion: ${JSON.stringify(apiVersion)}
  readonly kind: ${JSON.stringify(kind)}
  readonly metadata: KubernetesObjectMeta
  readonly spec: ${kind}Spec
  readonly status?: ${kind}Status
}

${renderInterface(`${kind}Spec`, specSchema)}
${renderInterface(`${kind}Status`, statusSchema)}
`
}

const definitions = [...attuneCrdDefinitions].sort((left, right) => left.kind.localeCompare(right.kind))
const workspaceRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "..", "..")
const generatedRoot = join(workspaceRoot, ".attune", "cache", "generated", "platform-alchemy-k8s")
const generatedRootRelative = ".attune/cache/generated/platform-alchemy-k8s"

export const KubernetesCrdGenerationStage = Schema.Literals([
  "emit-crd-manifests",
  "emit-crd-types",
  "emit-generated",
  "generate-crd-types",
] as const)
export type KubernetesCrdGenerationStage = typeof KubernetesCrdGenerationStage.Type

export const KubernetesGeneratedArtifactRecipeInput = Schema.Struct({
  stage: KubernetesCrdGenerationStage,
  projectRoot: Schema.optional(Schema.String),
})
export type KubernetesGeneratedArtifactRecipeInput = typeof KubernetesGeneratedArtifactRecipeInput.Type

export const KubernetesGeneratedArtifactRecipeOutput = Schema.Struct({
  stage: KubernetesCrdGenerationStage,
  generatedFiles: Schema.Array(Schema.String),
  manifestCount: Schema.Number,
  recipeId: Schema.String,
})
export type KubernetesGeneratedArtifactRecipeOutput = typeof KubernetesGeneratedArtifactRecipeOutput.Type

// @attune-packet-target generated-runtime-projection eligible
export const KubernetesCrdDefinitionCatalogResource = defineAlchemyResource({
  id: KubernetesCrdDefinitionCatalogResourceId,
  kind: "schema",
  alchemyType: "attune:resource:Schema",
  ownerRecipeId: CrdTypeGenerationRecipeId,
  producedBy: [CrdTypeGenerationRecipeId],
  consumedBy: [CrdTypeGenerationRecipeId],
  addressFields: ["projectRoot"],
  addressSchema: KubernetesGeneratedArtifactRecipeInput as never,
  stateSchema: KubernetesGeneratedArtifactRecipeOutput as never,
  modes: ["read", "project"],
})

// @attune-packet-target generated-runtime-projection eligible
export const KubernetesCrdGenerationWorkflowResource = defineAlchemyResource({
  id: KubernetesCrdGenerationWorkflowResourceId,
  kind: "workflow-target",
  alchemyType: "attune:resource:WorkflowTarget",
  ownerRecipeId: CrdGenerationCliInvocationRecipeId,
  producedBy: [CrdGenerationCliInvocationRecipeId],
  consumedBy: [CrdTypeGenerationRecipeId],
  addressFields: ["stage"],
  addressSchema: KubernetesGeneratedArtifactRecipeInput as never,
  stateSchema: KubernetesGeneratedArtifactRecipeOutput as never,
  modes: ["invoke", "project", "read"],
  programmaticResourceExport: "CrdGenerationRuntime",
  programmaticProviderExport: "CrdGenerationRuntimeLive",
  programmaticBridgeSourcePath: CrdGenerationSourcePath,
})

// @attune-packet-target generated-runtime-projection eligible
export const KubernetesGeneratedCrdArtifactResource = defineAlchemyResource({
  id: KubernetesGeneratedCrdArtifactResourceId,
  kind: "generated-directory",
  alchemyType: "attune:resource:GeneratedDirectory",
  ownerRecipeId: CrdTypeGenerationRecipeId,
  producedBy: [CrdTypeGenerationRecipeId],
  consumedBy: [LocalComputeStackRecipeId],
  addressFields: ["stage", "projectRoot"],
  addressSchema: KubernetesGeneratedArtifactRecipeInput as never,
  stateSchema: KubernetesGeneratedArtifactRecipeOutput as never,
  modes: ["project", "read"],
  programmaticResourceExport: "KubernetesGeneratedCrdArtifactResource",
  programmaticProviderExport: "CrdGenerationRuntimeLive",
  programmaticBridgeSourcePath: CrdGenerationSourcePath,
})

const writeCrdManifests = Effect.gen(function* () {
  const manifestDir = join(generatedRoot, "crds")

  yield* Effect.promise(() => rm(manifestDir, { force: true, recursive: true }))
  yield* Effect.promise(() => mkdir(manifestDir, { recursive: true }))
  yield* Effect.all(
    definitions.map((definition) =>
      Effect.promise(() =>
        writeFile(
          join(manifestDir, `${definition.plural}.crd.json`),
          `${JSON.stringify(makeCrd(definition), null, 2)}\n`,
          "utf8",
        ),
      ),
    ),
    { concurrency: 4 },
  )
})

const writeCrdTypes = Effect.gen(function* () {
  const outFile = join(generatedRoot, "crds.ts")
  yield* Effect.promise(() => mkdir(generatedRoot, { recursive: true }))
  yield* Effect.promise(() => writeFile(outFile, `${generatedHeader}${definitions.map(renderTypes).join("\n")}`, "utf8"))
})

const writeGenerated = Effect.gen(function* () {
  yield* writeCrdManifests
  yield* writeCrdTypes
})

const runStage = (stageName: string): Effect.Effect<void, Error> => {
  switch (stageName) {
    case "emit-crd-manifests":
      return writeCrdManifests
    case "emit-crd-types":
      return writeCrdTypes
    case "emit-generated":
    case "generate-crd-types":
      return writeGenerated
    default:
      return Effect.fail(new Error(`Unknown platform-alchemy-k8s generation stage: ${stageName}`))
  }
}

const generatedFilesForStage = (
  stage: KubernetesCrdGenerationStage,
): readonly string[] => {
  const manifestFiles = definitions.map((definition) => `${generatedRootRelative}/crds/${definition.plural}.crd.json`)
  switch (stage) {
    case "emit-crd-manifests":
      return manifestFiles
    case "emit-crd-types":
      return [`${generatedRootRelative}/crds.ts`]
    case "emit-generated":
    case "generate-crd-types":
      return [`${generatedRootRelative}/crds.ts`, ...manifestFiles]
  }
}

const readStage = (stageName: string): KubernetesCrdGenerationStage =>
  Schema.decodeUnknownSync(KubernetesCrdGenerationStage)(stageName)

export interface CrdGenerationRuntimeService {
  readonly run: (stage: KubernetesCrdGenerationStage) => Effect.Effect<void, Error>
}

export class CrdGenerationRuntime extends Context.Service<
  CrdGenerationRuntime,
  CrdGenerationRuntimeService
>()("platform-alchemy-k8s/CrdGenerationRuntime") {}

export const CrdGenerationRuntimeLive = Layer.succeed(CrdGenerationRuntime, {
  run: (stage) => runStage(stage),
})

export const CrdGenerationRuntimeLayer = defineRecipeLayer({
  id: CrdGenerationRuntimeLayerId,
  sourcePath: CrdGenerationSourcePath,
  exportName: "CrdGenerationRuntimeLive",
  layer: CrdGenerationRuntimeLive as never,
  provides: [{
    id: CrdGenerationRuntimeServiceId,
    service: CrdGenerationRuntime as never,
  }],
})

const crdGenerationOutput = (
  stage: KubernetesCrdGenerationStage,
  recipeId: string,
): KubernetesGeneratedArtifactRecipeOutput => ({
  stage,
  generatedFiles: generatedFilesForStage(stage),
  manifestCount: definitions.length,
  recipeId,
})

export const runCrdGenerationCli = async (
  argv: readonly string[] = process.argv.slice(2),
): Promise<void> => {
  const stage = readStage(argv[0] ?? "emit-generated")
  await Effect.runPromise(runStage(stage))
}

export const crdGenerationCliRecipeInvocation = (
  stage: KubernetesCrdGenerationStage,
): RecipeInvocation => ({
  recipeId: CrdGenerationCliInvocationRecipeId,
  action: "generate",
  input: { stage },
  source: {
    surface: "nx",
    projectId: PlatformAlchemyK8sProjectId,
    target: "platform-alchemy-k8s:generate",
  },
})

export const CrdGenerationCliHandler = defineRecipeHandler<
  KubernetesGeneratedArtifactRecipeInput,
  KubernetesGeneratedArtifactRecipeOutput,
  Error,
  CrdGenerationRuntime
>({
  id: CrdGenerationCliHandlerId,
  recipeId: CrdGenerationCliInvocationRecipeId,
  sourcePath: CrdGenerationSourcePath,
  exportName: "runCrdGenerationCli",
  handler: (input) =>
    Effect.gen(function* () {
      const runtime = yield* CrdGenerationRuntime
      yield* runtime.run(input.stage)
      return crdGenerationOutput(input.stage, CrdGenerationCliInvocationRecipeId)
    }) as never,
  layer: CrdGenerationRuntimeLayer,
  emitsReceipts: ["platform-alchemy-k8s.crd-generation.invoked"],
})

export const CrdGenerationCliInvocationRecipe = defineInvocationRecipe({
  id: CrdGenerationCliInvocationRecipeId,
  projectId: PlatformAlchemyK8sProjectId,
  title: "Own Kubernetes CRD generation CLI invocation surface",
  inputSchema: KubernetesGeneratedArtifactRecipeInput as never,
  outputSchema: KubernetesGeneratedArtifactRecipeOutput as never,
  nxTarget: "platform-alchemy-k8s:generate",
  entrypoints: [CrdGenerationSourcePath],
  allowedFiles: [CrdGenerationSourcePath],
  validationEvidence: ["platform-alchemy-k8s:generate", "platform-alchemy-k8s:test"],
  io: {
    inputSchema: KubernetesGeneratedArtifactRecipeInput as never,
    outputSchema: KubernetesGeneratedArtifactRecipeOutput as never,
    inputResources: [KubernetesCrdGenerationWorkflowResource],
    outputResources: [KubernetesCrdGenerationWorkflowResource],
  },
  handler: CrdGenerationCliHandler,
  alchemyDag: [{
    fromRecipeId: CrdGenerationCliInvocationRecipeId,
    toRecipeId: CrdTypeGenerationRecipeId,
    resource: KubernetesCrdGenerationWorkflowResource,
    kind: "invokes",
    modes: ["invoke", "project", "read"],
  }],
})

export const CrdTypeGenerationHandler = defineRecipeHandler<
  KubernetesGeneratedArtifactRecipeInput,
  KubernetesGeneratedArtifactRecipeOutput,
  Error,
  CrdGenerationRuntime
>({
  ...CrdGenerationCliHandler,
  id: CrdTypeGenerationHandlerId,
  recipeId: CrdTypeGenerationRecipeId,
  handler: (input) =>
    Effect.gen(function* () {
      const runtime = yield* CrdGenerationRuntime
      yield* runtime.run(input.stage)
      return crdGenerationOutput(input.stage, CrdTypeGenerationRecipeId)
    }) as never,
  emitsReceipts: ["platform-alchemy-k8s.generated-crd-artifacts"],
})

// @attune-packet-target generated-runtime-projection eligible
export const CrdTypeGenerationRecipe = defineProjectionRecipe({
  id: CrdTypeGenerationRecipeId,
  projectId: PlatformAlchemyK8sProjectId,
  title: "Generate Kubernetes CRD types and manifests through a recipe-backed stage",
  inputSchema: KubernetesGeneratedArtifactRecipeInput as never,
  outputSchema: KubernetesGeneratedArtifactRecipeOutput as never,
  nxTarget: "platform-alchemy-k8s:generate",
  allowedFiles: [
    "packages/canopy/platform-alchemy-k8s/src/crds/**",
    "packages/canopy/platform-alchemy-k8s/src/internal/generation/**",
    "packages/canopy/platform-alchemy-k8s/project.json",
    ".attune/cache/generated/platform-alchemy-k8s/**",
  ],
  validationEvidence: ["platform-alchemy-k8s:generate", "platform-alchemy-k8s:test"],
  io: {
    inputSchema: KubernetesGeneratedArtifactRecipeInput as never,
    outputSchema: KubernetesGeneratedArtifactRecipeOutput as never,
    inputResources: [KubernetesCrdDefinitionCatalogResource, KubernetesCrdGenerationWorkflowResource],
    outputResources: [KubernetesGeneratedCrdArtifactResource],
  },
  handler: CrdTypeGenerationHandler,
  alchemyDag: [{
    fromRecipeId: CrdTypeGenerationRecipeId,
    toRecipeId: LocalComputeStackRecipeId,
    resource: KubernetesGeneratedCrdArtifactResource,
    kind: "projects",
    modes: ["project", "read"],
  }],
})

export const CrdGenerationRecipes = [
  CrdGenerationCliInvocationRecipe,
  CrdTypeGenerationRecipe,
] as const

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await runCrdGenerationCli()
}
