/* @generated by @attune/nx:attune-repair. Do not edit directly. */
/* Materialized package contract; edit ./attune.package.ts and run Nx repair. */
import { Layer, Schema } from "effect"
import {
  defineOperation,
  definePackageContract,
  definePackageViews,
  defineTypeGuidance,
  touches,
} from "@attune/framework-protocol"

import { generatedSchema } from "./pure/generated/schema.js"
import { createAttuneGenerated } from "./attune.generated.js"

export { PackageContractSchema } from "@attune/framework-protocol"

export const PackageViews = definePackageViews({
  reactivityKeys: [
    "joern-effect.runtime.query.changed",
    "joern-effect.program-builder.changed",
    "joern-effect.traversal-dsl.generated",
    "joern-effect.template-registry.changed",
    "joern-effect.query-evidence.changed",
    "joern-effect.generated-schema-coverage.changed",
  ],
  atoms: [
    "joernRuntimeAtom",
    "cpgProgramBuilderAtom",
    "traversalDslAtom",
    "templateRegistryAtom",
    "queryEvidenceAtom",
    "generatedSchemaCoverageAtom",
  ],
} as const)

export const JoernPackageServices = [
  "joern-effect/Joern",
  "joern-effect/CpgProgramBuilder",
] as const

export const JoernContractError = Schema.Struct({
  code: Schema.Literal(
    "joern-query-failed",
    "joern-decode-failed",
    "cpg-program-compile-failed",
    "generated-dsl-stale",
    "template-registry-unavailable",
    "package-view-unavailable",
  ),
  message: Schema.String,
  operationId: Schema.optional(Schema.String),
})
export type JoernContractError = typeof JoernContractError.Type

export const JoernRuntimeQueryInput = Schema.Struct({
  cpgql: Schema.String,
  mode: Schema.Literal("typed", "raw"),
  expectedSchema: Schema.optional(Schema.String),
})
export type JoernRuntimeQueryInput = typeof JoernRuntimeQueryInput.Type

export const JoernRuntimeQueryOutput = Schema.Struct({
  decoded: Schema.Boolean,
  rawBytes: Schema.Number,
  evidenceId: Schema.String,
})
export type JoernRuntimeQueryOutput = typeof JoernRuntimeQueryOutput.Type

export const CpgProgramBuilderInput = Schema.Struct({
  title: Schema.String,
  outputKind: Schema.Literal(
    "rows",
    "findings",
    "graph-facts",
    "protocol-deviations",
    "materialized-graph",
  ),
  bindingCount: Schema.Number,
})
export type CpgProgramBuilderInput = typeof CpgProgramBuilderInput.Type

export const CpgProgramBuilderOutput = Schema.Struct({
  title: Schema.String,
  cpgql: Schema.String,
  bindingCount: Schema.Number,
  planSummary: Schema.String,
})
export type CpgProgramBuilderOutput = typeof CpgProgramBuilderOutput.Type

export const GeneratedTraversalDslInput = Schema.Struct({
  stage: Schema.Literal(
    "emit-schema-modules",
    "emit-node-types",
    "emit-property-metadata",
    "emit-traversal-dsl",
    "emit-generated",
  ),
  schemaVersion: Schema.optional(Schema.String),
  schemaHash: Schema.optional(Schema.String),
})
export type GeneratedTraversalDslInput = typeof GeneratedTraversalDslInput.Type

export const GeneratedTraversalDslOutput = Schema.Struct({
  generatedFiles: Schema.Array(Schema.String),
  schemaVersion: Schema.String,
  schemaHash: Schema.String,
  nodeCount: Schema.Number,
  edgeCount: Schema.Number,
  propertyCount: Schema.Number,
})
export type GeneratedTraversalDslOutput = typeof GeneratedTraversalDslOutput.Type

export const JoernTemplateBoundaryInput = Schema.Struct({
  templateId: Schema.String,
  templateKind: Schema.Literal(
    "query-template",
    "proof-template",
    "evidence-template",
  ),
  evidenceKind: Schema.Literal(
    "finding",
    "graph-fact",
    "protocol-deviation",
    "raw-query",
  ),
})
export type JoernTemplateBoundaryInput = typeof JoernTemplateBoundaryInput.Type

export const JoernTemplateBoundaryOutput = Schema.Struct({
  registered: Schema.Boolean,
  registrySource: Schema.String,
  evidenceAtomId: Schema.String,
})
export type JoernTemplateBoundaryOutput = typeof JoernTemplateBoundaryOutput.Type

export const QueryEvidenceViewInput = Schema.Struct({
  evidenceId: Schema.String,
  queryKind: Schema.Literal(
    "typed-query",
    "raw-query",
    "compiled-program",
    "template-query",
  ),
})
export type QueryEvidenceViewInput = typeof QueryEvidenceViewInput.Type

export const PackageViewOutput = Schema.Struct({
  atomId: Schema.String,
  reactivityKeys: Schema.Array(Schema.String),
  summary: Schema.String,
})
export type PackageViewOutput = typeof PackageViewOutput.Type

export const GeneratedSchemaCoverageInput = Schema.Struct({
  schemaVersion: Schema.optional(Schema.String),
  includeGeneratedCounts: Schema.Boolean,
})
export type GeneratedSchemaCoverageInput = typeof GeneratedSchemaCoverageInput.Type

export const GeneratedSchemaCoverageOutput = Schema.Struct({
  atomId: Schema.String,
  schemaVersion: Schema.String,
  schemaHash: Schema.String,
  nodeCount: Schema.Number,
  edgeCount: Schema.Number,
  propertyCount: Schema.Number,
})
export type GeneratedSchemaCoverageOutput = typeof GeneratedSchemaCoverageOutput.Type

export const JoernSharedEvidenceSummary = Schema.Struct({
  evidenceKind: Schema.Literal(
    "query-evidence",
    "compiled-program-evidence",
    "generated-schema-coverage",
    "template-registry-evidence",
  ),
  operationId: Schema.String,
  protocolEvidenceKinds: Schema.Array(Schema.String),
  reactivityKeys: Schema.Array(Schema.String),
  atomIds: Schema.Array(Schema.String),
})
export type JoernSharedEvidenceSummary = typeof JoernSharedEvidenceSummary.Type

export const JoernTypedTargetIntent = Schema.Struct({
  targetName: Schema.String,
  intendedExecutor: Schema.Literal(
    "attune:package-check",
    "attune:generated",
    "attune:toolchain",
  ),
  resourceTier: Schema.Literal("commit", "push", "proof-pressure", "nightly"),
  commandSurfaceWaiverId: Schema.optional(Schema.String),
  operationIds: Schema.Array(Schema.String),
  typedOptions: Schema.Record({ key: Schema.String, value: Schema.Unknown }),
})
export type JoernTypedTargetIntent = typeof JoernTypedTargetIntent.Type

const runtimeKeys = [
  "joern-effect.runtime.query.changed",
  "joern-effect.query-evidence.changed",
] as const

const builderKeys = [
  "joern-effect.program-builder.changed",
  "joern-effect.query-evidence.changed",
] as const

const generatedKeys = [
  "joern-effect.traversal-dsl.generated",
  "joern-effect.generated-schema-coverage.changed",
] as const

const templateKeys = [
  "joern-effect.template-registry.changed",
  "joern-effect.query-evidence.changed",
] as const

const queryLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const commandLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "side-effect.declared-boundary",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const generatorLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.virtual-tree-only",
  "generator.options-decode",
  "generator.deterministic-output",
  "generator.provenance-recorded",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const joernTemplateLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "joern.template-schema",
  "joern.evidence-normalized",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const atomFamilyLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "side-effect.no-durable-atom-write",
  "atom-family.base-refresh",
  "atom-family.derived-composes",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

export const joernRuntimeQueryOperation = defineOperation({
  id: "joern-runtime-query",
  name: "Joern runtime query boundary",
  kind: "command",
  input: JoernRuntimeQueryInput,
  output: JoernRuntimeQueryOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: runtimeKeys,
    atoms: ["joernRuntimeAtom", "queryEvidenceAtom"],
  } as const),
  laws: commandLaws,
  metadata: {
    service: "joern-effect/Joern",
    boundary: "http-json-query",
    typedQuery: "Query<A> schema decode",
    evidenceShape: "JoernSharedEvidenceSummary",
  } as const,
} as const)

export const cpgProgramBuilderOperation = defineOperation({
  id: "cpg-program-builder",
  name: "CPG program builder compile boundary",
  kind: "query",
  input: CpgProgramBuilderInput,
  output: CpgProgramBuilderOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: builderKeys,
    atoms: ["cpgProgramBuilderAtom", "queryEvidenceAtom"],
  } as const),
  laws: queryLaws,
  metadata: {
    service: "joern-effect/CpgProgramBuilder",
    compiler: "CpgProgram.compile",
    evidenceShape: "JoernSharedEvidenceSummary",
    outputKinds: [
      "RowsOutput",
      "FindingsOutput",
      "GraphFactsOutput",
      "ProtocolDeviationOutput",
      "MaterializedGraphRef",
    ],
  } as const,
} as const)

export const generatedTraversalDslOperation = defineOperation({
  id: "generated-traversal-dsl",
  name: "Generated traversal DSL and schema modules",
  kind: "generator",
  input: GeneratedTraversalDslInput,
  output: GeneratedTraversalDslOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: generatedKeys,
    atoms: ["traversalDslAtom", "generatedSchemaCoverageAtom"],
  } as const),
  laws: generatorLaws,
  generator: {
    name: "joern-effect:emit-generated",
    project: "joern-effect",
    output: "src/pure/generated",
    intendedExecutor: "attune:generated",
    typedOptionsSchema: "JoernTypedTargetIntent",
  } as const,
} as const)

export const joernTemplateBoundaryOperation = defineOperation({
  id: "joern-template-boundary",
  name: "Joern template registry boundary",
  kind: "joern-template",
  input: JoernTemplateBoundaryInput,
  output: JoernTemplateBoundaryOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: templateKeys,
    atoms: ["templateRegistryAtom", "queryEvidenceAtom"],
  } as const),
  laws: joernTemplateLaws,
  joern: {
    registry: "TemplateRegistry.generated.ts",
    templateKinds: ["query-template", "proof-template", "evidence-template"],
    evidence: ["Finding", "GraphFact", "ProtocolDeviation"],
    evidenceShape: "JoernSharedEvidenceSummary",
  } as const,
} as const)

export const queryEvidenceViewOperation = defineOperation({
  id: "query-evidence-view",
  name: "Query evidence package view atoms",
  kind: "atom-family",
  input: QueryEvidenceViewInput,
  output: PackageViewOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: ["joern-effect.query-evidence.changed"],
    atoms: ["queryEvidenceAtom", "joernRuntimeAtom", "cpgProgramBuilderAtom"],
  } as const),
  laws: atomFamilyLaws,
  atom: {
    family: "query-evidence",
    baseAtoms: ["queryEvidenceAtom"],
    derivedAtoms: ["joernRuntimeAtom", "cpgProgramBuilderAtom"],
    subscribesTo: runtimeKeys,
  } as const,
} as const)

export const generatedSchemaCoverageOperation = defineOperation({
  id: "generated-schema-coverage",
  name: "Generated schema coverage package view atom",
  kind: "atom-family",
  input: GeneratedSchemaCoverageInput,
  output: GeneratedSchemaCoverageOutput,
  error: JoernContractError,
  views: touches(PackageViews, {
    reactivityKeys: ["joern-effect.generated-schema-coverage.changed"],
    atoms: ["generatedSchemaCoverageAtom", "traversalDslAtom"],
  } as const),
  laws: atomFamilyLaws,
  atom: {
    family: "generated-schema-coverage",
    baseAtoms: ["generatedSchemaCoverageAtom"],
    derivedAtoms: ["traversalDslAtom"],
    subscribesTo: generatedKeys,
  } as const,
} as const)

export const PackageOperations = [
  joernRuntimeQueryOperation,
  cpgProgramBuilderOperation,
  generatedTraversalDslOperation,
  joernTemplateBoundaryOperation,
  queryEvidenceViewOperation,
  generatedSchemaCoverageOperation,
] as const

export type JoernEffectOperationId = (typeof PackageOperations)[number]["id"]

export const PackageEvidenceShapes = {
  "joern-runtime-query": {
    evidenceKind: "query-evidence",
    operationId: "joern-runtime-query",
    protocolEvidenceKinds: ["property-run", "reactivity-key", "atom-movement"],
    reactivityKeys: runtimeKeys,
    atomIds: ["joernRuntimeAtom", "queryEvidenceAtom"],
  },
  "cpg-program-builder": {
    evidenceKind: "compiled-program-evidence",
    operationId: "cpg-program-builder",
    protocolEvidenceKinds: ["property-run", "coverage-point", "atom-movement"],
    reactivityKeys: builderKeys,
    atomIds: ["cpgProgramBuilderAtom", "queryEvidenceAtom"],
  },
  "generated-traversal-dsl": {
    evidenceKind: "generated-schema-coverage",
    operationId: "generated-traversal-dsl",
    protocolEvidenceKinds: ["property-run", "coverage-point", "atom-movement"],
    reactivityKeys: generatedKeys,
    atomIds: ["traversalDslAtom", "generatedSchemaCoverageAtom"],
  },
  "joern-template-boundary": {
    evidenceKind: "template-registry-evidence",
    operationId: "joern-template-boundary",
    protocolEvidenceKinds: ["property-run", "law-observed", "atom-movement"],
    reactivityKeys: templateKeys,
    atomIds: ["templateRegistryAtom", "queryEvidenceAtom"],
  },
  "query-evidence-view": {
    evidenceKind: "query-evidence",
    operationId: "query-evidence-view",
    protocolEvidenceKinds: ["atom-movement", "reactivity-key"],
    reactivityKeys: ["joern-effect.query-evidence.changed"],
    atomIds: ["queryEvidenceAtom", "joernRuntimeAtom", "cpgProgramBuilderAtom"],
  },
  "generated-schema-coverage": {
    evidenceKind: "generated-schema-coverage",
    operationId: "generated-schema-coverage",
    protocolEvidenceKinds: ["atom-movement", "coverage-point"],
    reactivityKeys: ["joern-effect.generated-schema-coverage.changed"],
    atomIds: ["generatedSchemaCoverageAtom", "traversalDslAtom"],
  },
} as const satisfies { readonly [Id in JoernEffectOperationId]: JoernSharedEvidenceSummary }
export type PackageEvidenceShapes = typeof PackageEvidenceShapes

export const PackageTargetIntents = [
  {
    targetName: "test",
    intendedExecutor: "attune:package-check",
    resourceTier: "commit",
    commandSurfaceWaiverId: "joern-effect/typed-executor-migration",
    operationIds: [
      "joern-runtime-query",
      "cpg-program-builder",
      "query-evidence-view",
      "generated-schema-coverage",
    ],
    typedOptions: {
      checkKind: "vitest",
      evidenceOutput: ".attune/cache/joern-effect/test-evidence.jsonl",
    },
  },
  {
    targetName: "emit-generated",
    intendedExecutor: "attune:generated",
    resourceTier: "push",
    commandSurfaceWaiverId: "joern-effect/typed-executor-migration",
    operationIds: ["generated-traversal-dsl"],
    typedOptions: {
      generatedRoot: "packages/joern-effect/src/pure/generated",
      schemaInput: "packages/joern-effect/schema/joern-cpg-schema.1.7.70.json",
    },
  },
  {
    targetName: "extract-cpg-schema",
    intendedExecutor: "attune:toolchain",
    resourceTier: "proof-pressure",
    commandSurfaceWaiverId: "joern-effect/typed-executor-migration",
    operationIds: ["generated-traversal-dsl", "joern-template-boundary"],
    typedOptions: {
      toolchain: "joern",
      envOptions: ["JOERN_HOME", "JOERN_CPG_VERSION"],
      outputRoot: "packages/joern-effect/schema",
    },
  },
] as const satisfies readonly JoernTypedTargetIntent[]
export type PackageTargetIntents = typeof PackageTargetIntents

export const PackageContract = definePackageContract({
  packageId: "joern-effect",
  sourceRoot: "packages/joern-effect/src",
  packageKind: "joern-runtime-and-dsl",
  views: PackageViews,
  services: JoernPackageServices,
  providedServices: JoernPackageServices,
  requiredServices: [
    "joern.process-config",
    "joern.http-transport",
    "joern.cpg-schema-source",
  ] as const,
  operations: PackageOperations,
  provenance: {
    generator: "@attune/nx:package-contract",
    customizedFor: "joern-effect runtime and generated CPG DSL",
    openspecChangeId: "standardize-effect-package-contracts",
    evidenceShapes: "PackageEvidenceShapes",
    targetIntents: "PackageTargetIntents",
  } as const,
  waivers: [
    {
      id: "joern-effect/context-tag-services",
      category: "legacy-boundary",
      owner: "proof-package-contract-agent",
      reason:
        "Joern and CpgProgramBuilder currently use lower-level Context.Tag service definitions until canonical Effect.Service migration lands.",
      review: "standardize-effect-package-contracts phase6 proof package validation",
    },
    {
      id: "joern-effect/process-runtime-boundary",
      category: "hidden-configuration",
      owner: "proof-package-contract-agent",
      reason:
        "Live Joern server startup still reads process/toolchain configuration and manages a child process behind Joern.layer; deterministic package audits use fixture handlers.",
      review: "standardize-effect-package-contracts task 11.4",
    },
    {
      id: "joern-effect/template-registry-generation-gap",
      category: "temporary-migration-adapter",
      owner: "proof-package-contract-agent",
      reason:
        "Template registry and evidence targets are declared as package boundaries before generated template registry source is materialized in this package.",
      review: "standardize-effect-package-contracts task 11.1",
    },
    {
      id: "joern-effect/typed-executor-migration",
      category: "temporary-migration-adapter",
      owner: "proof-package-evidence-integration-agent",
      reason:
        "Project targets and package scripts still use codex pnpm wrappers, Joern env variables, and shell redirection until attune:generated/toolchain executors land; PackageTargetIntents declares the typed options expected by the replacement.",
      review: "standardize-effect-package-contracts task 11.4",
    },
  ] as const,
} as const)
export type PackageContract = typeof PackageContract

export const PackageLayer = {
  layer: Layer.empty,
  provides: JoernPackageServices,
  requires: [
    "joern.process-config",
    "joern.http-transport",
    "joern.cpg-schema-source",
  ] as const,
  metadata: {
    packageId: "joern-effect",
    role: "joern-runtime-and-generated-dsl-boundary",
  },
} as const
export type PackageLayer = typeof PackageLayer

export const PackageTestLayer = {
  layer: Layer.empty,
  provides: [
    ...JoernPackageServices,
    "joern.process-config",
    "joern.http-transport",
    "joern.cpg-schema-source",
  ] as const,
  requires: [] as const,
  metadata: {
    packageId: "joern-effect",
    role: "joern-effect-fixture-audit-boundary",
    generatedSchemaVersion: generatedSchema.version,
  },
} as const
export type PackageTestLayer = typeof PackageTestLayer

const PackageGenerated = createAttuneGenerated({
  PackageContract,
  atomFamilyLaws,
  commandLaws,
  cpgProgramBuilderOperation,
  generatedSchema,
  generatedSchemaCoverageOperation,
  generatedTraversalDslOperation,
  generatorLaws,
  joernRuntimeQueryOperation,
  joernTemplateBoundaryOperation,
  joernTemplateLaws,
  queryEvidenceViewOperation,
  queryLaws,
} as const)
export const PackageFuzzHandlers = PackageGenerated.PackageFuzzHandlers
export const PackageProperties = PackageGenerated.PackageProperties
export const PackageTypeGuidance = PackageGenerated.PackageTypeGuidance
export type PackageFuzzHandlers = typeof PackageFuzzHandlers
export type PackageProperties = typeof PackageProperties
export type PackageTypeGuidance = typeof PackageTypeGuidance
