import { mkdir, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"

import { Effect, Schema } from "effect"
import type { CustomResourceDefinition } from "kubernetes-types/apiextensions/v1.d.ts"

import { attuneCrdDefinitions, type AttuneCrdDefinition } from "../src/crds/definitions.js"

interface JsonSchema {
  readonly type?: string | readonly string[]
  readonly enum?: readonly string[]
  readonly properties?: Readonly<Record<string, JsonSchema>>
  readonly items?: JsonSchema
  readonly required?: readonly string[]
  readonly anyOf?: readonly JsonSchema[]
  readonly $ref?: string
  readonly $defs?: Readonly<Record<string, JsonSchema>>
  readonly additionalProperties?: boolean | JsonSchema
}

const generatedHeader = `// This file is generated by platform-alchemy-k8s CRD codegen.
// Source CRDs live under src/crds.

export interface KubernetesObjectMeta {
  readonly name: string
  readonly namespace?: string
  readonly labels?: Readonly<Record<string, string>>
  readonly annotations?: Readonly<Record<string, string>>
}
`

const pascal = (value: string): string =>
  value
    .replace(/([a-z0-9])([A-Z])/gu, "$1 $2")
    .split(/[^A-Za-z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")

const camel = (value: string): string => {
  const name = pascal(value)
  return `${name[0]?.toLowerCase() ?? "c"}${name.slice(1)}`
}

const schemaDocument = (schema: Schema.Top): JsonSchema =>
  normalizeJsonSchema(Schema.toJsonSchemaDocument(schema, { additionalProperties: false }).schema as JsonSchema)

const schemaForKubernetes = (schema: Schema.Top): JsonSchema => {
  const document = Schema.toJsonSchemaDocument(schema, { additionalProperties: false })
  const root = normalizeJsonSchema(document.schema as JsonSchema)
  if (Object.keys(document.definitions).length === 0) {
    return root
  }
  return {
    ...root,
    $defs: Object.fromEntries(
      Object.entries(document.definitions).map(([key, value]) => [key, normalizeJsonSchema(value as JsonSchema)]),
    ),
  }
}

const isNullSchema = (schema: JsonSchema): boolean => schema.type === "null"

const isSpecialNumberString = (schema: JsonSchema): boolean =>
  schema.type === "string" &&
  Array.isArray(schema.enum) &&
  schema.enum.every((item) => item === "NaN" || item === "Infinity" || item === "-Infinity")

const normalizeJsonSchema = (schema: JsonSchema): JsonSchema => {
  if (schema.anyOf) {
    const anyOf = schema.anyOf.map(normalizeJsonSchema).filter((item) => !isNullSchema(item) && !isSpecialNumberString(item))
    if (anyOf.length === 1) {
      return anyOf[0] ?? {}
    }
    return {
      ...schema,
      anyOf,
    }
  }
  return {
    ...schema,
    ...(schema.properties
      ? {
          properties: Object.fromEntries(
            Object.entries(schema.properties).map(([key, value]) => [key, normalizeJsonSchema(value)]),
          ),
        }
      : {}),
    ...(schema.items ? { items: normalizeJsonSchema(schema.items) } : {}),
    ...(schema.additionalProperties && typeof schema.additionalProperties === "object"
      ? { additionalProperties: normalizeJsonSchema(schema.additionalProperties) }
      : {}),
  }
}

const propertyType = (schema: JsonSchema | undefined): string => {
  if (!schema) {
    return "unknown"
  }
  if (schema.$ref) {
    return pascal(schema.$ref.split("/").at(-1) ?? "Referenced")
  }
  if (schema.anyOf) {
    return schema.anyOf.filter((item) => !isNullSchema(item) && !isSpecialNumberString(item)).map(propertyType).join(" | ")
  }
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((item) => JSON.stringify(item)).join(" | ")
  }
  const schemaType = Array.isArray(schema.type) ? schema.type.find((item) => item !== "null") : schema.type
  if (schema.type === "array") {
    return `ReadonlyArray<${propertyType(schema.items)}>`
  }
  if (schemaType === "array") {
    return `ReadonlyArray<${propertyType(schema.items)}>`
  }
  if (schemaType === "integer" || schemaType === "number") {
    return "number"
  }
  if (schemaType === "boolean") {
    return "boolean"
  }
  if (schemaType === "object") {
    if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
      return `Readonly<Record<string, ${propertyType(schema.additionalProperties)}>>`
    }
    return "Readonly<Record<string, unknown>>"
  }
  return "string"
}

const renderInterface = (name: string, schema: JsonSchema | undefined): string => {
  const properties = schema?.properties ?? {}
  const required = new Set(schema?.required ?? [])
  const lines = Object.entries(properties).map(([key, value]) => {
    const optional = required.has(key) ? "" : "?"
    return `  readonly ${key}${optional}: ${propertyType(value)}`
  })

  return `export interface ${name} {
${lines.join("\n")}
}
`
}

const makeCrd = (definition: AttuneCrdDefinition): CustomResourceDefinition => ({
  apiVersion: "apiextensions.k8s.io/v1",
  kind: "CustomResourceDefinition",
  metadata: {
    name: `${definition.plural}.attune.dev`,
  },
  spec: {
    group: "attune.dev",
    scope: "Namespaced",
    names: {
      plural: definition.plural,
      singular: definition.singular,
      kind: definition.kind,
      shortNames: [...definition.shortNames],
    },
    versions: [
      {
        name: "v1alpha1",
        served: true,
        storage: true,
        schema: {
          openAPIV3Schema: {
            type: "object",
            properties: {
              spec: schemaForKubernetes(definition.spec),
              status: schemaForKubernetes(definition.status),
            },
          } as any,
        },
      },
    ],
  },
})

const renderTypes = (definition: AttuneCrdDefinition): string => {
  const specSchema = schemaDocument(definition.spec)
  const statusSchema = schemaDocument(definition.status)
  const kind = definition.kind
  const apiVersion = "attune.dev/v1alpha1"
  return `
export const ${camel(kind)}CrdMetadata = {
  apiVersion: ${JSON.stringify(apiVersion)},
  group: "attune.dev",
  version: "v1alpha1",
  kind: ${JSON.stringify(kind)},
  plural: ${JSON.stringify(definition.plural)},
  scope: "Namespaced",
} as const

export interface ${kind} {
  readonly apiVersion: ${JSON.stringify(apiVersion)}
  readonly kind: ${JSON.stringify(kind)}
  readonly metadata: KubernetesObjectMeta
  readonly spec: ${kind}Spec
  readonly status?: ${kind}Status
}

${renderInterface(`${kind}Spec`, specSchema)}
${renderInterface(`${kind}Status`, statusSchema)}
`
}

const definitions = [...attuneCrdDefinitions].sort((left, right) => left.kind.localeCompare(right.kind))

const writeCrdManifests = Effect.gen(function* () {
  const manifestDir = join("src", "generated", "crds")

  yield* Effect.promise(() => rm(manifestDir, { force: true, recursive: true }))
  yield* Effect.promise(() => mkdir(manifestDir, { recursive: true }))
  yield* Effect.all(
    definitions.map((definition) =>
      Effect.promise(() =>
        writeFile(
          join(manifestDir, `${definition.plural}.crd.json`),
          `${JSON.stringify(makeCrd(definition), null, 2)}\n`,
          "utf8",
        ),
      ),
    ),
    { concurrency: 4 },
  )
})

const writeCrdTypes = Effect.gen(function* () {
  const outFile = join("src", "generated", "crds.ts")
  yield* Effect.promise(() => mkdir(join("src", "generated"), { recursive: true }))
  yield* Effect.promise(() => writeFile(outFile, `${generatedHeader}${definitions.map(renderTypes).join("\n")}`, "utf8"))
})

const writeGenerated = Effect.gen(function* () {
  yield* writeCrdManifests
  yield* writeCrdTypes
})

const stage = process.argv[2] ?? "emit-generated"

const runStage = (stageName: string): Effect.Effect<void, Error> => {
  switch (stageName) {
    case "emit-crd-manifests":
      return writeCrdManifests
    case "emit-crd-types":
      return writeCrdTypes
    case "emit-generated":
    case "generate-crd-types":
      return writeGenerated
    default:
      return Effect.fail(new Error(`Unknown platform-alchemy-k8s generation stage: ${stageName}`))
  }
}

await Effect.runPromise(runStage(stage))
