import { upsertExport } from "../../internal/barrel.js"
import { joinPath, relativeModulePath } from "../../internal/paths.js"
import {
  inferProjectRootFromDirectory,
  upsertSourceBom,
} from "../../internal/source-bom.js"
import {
  type GeneratorTask,
  type GeneratorTree,
  writeTextIfChanged,
} from "../../internal/tree.js"
import { toNames } from "../../internal/names.js"

export interface AtomViewGeneratorSchema {
  readonly name: string
  readonly packageId?: string
  readonly operationId?: string
  readonly directory?: string
  readonly export?: boolean
  readonly reactivityKey?: string
  readonly baseAtomId?: string
  readonly derivedAtomId?: string
  readonly packageViewAtomId?: string
  readonly project?: string
  readonly generatorVersion?: string
  readonly generatorRevision?: string
  readonly openspecChangeId?: string
}

interface AtomViewPlan {
  readonly names: ReturnType<typeof toNames>
  readonly packageId: string
  readonly operationId: string
  readonly directory: string
  readonly shouldExport: boolean
  readonly reactivityKey: string
  readonly baseAtomId: string
  readonly derivedAtomId: string
  readonly packageViewAtomId: string
  readonly keysPath: string
  readonly baseAtomPath: string
  readonly derivedAtomPath: string
  readonly packageViewAtomPath: string
  readonly graphPath: string
  readonly indexPath: string
}

const atomViewPlan = (schema: AtomViewGeneratorSchema): AtomViewPlan => {
  const names = toNames(schema.name)
  const packageId = schema.packageId ?? "package"
  const operationId = schema.operationId ?? names.fileName
  const directory = schema.directory ?? "src/atoms"
  const reactivityKey = schema.reactivityKey ?? `${packageId}.${names.fileName}`
  const baseAtomId = schema.baseAtomId ?? `${names.propertyName}BaseAtom`
  const derivedAtomId = schema.derivedAtomId ?? `${names.propertyName}DerivedAtom`
  const packageViewAtomId =
    schema.packageViewAtomId ?? `${names.propertyName}PackageViewAtom`

  return {
    names,
    packageId,
    operationId,
    directory,
    shouldExport: schema.export ?? true,
    reactivityKey,
    baseAtomId,
    derivedAtomId,
    packageViewAtomId,
    keysPath: joinPath(directory, `${names.fileName}.reactivity.ts`),
    baseAtomPath: joinPath(directory, `${names.fileName}.base-atom.ts`),
    derivedAtomPath: joinPath(directory, `${names.fileName}.derived-atom.ts`),
    packageViewAtomPath: joinPath(
      directory,
      `${names.fileName}.package-view-atom.ts`,
    ),
    graphPath: joinPath(directory, `${names.fileName}.atom-graph.ts`),
    indexPath: joinPath(directory, "index.ts"),
  }
}

const reactivitySource = (plan: AtomViewPlan): string => `/**
 * Generated by @attune/nx:atom-view.
 * Ownership: Effect services and projections change facts; Reactivity keys
 * announce freshness for package atoms.
 */
export const ${plan.names.propertyName}OperationId = "${plan.operationId}" as const

export const ${plan.names.propertyName}ReactivityKeys = {
  ${plan.names.propertyName}: "${plan.reactivityKey}",
} as const

export type ${plan.names.className}ReactivityKey =
  (typeof ${plan.names.propertyName}ReactivityKeys)[keyof typeof ${plan.names.propertyName}ReactivityKeys]

export const ${plan.names.propertyName}OperationReactivityEdges = [
  {
    operationId: ${plan.names.propertyName}OperationId,
    reactivityKey: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
  },
] as const
`

const baseAtomSource = (plan: AtomViewPlan): string => `import {
  ${plan.names.propertyName}ReactivityKeys,
  type ${plan.names.className}ReactivityKey,
} from "./${plan.names.fileName}.reactivity.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: base atoms read durable package facts and subscribe to Reactivity.
 */
export const ${plan.names.propertyName}BaseAtomId = "${plan.baseAtomId}" as const

export interface ${plan.names.className}BaseAtom<Scope = string, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}BaseAtomId
  readonly label: string
  readonly reactivityKey: ${plan.names.className}ReactivityKey
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}BaseAtom = <
  Scope = string,
  Value = unknown,
>(
  read: (scope: Scope) => Value,
): ${plan.names.className}BaseAtom<Scope, Value> => ({
  id: ${plan.names.propertyName}BaseAtomId,
  label: "${plan.baseAtomId}",
  reactivityKey: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
  read,
})
`

const derivedAtomSource = (plan: AtomViewPlan): string => `import type { ${plan.names.className}BaseAtom } from "./${plan.names.fileName}.base-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: derived atoms compose base atoms or other derived atoms.
 */
export const ${plan.names.propertyName}DerivedAtomId = "${plan.derivedAtomId}" as const

export interface ${plan.names.className}DerivedAtom<Scope = string, Input = unknown, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}DerivedAtomId
  readonly label: string
  readonly sourceAtomId: string
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}DerivedAtom = <
  Scope = string,
  Input = unknown,
  Value = unknown,
>(
  baseAtom: ${plan.names.className}BaseAtom<Scope, Input>,
  derive: (value: Input, scope: Scope) => Value,
): ${plan.names.className}DerivedAtom<Scope, Input, Value> => ({
  id: ${plan.names.propertyName}DerivedAtomId,
  label: "${plan.derivedAtomId}",
  sourceAtomId: baseAtom.id,
  read: (scope) => derive(baseAtom.read(scope), scope),
})
`

const packageViewAtomSource = (plan: AtomViewPlan): string => `import type { ${plan.names.className}DerivedAtom } from "./${plan.names.fileName}.derived-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: package view atoms expose stable semantic package views to agents.
 */
export const ${plan.names.propertyName}PackageViewAtomId = "${plan.packageViewAtomId}" as const

export interface ${plan.names.className}PackageViewAtom<Scope = string, Input = unknown, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}PackageViewAtomId
  readonly label: string
  readonly sourceAtomId: string
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}PackageViewAtom = <
  Scope = string,
  Input = unknown,
  Value = unknown,
>(
  derivedAtom: ${plan.names.className}DerivedAtom<Scope, Input, Input>,
  project: (value: Input, scope: Scope) => Value,
): ${plan.names.className}PackageViewAtom<Scope, Input, Value> => ({
  id: ${plan.names.propertyName}PackageViewAtomId,
  label: "${plan.packageViewAtomId}",
  sourceAtomId: derivedAtom.id,
  read: (scope) => project(derivedAtom.read(scope), scope),
})
`

const graphSource = (plan: AtomViewPlan): string => `import {
  ${plan.names.propertyName}OperationId,
  ${plan.names.propertyName}ReactivityKeys,
} from "./${plan.names.fileName}.reactivity.js"
import { ${plan.names.propertyName}BaseAtomId } from "./${plan.names.fileName}.base-atom.js"
import { ${plan.names.propertyName}DerivedAtomId } from "./${plan.names.fileName}.derived-atom.js"
import { ${plan.names.propertyName}PackageViewAtomId } from "./${plan.names.fileName}.package-view-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * This registration makes the path
 * operation -> Reactivity key -> base atom -> derived atom -> package view atom
 * visible to package-contract, property, and coverage checks.
 */
export const ${plan.names.propertyName}AtomGraph = {
  packageId: "${plan.packageId}",
  operationId: ${plan.names.propertyName}OperationId,
  reactivityKeys: [${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName}],
  baseAtoms: [${plan.names.propertyName}BaseAtomId],
  derivedAtoms: [${plan.names.propertyName}DerivedAtomId],
  packageViewAtoms: [${plan.names.propertyName}PackageViewAtomId],
  edges: [
    {
      kind: "operation-reactivity",
      from: ${plan.names.propertyName}OperationId,
      to: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
    },
    {
      kind: "reactivity-base-atom",
      from: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
      to: ${plan.names.propertyName}BaseAtomId,
    },
    {
      kind: "base-derived-atom",
      from: ${plan.names.propertyName}BaseAtomId,
      to: ${plan.names.propertyName}DerivedAtomId,
    },
    {
      kind: "derived-package-view-atom",
      from: ${plan.names.propertyName}DerivedAtomId,
      to: ${plan.names.propertyName}PackageViewAtomId,
    },
  ],
} as const

export type ${plan.names.className}AtomGraph =
  typeof ${plan.names.propertyName}AtomGraph
`

export default function atomViewGenerator(
  tree: GeneratorTree,
  schema: AtomViewGeneratorSchema,
): GeneratorTask {
  const plan = atomViewPlan(schema)

  writeTextIfChanged(tree, plan.keysPath, reactivitySource(plan))
  writeTextIfChanged(tree, plan.baseAtomPath, baseAtomSource(plan))
  writeTextIfChanged(tree, plan.derivedAtomPath, derivedAtomSource(plan))
  writeTextIfChanged(
    tree,
    plan.packageViewAtomPath,
    packageViewAtomSource(plan),
  )
  writeTextIfChanged(tree, plan.graphPath, graphSource(plan))

  if (plan.shouldExport) {
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.keysPath))
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.baseAtomPath))
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.derivedAtomPath))
    upsertExport(
      tree,
      plan.indexPath,
      relativeModulePath(plan.indexPath, plan.packageViewAtomPath),
    )
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.graphPath))
  }

  const projectRoot = inferProjectRootFromDirectory(plan.directory)
  const owningProject =
    schema.project ??
    (projectRoot === "."
      ? "workspace"
      : (projectRoot.split("/").at(-1) ?? projectRoot))

  upsertSourceBom(tree, {
    generatorName: "@attune/nx:atom-view",
    generatorVersion: schema.generatorVersion,
    generatorRevision: schema.generatorRevision,
    owningProject,
    projectRoot,
    sourceShapeKind: "atom-view",
    options: {
      baseAtomId: plan.baseAtomId,
      derivedAtomId: plan.derivedAtomId,
      directory: plan.directory,
      export: plan.shouldExport,
      name: schema.name,
      operationId: plan.operationId,
      packageId: plan.packageId,
      packageViewAtomId: plan.packageViewAtomId,
      reactivityKey: plan.reactivityKey,
    },
    ownedFiles: plan.shouldExport
      ? [
          plan.baseAtomPath,
          plan.derivedAtomPath,
          plan.graphPath,
          plan.indexPath,
          plan.keysPath,
          plan.packageViewAtomPath,
        ]
      : [
          plan.baseAtomPath,
          plan.derivedAtomPath,
          plan.graphPath,
          plan.keysPath,
          plan.packageViewAtomPath,
        ],
    editableRegions: [
      {
        file: plan.baseAtomPath,
        marker: "Generated by @attune/nx:atom-view",
        description:
          "Base atom shell; keep durable writes behind Effect services and projections.",
      },
      {
        file: plan.graphPath,
        marker: "operation -> Reactivity key -> base atom -> derived atom -> package view atom",
        description:
          "Package atom graph registration consumed by conformance and property evidence.",
      },
    ],
    syncTargets: [{ project: owningProject, target: "sync-package-contract" }],
    checkTargets: [{ project: owningProject, target: "atom-graph-conformance" }],
    openspecChangeId:
      schema.openspecChangeId ?? "standardize-effect-package-contracts",
  })
}
