import { upsertExport } from "../../internal/barrel.js"
import { joinPath, relativeModulePath } from "../../internal/paths.js"
import {
  inferProjectRootFromDirectory,
  upsertSourceBom,
} from "../../internal/source-bom.js"
import {
  type GeneratorTask,
  type GeneratorTree,
  writeTextIfChanged,
} from "../../internal/tree.js"
import { toNames } from "../../internal/names.js"

export interface AtomViewGeneratorSchema {
  readonly name: string
  readonly projectId?: string
  readonly symbolId?: string
  readonly directory?: string
  readonly export?: boolean
  readonly reactivityKey?: string
  readonly baseAtomId?: string
  readonly derivedAtomId?: string
  readonly projectAtomId?: string
  readonly project?: string
  readonly generatorVersion?: string
  readonly generatorRevision?: string
  readonly openspecChangeId?: string
}

interface AtomViewPlan {
  readonly names: ReturnType<typeof toNames>
  readonly projectId: string
  readonly symbolId: string
  readonly directory: string
  readonly shouldExport: boolean
  readonly reactivityKey: string
  readonly baseAtomId: string
  readonly derivedAtomId: string
  readonly projectAtomId: string
  readonly keysPath: string
  readonly baseAtomPath: string
  readonly derivedAtomPath: string
  readonly projectAtomPath: string
  readonly graphPath: string
  readonly indexPath: string
}

const atomViewPlan = (schema: AtomViewGeneratorSchema): AtomViewPlan => {
  const names = toNames(schema.name)
  const projectId = schema.projectId ?? "project"
  const symbolId = schema.symbolId ?? names.fileName
  const directory = schema.directory ?? "src/atoms"
  const reactivityKey = schema.reactivityKey ?? `${projectId}.${names.fileName}`
  const baseAtomId = schema.baseAtomId ?? `${names.propertyName}BaseAtom`
  const derivedAtomId = schema.derivedAtomId ?? `${names.propertyName}DerivedAtom`
  const projectAtomId =
    schema.projectAtomId ?? `${names.propertyName}ProjectAtom`

  return {
    names,
    projectId,
    symbolId,
    directory,
    shouldExport: schema.export ?? true,
    reactivityKey,
    baseAtomId,
    derivedAtomId,
    projectAtomId,
    keysPath: joinPath(directory, `${names.fileName}.reactivity.ts`),
    baseAtomPath: joinPath(directory, `${names.fileName}.base-atom.ts`),
    derivedAtomPath: joinPath(directory, `${names.fileName}.derived-atom.ts`),
    projectAtomPath: joinPath(
      directory,
      `${names.fileName}.project-atom.ts`,
    ),
    graphPath: joinPath(directory, `${names.fileName}.atom-graph.ts`),
    indexPath: joinPath(directory, "index.ts"),
  }
}

const reactivitySource = (plan: AtomViewPlan): string => `/**
 * Generated by @attune/nx:atom-view.
 * Ownership: Effect services and projections change facts; Reactivity keys
 * announce freshness for project atoms.
 */
export const ${plan.names.propertyName}SymbolId = "${plan.symbolId}" as const

export const ${plan.names.propertyName}ReactivityKeys = {
  ${plan.names.propertyName}: "${plan.reactivityKey}",
} as const

export type ${plan.names.className}ReactivityKey =
  (typeof ${plan.names.propertyName}ReactivityKeys)[keyof typeof ${plan.names.propertyName}ReactivityKeys]

export const ${plan.names.propertyName}SymbolReactivityEdges = [
  {
    symbolId: ${plan.names.propertyName}SymbolId,
    reactivityKey: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
  },
] as const
`

const baseAtomSource = (plan: AtomViewPlan): string => `import {
  ${plan.names.propertyName}ReactivityKeys,
  type ${plan.names.className}ReactivityKey,
} from "./${plan.names.fileName}.reactivity.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: base atoms read durable project facts and subscribe to Reactivity.
 */
export const ${plan.names.propertyName}BaseAtomId = "${plan.baseAtomId}" as const

export interface ${plan.names.className}BaseAtom<Scope = string, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}BaseAtomId
  readonly label: string
  readonly reactivityKey: ${plan.names.className}ReactivityKey
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}BaseAtom = <
  Scope = string,
  Value = unknown,
>(
  read: (scope: Scope) => Value,
): ${plan.names.className}BaseAtom<Scope, Value> => ({
  id: ${plan.names.propertyName}BaseAtomId,
  label: "${plan.baseAtomId}",
  reactivityKey: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
  read,
})
`

const derivedAtomSource = (plan: AtomViewPlan): string => `import type { ${plan.names.className}BaseAtom } from "./${plan.names.fileName}.base-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: derived atoms compose base atoms or other derived atoms.
 */
export const ${plan.names.propertyName}DerivedAtomId = "${plan.derivedAtomId}" as const

export interface ${plan.names.className}DerivedAtom<Scope = string, Input = unknown, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}DerivedAtomId
  readonly label: string
  readonly sourceAtomId: string
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}DerivedAtom = <
  Scope = string,
  Input = unknown,
  Value = unknown,
>(
  baseAtom: ${plan.names.className}BaseAtom<Scope, Input>,
  derive: (value: Input, scope: Scope) => Value,
): ${plan.names.className}DerivedAtom<Scope, Input, Value> => ({
  id: ${plan.names.propertyName}DerivedAtomId,
  label: "${plan.derivedAtomId}",
  sourceAtomId: baseAtom.id,
  read: (scope) => derive(baseAtom.read(scope), scope),
})
`

const projectAtomSource = (plan: AtomViewPlan): string => `import type { ${plan.names.className}DerivedAtom } from "./${plan.names.fileName}.derived-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * Ownership: project atoms expose stable semantic project atoms to agents.
 */
export const ${plan.names.propertyName}ProjectAtomId = "${plan.projectAtomId}" as const

export interface ${plan.names.className}ProjectAtom<Scope = string, Input = unknown, Value = unknown> {
  readonly id: typeof ${plan.names.propertyName}ProjectAtomId
  readonly label: string
  readonly sourceAtomId: string
  readonly read: (scope: Scope) => Value
}

export const ${plan.names.propertyName}ProjectAtom = <
  Scope = string,
  Input = unknown,
  Value = unknown,
>(
  derivedAtom: ${plan.names.className}DerivedAtom<Scope, Input, Input>,
  project: (value: Input, scope: Scope) => Value,
): ${plan.names.className}ProjectAtom<Scope, Input, Value> => ({
  id: ${plan.names.propertyName}ProjectAtomId,
  label: "${plan.projectAtomId}",
  sourceAtomId: derivedAtom.id,
  read: (scope) => project(derivedAtom.read(scope), scope),
})
`

const graphSource = (plan: AtomViewPlan): string => `import {
  ${plan.names.propertyName}SymbolId,
  ${plan.names.propertyName}ReactivityKeys,
} from "./${plan.names.fileName}.reactivity.js"
import { ${plan.names.propertyName}BaseAtomId } from "./${plan.names.fileName}.base-atom.js"
import { ${plan.names.propertyName}DerivedAtomId } from "./${plan.names.fileName}.derived-atom.js"
import { ${plan.names.propertyName}ProjectAtomId } from "./${plan.names.fileName}.project-atom.js"

/**
 * Generated by @attune/nx:atom-view.
 * This registration makes the path
 * symbol -> Reactivity key -> base atom -> derived atom -> project atom
 * visible to project facts, observations, and coverage checks.
 */
export const ${plan.names.propertyName}AtomGraph = {
  projectId: "${plan.projectId}",
  symbolId: ${plan.names.propertyName}SymbolId,
  reactivityKeys: [${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName}],
  baseAtoms: [${plan.names.propertyName}BaseAtomId],
  derivedAtoms: [${plan.names.propertyName}DerivedAtomId],
  projectAtoms: [${plan.names.propertyName}ProjectAtomId],
  edges: [
    {
      kind: "symbol-reactivity",
      from: ${plan.names.propertyName}SymbolId,
      to: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
    },
    {
      kind: "reactivity-base-atom",
      from: ${plan.names.propertyName}ReactivityKeys.${plan.names.propertyName},
      to: ${plan.names.propertyName}BaseAtomId,
    },
    {
      kind: "base-derived-atom",
      from: ${plan.names.propertyName}BaseAtomId,
      to: ${plan.names.propertyName}DerivedAtomId,
    },
    {
      kind: "derived-project-atom",
      from: ${plan.names.propertyName}DerivedAtomId,
      to: ${plan.names.propertyName}ProjectAtomId,
    },
  ],
} as const

export type ${plan.names.className}AtomGraph =
  typeof ${plan.names.propertyName}AtomGraph
`

export default function atomViewGenerator(
  tree: GeneratorTree,
  schema: AtomViewGeneratorSchema,
): GeneratorTask {
  const plan = atomViewPlan(schema)

  writeTextIfChanged(tree, plan.keysPath, reactivitySource(plan))
  writeTextIfChanged(tree, plan.baseAtomPath, baseAtomSource(plan))
  writeTextIfChanged(tree, plan.derivedAtomPath, derivedAtomSource(plan))
  writeTextIfChanged(
    tree,
    plan.projectAtomPath,
    projectAtomSource(plan),
  )
  writeTextIfChanged(tree, plan.graphPath, graphSource(plan))

  if (plan.shouldExport) {
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.keysPath))
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.baseAtomPath))
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.derivedAtomPath))
    upsertExport(
      tree,
      plan.indexPath,
      relativeModulePath(plan.indexPath, plan.projectAtomPath),
    )
    upsertExport(tree, plan.indexPath, relativeModulePath(plan.indexPath, plan.graphPath))
  }

  const projectRoot = inferProjectRootFromDirectory(plan.directory)
  const owningProject =
    schema.project ??
    (projectRoot === "."
      ? "workspace"
      : (projectRoot.split("/").at(-1) ?? projectRoot))

  upsertSourceBom(tree, {
    generatorName: "@attune/nx:atom-view",
    generatorVersion: schema.generatorVersion,
    generatorRevision: schema.generatorRevision,
    owningProject,
    projectRoot,
    sourceShapeKind: "atom-view",
    options: {
      baseAtomId: plan.baseAtomId,
      derivedAtomId: plan.derivedAtomId,
      directory: plan.directory,
      export: plan.shouldExport,
      name: schema.name,
      symbolId: plan.symbolId,
      projectId: plan.projectId,
      projectAtomId: plan.projectAtomId,
      reactivityKey: plan.reactivityKey,
    },
    ownedFiles: plan.shouldExport
      ? [
          plan.baseAtomPath,
          plan.derivedAtomPath,
          plan.graphPath,
          plan.indexPath,
          plan.keysPath,
          plan.projectAtomPath,
        ]
      : [
          plan.baseAtomPath,
          plan.derivedAtomPath,
          plan.graphPath,
          plan.keysPath,
          plan.projectAtomPath,
        ],
    editableRegions: [
      {
        file: plan.baseAtomPath,
        marker: "Generated by @attune/nx:atom-view",
        description:
          "Base atom shell; keep durable writes behind Effect services and projections.",
      },
      {
        file: plan.graphPath,
        marker: "symbol -> Reactivity key -> base atom -> derived atom -> project atom",
        description:
          "Project runtime edge registration consumed by conformance and observations.",
      },
    ],
    syncTargets: [{ project: owningProject, target: "sync-project-facts" }],
    checkTargets: [{ project: owningProject, target: "atom-graph-conformance" }],
    openspecChangeId:
      schema.openspecChangeId ?? "promote-program-index-runtime-substrate",
  })
}
