/* @generated by @attune/nx:attune-repair. Do not edit directly. */
// @ts-nocheck
import {
  definePackageFuzzRpcGroup,
  defineTypeGuidance,
  type AttunePackageContract,
} from "@attune/framework-protocol"

export const createAttuneGenerated = <
  const Contract extends AttunePackageContract,
  const CodecLaws extends readonly string[],
  const CommandLaws extends readonly string[],
  const GeneratorLaws extends readonly string[],
  const QueryLaws extends readonly string[],
  const Source extends { readonly PackageContract: Contract; readonly codecLaws: CodecLaws; readonly commandLaws: CommandLaws; readonly generatorLaws: GeneratorLaws; readonly queryLaws: QueryLaws } & Readonly<Record<string, unknown>>,
>(source: Source) => {
  const PackageContract = source.PackageContract
  const {
    codecLaws,
    commandLaws,
    commandLifecycleOperation,
    decodeMcpSearchResultOperation,
    emitMcpSchemaOperation,
    emptyAnchors,
    ensureIndexedOperation,
    fixtureClientQueryOperation,
    generatorLaws,
    getAnchorOperation,
    mcpLifecycleOperation,
    normalizeRawHitsOperation,
    packageTestFixture,
    queryLaws,
    repositoryIntelligenceQueryOperation,
    repositorySessionOperation,
    repositoryToolStatusViewOperation,
    searchAnchorsOperation,
    searchSimilarAnchorsOperation,
    syncMcpToolRegistryOperation,
  } = source

  const PackageFuzzHandlers = {
    "ensure-indexed": () => ({
      repoSnapshotId: "repo-fixture",
      indexedAt: packageTestFixture.indexedAt,
      indexUri: "memory://cocoindex/repo-fixture",
    }),
    "search-anchors": () => emptyAnchors,
    "search-similar-anchors": () => emptyAnchors,
    "get-anchor": () => packageTestFixture.anchors[0],
    "fixture-client-query": () => packageTestFixture.anchors,
    "normalize-raw-hits": () => emptyAnchors,
    "decode-mcp-search-result": () => ({
      success: true,
      results: [],
      total_returned: 0,
      offset: 0,
    }),
    "repository-session": () => ({
      repoPath: "/workspace/attune",
      repoSnapshotId: "repo-fixture",
      runId: "run-fixture",
      status: [
        { tool: "cocoindex" as const, phase: "Ready" as const },
        { tool: "joern" as const, phase: "Ready" as const },
      ],
    }),
    "repository-intelligence-query": () => ({
      anchors: packageTestFixture.anchors,
      status: [
        { tool: "cocoindex" as const, phase: "Ready" as const },
        { tool: "joern" as const, phase: "Ready" as const },
      ],
    }),
    "repository-tool-status-view": () => ({
      status: [
        { tool: "cocoindex" as const, phase: "Ready" as const },
        { tool: "joern" as const, phase: "Ready" as const },
      ],
    }),
    "command-lifecycle": () => ({
      operation: "searchAnchors" as const,
      decoded: true,
      transport: "subprocess-json" as const,
    }),
    "mcp-lifecycle": () => ({
      status: { tool: "cocoindex" as const, phase: "Ready" as const },
      transport: "mcp-stdio" as const,
    }),
    "emit-mcp-schema": () => ({
      files: [
        {
          path: "src/generated/cocoindex-code-mcp.ts",
          generator: "scripts/generationStage.ts emit-mcp-schema",
          generated: true,
        },
      ],
      deterministic: true,
    }),
    "sync-mcp-tool-registry": () => ({
      tools: [
        {
          name: "search",
          inputSchema: "CocoIndexMcpSearchInput",
          resultSchema: "CocoIndexMcpSearchResult",
        },
      ],
      generatedFiles: ["src/cocoindex/tools/ToolRegistry.generated.ts"],
    }),
  } as const
  type PackageFuzzHandlers = typeof PackageFuzzHandlers

  const PackageProperties = {
    "ensure-indexed": propertyFor(ensureIndexedOperation),
    "search-anchors": propertyFor(searchAnchorsOperation),
    "search-similar-anchors": propertyFor(searchSimilarAnchorsOperation),
    "get-anchor": propertyFor(getAnchorOperation),
    "fixture-client-query": propertyFor(fixtureClientQueryOperation),
    "normalize-raw-hits": propertyFor(normalizeRawHitsOperation),
    "decode-mcp-search-result": propertyFor(decodeMcpSearchResultOperation),
    "repository-session": propertyFor(repositorySessionOperation),
    "repository-intelligence-query": propertyFor(
      repositoryIntelligenceQueryOperation,
    ),
    "repository-tool-status-view": propertyFor(repositoryToolStatusViewOperation),
    "command-lifecycle": propertyFor(commandLifecycleOperation),
    "mcp-lifecycle": propertyFor(mcpLifecycleOperation),
    "emit-mcp-schema": propertyFor(emitMcpSchemaOperation),
    "sync-mcp-tool-registry": propertyFor(syncMcpToolRegistryOperation),
  } as const
  type PackageProperties = typeof PackageProperties

  const PackageTypeGuidance = defineTypeGuidance(PackageContract, {
    sourceLabels: [
      "contract.operation",
      "effect-schema.ast",
      "semantic-recall-service",
      "declared-view",
      "mcp-tool-registry",
    ],
    operations: {
      "ensure-indexed": operationGuidance(ensureIndexedOperation, {
        laws: commandLaws,
        inputPartitionId: "ensure-indexed.repo-snapshot",
        outputPartitionId: "ensure-indexed.index-uri",
        coverageTargetId: "ensure-indexed.index-freshness",
        transformId: "ensure-indexed.fixture-snapshot",
      }),
      "search-anchors": operationGuidance(searchAnchorsOperation, {
        laws: queryLaws,
        inputPartitionId: "search-anchors.query-and-filters",
        outputPartitionId: "search-anchors.result-ordering",
        coverageTargetId: "search-anchors.search-result",
        transformId: "search-anchors.query-token-bias",
      }),
      "search-similar-anchors": operationGuidance(searchSimilarAnchorsOperation, {
        laws: queryLaws,
        inputPartitionId: "search-similar-anchors.anchor-id",
        outputPartitionId: "search-similar-anchors.shared-vocabulary",
        coverageTargetId: "search-similar-anchors.anchor-lookup",
        transformId: "search-similar-anchors.fixture-anchor-corpus",
        filterId: "search-similar-anchors.anchor-exists",
      }),
      "get-anchor": operationGuidance(getAnchorOperation, {
        laws: queryLaws,
        inputPartitionId: "get-anchor.anchor-id",
        outputPartitionId: "get-anchor.found-anchor",
        coverageTargetId: "get-anchor.anchor-lookup",
        transformId: "get-anchor.existing-and-missing-anchor",
        filterId: "get-anchor.fixture-anchor-or-missing",
      }),
      "fixture-client-query": operationGuidance(fixtureClientQueryOperation, {
        laws: queryLaws,
        inputPartitionId: "fixture-client-query.fixture-anchors",
        outputPartitionId: "fixture-client-query.deterministic-ranking",
        coverageTargetId: "fixture-client-query.search-result",
        transformId: "fixture-client-query.anchor-corpus",
      }),
      "normalize-raw-hits": operationGuidance(normalizeRawHitsOperation, {
        laws: codecLaws,
        inputPartitionId: "normalize-raw-hits.raw-hit-variants",
        outputPartitionId: "normalize-raw-hits.normalized-anchor-cards",
        coverageTargetId: "normalize-raw-hits.normalized-anchors",
        transformId: "normalize-raw-hits.score-location-vocabulary",
      }),
      "decode-mcp-search-result": operationGuidance(decodeMcpSearchResultOperation, {
        laws: codecLaws,
        inputPartitionId: "decode-mcp-search-result.result-variants",
        outputPartitionId: "decode-mcp-search-result.typed-result",
        coverageTargetId: "decode-mcp-search-result.decode-fallbacks",
        transformId: "decode-mcp-search-result.structured-content",
      }),
      "repository-session": operationGuidance(repositorySessionOperation, {
        laws: commandLaws,
        inputPartitionId: "repository-session.session-request",
        outputPartitionId: "repository-session.tool-status-ready",
        coverageTargetId: "repository-session.repository-tool-status",
        transformId: "repository-session.fixture-lifecycle",
      }),
      "repository-intelligence-query": operationGuidance(
        repositoryIntelligenceQueryOperation,
        {
          laws: queryLaws,
          inputPartitionId: "repository-intelligence-query.query",
          outputPartitionId: "repository-intelligence-query.anchors-and-status",
          coverageTargetId: "repository-intelligence-query.search-result",
          transformId: "repository-intelligence-query.fixture-query-corpus",
        },
      ),
      "repository-tool-status-view": operationGuidance(
        repositoryToolStatusViewOperation,
        {
          laws: queryLaws,
          inputPartitionId: "repository-tool-status-view.include-stopped",
          outputPartitionId: "repository-tool-status-view.status-phases",
          coverageTargetId: "repository-tool-status-view.repository-status",
          transformId: "repository-tool-status-view.phase-coverage",
        },
      ),
      "command-lifecycle": operationGuidance(commandLifecycleOperation, {
        laws: commandLaws,
        inputPartitionId: "command-lifecycle.command-envelope",
        outputPartitionId: "command-lifecycle.decoded-subprocess-json",
        coverageTargetId: "command-lifecycle.subprocess-boundary",
        transformId: "command-lifecycle.operation-envelope",
      }),
      "mcp-lifecycle": operationGuidance(mcpLifecycleOperation, {
        laws: commandLaws,
        inputPartitionId: "mcp-lifecycle.session-config",
        outputPartitionId: "mcp-lifecycle.ready-status",
        coverageTargetId: "mcp-lifecycle.mcp-stdio-boundary",
        transformId: "mcp-lifecycle.repo-path-config",
      }),
      "emit-mcp-schema": operationGuidance(emitMcpSchemaOperation, {
        laws: generatorLaws,
        inputPartitionId: "emit-mcp-schema.stage",
        outputPartitionId: "emit-mcp-schema.generated-schema-file",
        coverageTargetId: "emit-mcp-schema.snapshot-fallback",
        transformId: "emit-mcp-schema.stage-selection",
      }),
      "sync-mcp-tool-registry": operationGuidance(syncMcpToolRegistryOperation, {
        laws: generatorLaws,
        inputPartitionId: "sync-mcp-tool-registry.registry-path",
        outputPartitionId: "sync-mcp-tool-registry.search-tool",
        coverageTargetId: "sync-mcp-tool-registry.registry-artifact",
        transformId: "sync-mcp-tool-registry.tool-name-selection",
      }),
    },
  } as const)
  type PackageTypeGuidance = typeof PackageTypeGuidance

  type OperationWithGuidance = {
    readonly id: string
    readonly kind: string
    readonly input: unknown
    readonly output: unknown
    readonly error?: unknown
    readonly views?: {
      readonly reactivityKeys?: readonly string[]
      readonly atoms?: readonly string[]
    }
    readonly laws: readonly string[]
  }

  type GuidanceOptions<Laws extends readonly string[]> = {
    readonly laws: Laws
    readonly inputPartitionId: string
    readonly outputPartitionId: string
    readonly coverageTargetId: string
    readonly transformId: string
    readonly filterId?: string
  }

  function propertyFor<const Operation extends OperationWithGuidance>(
    operation: Operation,
  ) {
    return {
      property: {
        operationId: operation.id,
        kind: operation.kind,
        laws: operation.laws,
        checks: [
          "schema.decode",
          "schema.encode",
          "handler.exact-operation-map",
          "view.atom-moves",
        ],
      },
    } as const
  }

  function operationGuidance<
    const Laws extends readonly string[],
    const Operation extends Omit<OperationWithGuidance, "laws"> & {
      readonly laws: Laws
    },
  >(
    operation: Operation,
    options: GuidanceOptions<Laws>,
  ) {
    const inputSchemaId = `schema:${operation.id}:input`
    const outputSchemaId = `schema:${operation.id}:output`
    const errorSchemaId = `schema:${operation.id}:error`

    return {
      sourceLabels: [
        `operation.kind.${operation.kind}`,
        "effect-schema.ast",
        "package-view.graph",
      ],
      sources: [
        {
          id: `operation:${operation.id}`,
          label: operation.id,
          kind: "contract-operation",
          operationId: operation.id,
        },
      ],
      schemaSources: [
        {
          id: inputSchemaId,
          role: "input",
          label: `${operation.id}.input`,
          source: "effect-schema",
        },
        {
          id: outputSchemaId,
          role: "output",
          label: `${operation.id}.output`,
          source: "effect-schema",
        },
        {
          id: errorSchemaId,
          role: "error",
          label: `${operation.id}.error`,
          source: "effect-schema",
        },
      ],
      inputPartitions: [
        {
          id: options.inputPartitionId,
          kind: "schema-boundary",
          from: "schema.input",
          sourceId: inputSchemaId,
          transformIds: [options.transformId],
          ...(options.filterId ? { filterIds: [options.filterId] } : {}),
        },
      ],
      outputPartitions: [
        {
          id: options.outputPartitionId,
          kind: "output-variant",
          from: "schema.output",
          sourceId: outputSchemaId,
        },
      ],
      errorPartitions: [
        {
          id: `${operation.id}.typed-error`,
          kind: "typed-error-variant",
          from: "schema.error",
          sourceId: errorSchemaId,
        },
      ],
      lawPartitions: lawPartitions(options.laws),
      viewPartitions: [
        ...viewPartitions(
          operation.id,
          "reactivity-key",
          operation.views?.reactivityKeys ?? [],
        ),
        ...viewPartitions(operation.id, "atom", operation.views?.atoms ?? []),
      ],
      coverageSearch: [
        {
          id: `coverage:${operation.id}:${options.coverageTargetId}`,
          targetPartitionId: options.coverageTargetId,
          tier: "commit",
          required: true,
          priority: 10,
          reason:
            "Generated semantic-recall property evidence should move the declared package view graph.",
        },
      ],
      transforms: [
        {
          id: options.transformId,
          kind: "coverage-bias",
          targetPartitionId: options.coverageTargetId,
          sourceLabel: "effect-schema.arbitrary",
          reason:
            "Bias Schema-derived values toward missing package view movement and codec branches.",
        },
      ],
      filters: options.filterId
        ? [
            {
              id: options.filterId,
              kind: "operation-precondition",
              reason:
                "Fixture-only precondition until generated corpus replay can construct both successful and expected-error branches.",
              targetPartitionId: options.inputPartitionId,
              expectedAcceptanceRate: 0.8,
            },
          ]
        : [],
    } as const
  }

  function lawPartitions<const Laws extends readonly string[]>(laws: Laws) {
    return laws.map((id) => ({
      id,
      kind: "law" as const,
      from: "inferred-law",
    })) as readonly {
      readonly id: Laws[number]
      readonly kind: "law"
      readonly from: "inferred-law"
    }[]
  }

  function viewPartitions<
    const Kind extends "reactivity-key" | "atom",
    const Ids extends readonly string[],
  >(operationId: string, kind: Kind, ids: Ids) {
    return ids.map((id) => ({
      id: `${id}.moves`,
      kind,
      from: `touches.${kind}`,
      sourceId: `operation:${operationId}`,
    })) as readonly {
      readonly id: `${Ids[number]}.moves`
      readonly kind: Kind
      readonly from: `touches.${Kind}`
      readonly sourceId: `operation:${string}`
    }[]
  }

  return {
    PackageFuzzHandlers,
    PackageProperties,
    PackageTypeGuidance,
  } as const
}
