import { access, readFile } from "node:fs/promises";
import * as Path from "node:path";

import type { RepositoryArea, RepositoryMap } from "./model.ts";
import { paths } from "./paths.ts";

const exists = async (path: string): Promise<boolean> => {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
};

const packageDescription = async (
  path: string,
  fallback: string,
): Promise<string> => {
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as {
      readonly description?: string;
      readonly project?: { readonly description?: string };
    };
    return parsed.description ?? parsed.project?.description ?? fallback;
  } catch {
    const source = await readFile(path, "utf8").catch(() => "");
    return source.match(/^description\s*=\s*"([^"]+)"/mu)?.[1] ?? fallback;
  }
};

export const collectRepositoryMap = async (options: {
  readonly revision: string;
  readonly sourceRef: string;
  readonly repositoryUrl: string;
}): Promise<RepositoryMap> => {
  const sourceUrl = (path: string) =>
    `${options.repositoryUrl}/tree/${options.sourceRef}/${path}`;
  const candidates: readonly (RepositoryArea & {
    readonly marker: string;
  })[] = [
    {
      id: "effect-joern",
      name: "joern-effect",
      path: "packages/effect-joern",
      marker: "packages/effect-joern/package.json",
      role: await packageDescription(
        Path.join(paths.repository, "packages/effect-joern/package.json"),
        "Typed Effect bindings and a generated TypeScript query DSL for Joern.",
      ),
      details:
        "Owns typed CPG queries, Joern process scope, transport, and result decoding. It stays platform-neutral; the MCP application supplies the Node runtime.",
      connectsTo: ["attune-mcp", "nix"],
      sourceUrl: sourceUrl("packages/effect-joern"),
    },
    {
      id: "attune-mcp",
      name: "attune-mcp",
      path: "packages/attune-mcp",
      marker: "packages/attune-mcp/package.json",
      role: await packageDescription(
        Path.join(paths.repository, "packages/attune-mcp/package.json"),
        "Local stdio MCP suite for reproducible Attune investigations.",
      ),
      details:
        "Owns the investigation lifecycle, eight typed tool contracts, idempotent receipts, artifacts, cancellation, and the local stdio adapter.",
      connectsTo: ["effect-joern", "contracts", "activegraph", "nix", "docs"],
      sourceUrl: sourceUrl("packages/attune-mcp"),
    },
    {
      id: "activegraph",
      name: "ActiveGraph bridge",
      path: "python/attune-activegraph",
      marker: "python/attune-activegraph/pyproject.toml",
      role: await packageDescription(
        Path.join(paths.repository, "python/attune-activegraph/pyproject.toml"),
        "Typed ActiveGraph bridge for the Attune Effect MCP service.",
      ),
      details:
        "Projects the Effect-owned contract into Python and records durable, traceable research and documentation runs without redefining investigation semantics.",
      connectsTo: ["attune-mcp", "contracts", "docs"],
      sourceUrl: sourceUrl("python/attune-activegraph"),
    },
    {
      id: "contracts",
      name: "Generated contracts",
      path: "contracts",
      marker: "contracts/attune-tools.schema.json",
      role: "Versioned JSON Schema and digest generated from Effect Schema.",
      details:
        "The schema is the language boundary between the TypeScript MCP service and the Python ActiveGraph projection. Drift checks compare exact generated bytes.",
      connectsTo: ["attune-mcp", "activegraph"],
      sourceUrl: sourceUrl("contracts"),
    },
    {
      id: "nix",
      name: "Nix workspace",
      path: "nix",
      marker: "flake.nix",
      role: "Pinned executable environment for Attune investigations.",
      details:
        "Pins Node, AgentFS, Joern, Maude, ast-grep, Git, and package builds so the typed contract describes the executable reality.",
      connectsTo: ["effect-joern", "attune-mcp", "activegraph"],
      sourceUrl: sourceUrl("nix"),
    },
    {
      id: "openspec",
      name: "OpenSpec changes",
      path: "openspec",
      marker: "openspec/config.yaml",
      role: "Reviewable requirements, design decisions, and implementation tasks.",
      details:
        "Changes preserve the reasoning behind lifecycle, contract, documentation, and provenance work before those decisions become code.",
      connectsTo: ["attune-mcp", "activegraph", "docs"],
      sourceUrl: sourceUrl("openspec"),
    },
    {
      id: "docs",
      name: "Documentation compiler",
      path: "packages/attune-docs",
      marker: "packages/attune-docs/package.json",
      role: "Deterministic API reference and evidence-grounded onboarding site.",
      details:
        "Extracts the supported MCP exports with TypeScript, validates narrative evidence, and emits the static GitHub Pages artifact you are reading.",
      connectsTo: ["attune-mcp", "activegraph", "openspec"],
      sourceUrl: sourceUrl("packages/attune-docs"),
    },
  ];

  const areas: RepositoryArea[] = [];
  for (const candidate of candidates) {
    if (await exists(Path.join(paths.repository, candidate.marker))) {
      const { marker: _, ...area } = candidate;
      areas.push(area);
    }
  }
  return { revision: options.revision, areas };
};
