import { Effect, Schema } from "effect"
import { describe, expect, it } from "vitest"
import {
  MeasurementBaselineSessionSelectionPayloadSchema,
  MeasurementAgentMetricsSummaryPayloadSchema,
  MeasurementAgentToolUsageSummaryPayloadSchema,
  MeasurementBenchmarkArmLifecyclePayloadSchema,
  MeasurementBenchmarkPacketApplyPayloadSchema,
  MeasurementBenchmarkPacketFixPreviewPayloadSchema,
  MeasurementBenchmarkPacketLifecyclePayloadSchema,
  MeasurementBenchmarkPacketQueuePayloadSchema,
  MeasurementBenchmarkPacketValidationPayloadSchema,
  MeasurementBenchmarkFinalJudgePayloadSchema,
  MeasurementBenchmarkHoldoutEvaluationPayloadSchema,
  MeasurementBenchmarkLoopLifecyclePayloadSchema,
  MeasurementBenchmarkPlanSummaryPayloadSchema,
  MeasurementBenchmarkRegistrationPayloadSchema,
  MeasurementBenchmarkReportProjectionPayloadSchema,
  MeasurementBenchmarkRunLifecyclePayloadSchema,
  MeasurementBenchmarkScorecardPayloadSchema,
  MeasurementBenchmarkTargetPacketPayloadSchema,
  MeasurementBenchmarkTargetStatusPayloadSchema,
  MeasurementCommandObservationPayloadSchema,
  MeasurementCodexClusterTelemetryPayloadSchema,
  MeasurementCodexThreadTelemetryPayloadSchema,
  MeasurementEditAttemptSummaryPayloadSchema,
  MeasurementHarnessProofPayloadSchema,
  MeasurementLifecycleHealthPayloadSchema,
  MeasurementLegacySubstrateAuditPayloadSchema,
  MeasurementMigrationReadinessSummaryPayloadSchema,
  MeasurementMicroExperimentSummaryPayloadSchema,
  MeasurementObservationRecipe,
  MeasurementRecipeSpineCoveragePayloadSchema,
  MeasurementReportProjectionPayloadSchema,
  MeasurementTraceInventorySummaryPayloadSchema,
  createMeasurementObservation,
  createMeasurementObservationSink,
  measurementStoreConfigFromEnv,
  recordMeasurementObservation,
} from "../src/index.js"

const privacy = {
  rawPromptsStored: false,
  rawConversationStored: false,
  rawTraceRowsStored: false,
  fullCommandOutputStored: false,
} as const

const outputSummary = {
  text: "ok",
  byteLength: 2,
  lineCount: 1,
  truncated: false,
  sha256: "2689367b205c16ce836ea2af1ca243e63d45fc130b5a7abcb825aafa821d4a4e",
  redacted: false,
} as const

const commandObservationCapability = "commandObservation" as const
const safeAutofixRisk = "safe" as const

const historicalSession = {
  sessionId: "sha256:baseline-session",
  score: 117,
  scoreReasons: ["matched command signal: trellis-ls", "enough samples: 3 command events"],
  startedAt: "2026-06-28T00:00:00.000Z",
  completedAt: "2026-06-28T00:00:30.000Z",
  wallTimeMs: 30_000,
  commandEvents: 3,
  uniqueCommandFamilies: 2,
  repeatedCommandFamilies: 1,
  repeatedCommandInvocations: 2,
  exitCodeEvents: 3,
  failedCommands: 1,
  successfulCommands: 2,
  commandSuccessRate: 2 / 3,
  expensiveChecks: 2,
  workspacePolicyFastCount: 0,
  timeToFirstUsefulDiagnosticMs: 5_000,
  durationMs: {
    count: 3,
    total: 90,
    min: 20,
    max: 40,
    average: 30,
    p50: 30,
    p95: 40,
  },
  tokenTotal: 42,
  toolCalls: 4,
  modelIds: [{ value: "gpt-5", count: 1 }],
  commandFamilies: [
    { value: "nx run framework-language-service:test", count: 2 },
    { value: "trellis-ls diagnostics", count: 1 },
  ],
  exitCodes: [{ value: "0", count: 2 }, { value: "1", count: 1 }],
  matchedSignals: ["trellis-ls", "framework-language-service"],
  hasAttuneTrellisSignal: true,
  hasEnoughSamples: true,
  giantCatchallPenalty: false,
  privacy,
} as const

describe("MeasurementObservation payload schemas", () => {
  it("decodes the item 3.3 measurement payload shapes", () => {
    expect(Schema.decodeUnknownSync(MeasurementHarnessProofPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      passed: true,
      runtime: {
        flakeProvided: true,
        runtimeKind: "upstream-opencode",
        upstreamIntegrated: true,
      },
      plugins: [{
        name: "@attune/tend-opencode",
        loaded: true,
        capability: commandObservationCapability,
      }],
      upstream: {
        available: true,
        command: ["tend-opencode", "fingerprint", "--format", "json"],
      },
      pluginHookExercise: {
        passed: true,
        skipped: false,
        durationMs: 10,
      },
      leakageCheck: {
        rawPromptPresent: false,
        rawConversationPresent: false,
      },
      privacy,
    }).passed).toBe(true)

    expect(Schema.decodeUnknownSync(MeasurementCommandObservationPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      command: "pnpm exec nx run framework-runtime:typecheck --output-style=static",
      argv: ["pnpm", "exec", "nx", "run", "framework-runtime:typecheck", "--output-style=static"],
      cwd: "/workspace/attune",
      startedAt: "2026-06-28T00:00:00.000Z",
      completedAt: "2026-06-28T00:00:01.000Z",
      durationMs: 1000,
      exitCode: 0,
      status: "succeeded",
      stdoutSummary: outputSummary,
      stderrSummary: outputSummary,
      measurementPhase: "treatment",
      knownNxTarget: "framework-runtime:typecheck",
      targetId: "framework-runtime:typecheck",
      inferredRecipeId: "framework-runtime.local-timescaledb",
      tokenTotal: 42,
      toolCalls: 3,
      tokenMetricSource: "stdout-json",
      rawOutputStored: false,
    }).tokenTotal).toBe(42)

    expect(Schema.decodeUnknownSync(MeasurementTraceInventorySummaryPayloadSchema)({
      measurementSessionId: "measurement:test",
      scannedAt: "2026-06-28T00:00:02.000Z",
      codexHome: "/home/becker/.codex",
      traceFiles: 2,
      sqliteFiles: 1,
      jsonlFiles: 1,
      skippedFiles: 0,
      sqliteSchemaFilesInspected: 1,
      sqliteSchemaFilesSkipped: 0,
      sqliteSchemas: [{
        fileId: "sha256:sqlite-file",
        fileKind: "sqlite",
        inspected: true,
        tableCount: 1,
        tables: [{
          tableName: "sessions",
          allowlistedColumns: ["session_id", "model_id", "created_at"],
          skippedColumnCount: 2,
        }],
      }],
      commandEventCount: 2,
      uniqueCommandFamilies: 1,
      repeatedCommandFamilyCount: 1,
      repeatedCommandInvocationCount: 2,
      exitCodeEventCount: 2,
      failedExitCodeCount: 1,
      timestampRange: {
        count: 2,
        earliest: "2026-06-28T00:00:00.000Z",
        latest: "2026-06-28T00:00:01.000Z",
        spanMs: 1000,
      },
      durationMs: {
        count: 2,
        total: 30,
        min: 10,
        max: 20,
        average: 15,
        p50: 10,
        p95: 20,
      },
      commandFamilies: [{ value: "nx", count: 2 }],
      repeatedCommandPatterns: [{ value: "framework-runtime:typecheck", count: 2 }],
      exitCodes: [{ value: "0", count: 2 }],
      comparableSessionCandidates: [historicalSession],
      selectedBaselineSession: historicalSession,
      toolCalls: 3,
      tokenTotal: 42,
      modelIds: [{ value: "gpt-5", count: 1 }],
      sessionIds: [{ value: "session-1", count: 1 }],
      privacy,
    }).traceFiles).toBe(2)

    expect(Schema.decodeUnknownSync(MeasurementAgentMetricsSummaryPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      measurementPhase: "treatment",
      capturedAt: "2026-06-28T00:00:02.250Z",
      source: "codex-trace-window-v1",
      tokenTotal: 1234,
      toolCalls: 5,
      sampleCount: 7,
      traceFilesScanned: 2,
      windowCount: 3,
      startedAt: "2026-06-28T00:00:00.000Z",
      completedAt: "2026-06-28T00:00:30.000Z",
      tokenMetricSource: "trace-jsonl-window:cumulative-delta+tool-call-count",
      privacy,
    }).tokenTotal).toBe(1234)

    expect(Schema.decodeUnknownSync(MeasurementRecipeSpineCoveragePayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      capturedAt: "2026-06-28T00:00:02.300Z",
      recipeCount: 4,
      edgeCount: 3,
      ioCount: 5,
      runCount: 6,
      receiptCount: 7,
      observationCount: 8,
      diagnosticCount: 2,
      repairCount: 1,
      healthCount: 4,
      frameworkSchemasPreserved: true,
      observationStore: "framework_event.recipe_observation",
      privacy,
    }).observationCount).toBe(8)

    expect(Schema.decodeUnknownSync(MeasurementEditAttemptSummaryPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      capturedAt: "2026-06-28T00:00:02.350Z",
      dirtyPathCount: 3,
      sourceEditCount: 2,
      reportExportEditCount: 1,
      generatedPrivateLedgerEditAttempts: 0,
      generatedPrivateLedgerPathClasses: [],
      privacy,
    }).generatedPrivateLedgerEditAttempts).toBe(0)

    expect(Schema.decodeUnknownSync(MeasurementLegacySubstrateAuditPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      capturedAt: "2026-06-28T00:00:02.400Z",
      scannedPathCount: 42,
      historicalReferenceCount: 8,
      enforcementReferenceCount: 6,
      testFixtureReferenceCount: 5,
      measurementInventoryReferenceCount: 2,
      blockingLiveReferenceCount: 0,
      privacy,
    }).blockingLiveReferenceCount).toBe(0)

    expect(Schema.decodeUnknownSync(MeasurementBaselineSessionSelectionPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      selectedAt: "2026-06-28T00:00:02.500Z",
      selectedSessionId: historicalSession.sessionId,
      score: historicalSession.score,
      scoreReasons: historicalSession.scoreReasons,
      candidateCount: 1,
      selectionMethod: "safe-session-comparability-score-v1",
      selectedSession: historicalSession,
      privacy,
    }).selectedSessionId).toBe(historicalSession.sessionId)

    expect(Schema.decodeUnknownSync(MeasurementMicroExperimentSummaryPayloadSchema)({
      measurementSessionId: "measurement:test",
      summarizedAt: "2026-06-28T00:00:03.000Z",
      task: "Analyze packages/trellis/language-service migration readiness",
      baseline: {
        mode: "baseline",
        fileReads: 12,
        shellCommands: 4,
        repeatedCommands: 1,
        failedCommands: 0,
        expensiveChecks: 1,
        successfulCommands: 4,
        knownExitCodeCommands: 4,
        commandSuccessRate: 1,
        durationSampleCount: 2,
        durationAverageMs: 50,
        uniqueCommandFamilies: 3,
      },
      selectedBaselineSession: historicalSession,
      selectedBaseline: {
        mode: "baseline",
        fileReads: 0,
        shellCommands: 3,
        repeatedCommands: 2,
        failedCommands: 1,
        expensiveChecks: 2,
        tokenTotal: 42,
        toolCalls: 4,
        durationP50Ms: 30,
        durationP95Ms: 40,
      },
      treatment: {
        mode: "treatment",
        fileReads: 7,
        shellCommands: 3,
        repeatedCommands: 0,
        failedCommands: 0,
        expensiveChecks: 1,
        successfulCommands: 3,
        knownExitCodeCommands: 3,
        commandSuccessRate: 1,
        durationSampleCount: 3,
        durationAverageMs: 25,
        storeEmittedCommands: 3,
        uniqueTargets: 2,
        uniqueRecipes: 2,
        trellisDiagnosticObservations: 1,
      },
      comparison: {
        shellCommandDelta: -1,
        repeatedCommandDelta: -1,
        durationAverageDeltaMs: -25,
        commandSuccessRateDelta: 0,
      },
      selectedBaselineComparison: {
        shellCommandDelta: 0,
        repeatedCommandDelta: -2,
        failedCommandDelta: -1,
        tokenDelta: -42,
      },
      findingQualityMatrix: [{
        finding: "trellis-ls as migration machine",
        baseline: "partial",
        treatment: "hit",
        evidence: "treatment diagnostics include recipe-only source profile.",
      }],
      recommendation: {
        proceedToRecipeOnlyMigration: false,
        summary: "Need more diagnostic coverage first.",
        evidenceGaps: ["missing treatment diagnostics"],
      },
      privacy,
    }).recommendation?.proceedToRecipeOnlyMigration).toBe(false)

    expect(Schema.decodeUnknownSync(MeasurementMigrationReadinessSummaryPayloadSchema)({
      schemaVersion: 1,
      measurementSessionId: "measurement:test",
      summarizedAt: "2026-06-28T00:00:03.500Z",
      proceedToRecipeOnlyMigration: false,
      gates: [{
        gate: "phase-token-tool-metrics",
        status: "blocked",
        evidence: "treatment token/tool metrics are missing",
        followUp: "Record phase-level agent metrics.",
      }],
      privacy,
    }).gates[0]?.gate).toBe("phase-token-tool-metrics")

    expect(Schema.decodeUnknownSync(MeasurementLifecycleHealthPayloadSchema)({
      measurementSessionId: "measurement:test",
      checkedAt: "2026-06-28T00:00:04.000Z",
      source: "framework-runtime.local-timescaledb",
      lifecycleOwner: "framework-runtime",
      service: {
        dataDir: ".attune/state/local-timescaledb",
        databaseUrl: "ATTUNE_RECIPE_STORE_URL",
        port: 54329,
        storeMode: "local-postgres",
        ready: true,
      },
      migration: {
        path: "packages/trellis/runtime/sql/0001_framework_recipe_receipt_spine.sql",
        applied: true,
      },
      schemaState: {
        frameworkCore: true,
        frameworkEvent: true,
        frameworkView: true,
      },
      sqlValidation: {
        valid: true,
        statementCount: 8,
      },
      lastLifecycleAction: "check",
    }).service.ready).toBe(true)

    expect(Schema.decodeUnknownSync(MeasurementReportProjectionPayloadSchema)({
      reportPath: "reports/tend-opencode-codex-measurement/tend-opencode-measurement-report.md",
      measurementSessionId: "measurement:test",
      inputObservationIds: ["observation-1"],
      generatedAt: "2026-06-28T00:00:05.000Z",
      privacy,
    }).inputObservationIds).toEqual(["observation-1"])
  })

  it("decodes recipe-only benchmark payload shapes", () => {
    const worktree = {
      arm: "treatment",
      armId: "treatment",
      path: ".attune/state/benchmarks/run/worktrees/treatment",
      branch: "benchmark/run/treatment",
      baseCommit: "abc123",
      startingHead: "abc123",
      endingHead: "def456",
      sourceStateFingerprint: "source-fingerprint-1",
      worktreeFingerprint: "worktree-fingerprint-1",
      dependencyLockHash: "lock-hash-1",
      packetInventoryHash: "packet-inventory-hash-1",
      allowedSourceScopeHash: "allowed-source-scope-hash-1",
      pairedStateStatus: "passed",
      pairedStateBlockers: [],
    } as const
    const patchSummary = {
      applyPatchCalls: 2,
      changedFiles: 4,
      addedFiles: 1,
      modifiedFiles: 3,
      deletedFiles: 0,
      rawDiffStored: false,
      patchTextStored: false,
    } as const
    const validationLadder = [{
      tier: "cheap",
      command: "pnpm exec trellis-ls check --workspace . --profile effect-autofix-safe --packet-id packet-1 --format json",
      targetId: "framework-language-service:check",
      required: true,
      status: "passed",
    }, {
      tier: "focused",
      command: "pnpm exec nx run framework-language-service:test --output-style=static",
      targetId: "framework-language-service:test",
      required: true,
      status: "pending",
    }] as const
    const packet = {
      packetId: "packet-1",
      profile: "effect-autofix-safe",
      ruleName: "effectSucceedWithVoid",
      source: "effect",
      diagnosticCount: 12,
      safeFixCount: 12,
      reviewRequiredFixCount: 0,
      affectedFileCount: 3,
      affectedPackageCount: 2,
      risk: safeAutofixRisk,
      rank: 1,
      rankingInputs: {
        diagnosticCount: 12,
        safeFixCount: 12,
        affectedFileCount: 3,
        affectedPackageCount: 2,
        validationCost: 2,
        riskScore: 0,
        objectiveBoost: 4,
      },
      validationLadder,
      context: {
        summary: "Replace Effect.succeed(undefined) with Effect.void in focused files.",
        representativeFiles: [
          "packages/trellis/language-service/src/example.ts",
        ],
        representativeCodes: ["effect/effectSucceedWithVoid"],
        rawSourceStored: false,
        rawOutputStored: false,
        rawDiagnosticTextStored: false,
      },
    } as const
    const exactTarget = {
      targetId: "target-exact-1",
      evaluatorId: "trellis-ls:hidden:evaluator",
      profile: "effect-full-inventory",
      ruleName: "missingEffectContext",
      diagnosticId: "diag-exact-1",
      sourcePath: "packages/attune/example/src/service.ts",
      stableRangeFingerprint: "range-fingerprint-1",
      sourceScopeMembership: "source-scope",
      sourceScopeReason: "package source file inside allowed migration scope",
      reasoningBurden: "cross-file-effect-migration",
      fixIds: ["fix-1"],
      messageHash: "sha256-message",
      rawSourceStored: false,
      rawDiagnosticTextStored: false,
    } as const

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkRunLifecyclePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test",
      mode: "live",
      action: "started",
      status: "running",
      baseCommit: "abc123",
      baseBranch: "codex/test",
      dirtyFileCount: 3,
      worktreeRoot: ".attune/state/benchmarks/run/worktrees",
      reportsDir: "reports/tend-opencode-codex-measurement",
      cleanupPolicy: "retain",
      startedAt: "2026-06-28T00:00:00.000Z",
      privacy,
    }).status).toBe("running")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkArmLifecyclePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      mode: "live",
      status: "completed",
      worktree,
      startedAt: "2026-06-28T00:00:00.000Z",
      completedAt: "2026-06-28T00:10:00.000Z",
      codexThreadId: "019f10d3-e55c-71e3-92e7-968080ae7dd6",
      promptFile: ".attune/state/benchmarks/run/prompts/treatment.md",
      trellisExposure: true,
      forbiddenCommandFamilies: [],
      budgetUsage: {
        wallTimeMs: 600_000,
        tokenTotal: 1000,
        toolCalls: 12,
        validationCommands: 3,
      },
      worktreePatchSummary: patchSummary,
      privacy,
    }).budgetUsage?.toolCalls).toBe(12)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPlanSummaryPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      capturedAt: "2026-06-28T00:00:01.000Z",
      planFile: ".attune/state/benchmarks/run/prompts/treatment.md",
      score: 5,
      maxScore: 5,
      criteria: [{
        criterion: "openspec-first workflow",
        score: 1,
        maxScore: 1,
        evidence: "Prompt requires OpenSpec planning.",
      }],
      highLevelSummary: "Treatment prompt exposes Trellis LS and starts with OpenSpec.",
      rawPlanStored: false,
      privacy,
    }).rawPlanStored).toBe(false)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkFinalJudgePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      judgedAt: "2026-06-28T00:12:00.000Z",
      command: "pnpm exec trellis-ls diagnostics --workspace . --profile recipe-only-source --format json",
      argv: ["pnpm", "exec", "trellis-ls", "diagnostics"],
      cwd: "/workspace/attune",
      durationMs: 1200,
      exitCode: 0,
      status: "completed",
      baseDiagnosticCount: 456,
      finalDiagnosticCount: 320,
      diagnosticDelta: -136,
      diagnosticsByCode: [{ code: "ts/2304", count: 20 }],
      diagnosticsBySource: [{ value: "typescript", count: 200 }],
      clearedDiagnosticCount: 136,
      remainingDiagnosticCount: 320,
      outputStored: false,
      privacy,
    }).finalDiagnosticCount).toBe(320)

    expect(Schema.decodeUnknownSync(MeasurementCodexThreadTelemetryPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      threadId: "019f10d3-e55c-71e3-92e7-968080ae7dd6",
      role: "primary",
      capturedAt: "2026-06-28T00:13:00.000Z",
      modelIds: [{ value: "gpt-5", count: 1 }],
      sessionIds: [{ value: "019f10d3-e55c-71e3-92e7-968080ae7dd6", count: 1 }],
      tokenTotal: 1000,
      inputTokens: 800,
      outputTokens: 150,
      cachedInputTokens: 200,
      reasoningTokens: 50,
      toolCalls: 12,
      commandFamilies: [{ value: "trellis-ls", count: 2 }],
      validationCommandCount: 4,
      forbiddenTrellisCommandCount: 0,
      patchSummary,
      privacy,
    }).patchSummary.changedFiles).toBe(4)

    expect(Schema.decodeUnknownSync(MeasurementCodexClusterTelemetryPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      rootThreadId: "019f10d3-e55c-71e3-92e7-968080ae7dd6",
      capturedAt: "2026-06-28T00:13:01.000Z",
      threadCount: 2,
      descendantCount: 1,
      maxDepth: 1,
      primaryThreadTokenTotal: 1000,
      subagentTokenTotal: 500,
      connectedClusterTokenTotal: 1500,
      toolCalls: 18,
      validationCommandCount: 5,
      forbiddenTrellisCommandCount: 0,
      patchSummary,
      privacy,
    }).connectedClusterTokenTotal).toBe(1500)

    expect(Schema.decodeUnknownSync(MeasurementAgentToolUsageSummaryPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test:treatment",
      arm: "treatment",
      armId: "treatment",
      capturedAt: "2026-06-28T00:13:02.000Z",
      taxonomy: [{ family: "trellis-ls", calls: 2, failedCalls: 0 }],
      commandFamilies: [{ value: "trellis-ls", count: 2 }],
      validationCommandCount: 2,
      forbiddenTrellisCommandCount: 0,
      privacy,
    }).taxonomy[0]?.family).toBe("trellis-ls")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkScorecardPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test",
      scoredAt: "2026-06-28T00:14:00.000Z",
      winner: "opencode-trellis",
      summary: "OpenCode with Trellis cleared more diagnostics.",
      metrics: [{
        metric: "final diagnostics",
        values: [
          { armId: "opencode-trellis", value: 320 },
          { armId: "codex-trellis", value: 321 },
          { armId: "opencode-blind", value: 400 },
          { armId: "codex-blind", value: 456 },
        ],
        bestValue: 320,
        winner: "opencode-trellis",
        evidence: "Hidden evaluator diagnostic count.",
      }],
      missingMetricReasons: [],
      scorerSelfChecks: [{
        code: "target-item-count",
        status: "passed",
        detail: "Every expected target diagnostic has an exact target item.",
      }],
      aggregateStatistics: {
        medianImprovementMultiple: 12,
        geometricMeanImprovementMultiple: 11,
        worstQuartileImprovementMultiple: 8,
        packetClassCount: 2,
        diagnosticFamilyCount: 2,
      },
      privacy,
    }).winner).toBe("opencode-trellis")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkRegistrationPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-loop:test",
      measurementSessionId: "measurement:effect-packet-loop:test",
      loopId: "effect-packet-loop:test:full-ab",
      loopKind: "full-ab",
      evidenceTier: "promotion-eligible",
      registeredAt: "2026-06-28T00:00:00.000Z",
      packetIds: ["packet-exact-1"],
      holdoutCommitments: ["holdout:commitment-1"],
      diagnosticFamilies: ["missingEffectContext"],
      allowedFiles: ["packages/*/*/src/**/*.ts"],
      excludedScopes: ["packages/trellis/runtime/**"],
      baseline: "codex-raw-effect",
      arms: ["codex-effect-packets", "codex-raw-effect"],
      budgets: {
        wallTimeMs: 600_000,
        tokenTotal: 250_000,
        maxParallelism: 1,
      },
      validationLadder: ["nx run framework-runtime:db:validate-sql"],
      stopRules: ["stop before workspace:policy-fast"],
      negativeControls: ["should-not-change:framework-runtime-db-lifecycle"],
      scoringPolicy: "precision-adjusted-reasoning-bearing-exact-clears-per-all-in-token-v1",
      sourceStateFingerprints: ["source-fingerprint-1", "worktree-fingerprint-1", "packet-inventory-hash-1", "allowed-source-scope-hash-1", "lock-hash-1"],
      allowedSourceScopeHash: "allowed-source-scope-hash-1",
      privacy,
    }).registeredAt).toBe("2026-06-28T00:00:00.000Z")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkHoldoutEvaluationPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-loop:test",
      measurementSessionId: "measurement:effect-packet-loop:test",
      loopId: "effect-packet-loop:test:full-ab",
      loopKind: "full-ab",
      evaluatedAt: "2026-06-28T00:09:00.000Z",
      seed: "holdout-seed",
      selectionPolicy: "seeded-hidden-same-family-commitment-v1",
      commitmentSlots: ["holdout:commitment-1"],
      revealedTargetCommitments: ["holdout-target:target-1"],
      packetId: "holdout-packet-1",
      packetIds: ["packet-hidden-1"],
      sourceSnapshot: "effect-packet-queue-base",
      profile: "effect-full-inventory",
      packetSelectionStrategy: "ranked-safe-effect-packet-queue-v1:holdout",
      targetFamilies: ["missingEffectContext"],
      itemCount: 1,
      sourceScopeItemCount: 1,
      reasoningBearingItemCount: 1,
      baseline: "codex-raw-effect",
      treatment: "codex-effect-packets",
      baselineReasoningBearingClears: 1,
      treatmentReasoningBearingClears: 1,
      baselinePrecisionAdjustedReasoningBearingClears: 1,
      treatmentPrecisionAdjustedReasoningBearingClears: 1,
      baselineAllInTokens: 10_000,
      treatmentAllInTokens: 100,
      improvementMultiple: 100,
      visibleImprovementMultiple: 25,
      status: "confirmed",
      blockers: [],
      diagnosticFamilies: [{ value: "missingEffectContext", count: 1 }],
      reasoningBurdenCounts: [{ value: "cross-file-effect-migration", count: 1 }],
      rawHoldoutTargetsStored: false,
      rawPromptsStored: false,
      rawConversationStored: false,
      rawTraceRowsStored: false,
      fullCommandOutputStored: false,
      rawDiffStored: false,
      patchTextStored: false,
      privacy,
    }).status).toBe("confirmed")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkLoopLifecyclePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-loop:test",
      measurementSessionId: "measurement:effect-packet-loop:test",
      loopId: "effect-packet-loop:test:full-ab",
      loopKind: "full-ab",
      evidenceTier: "promotion-eligible",
      status: "completed",
      hypothesis: "Packet-guided migration improves token efficiency.",
      baseline: "codex-raw-effect",
      packetTargets: ["target-exact-1"],
      arms: ["codex-effect-packets", "codex-raw-effect"],
      budgets: {
        wallTimeMs: 600_000,
        tokenTotal: 250_000,
        maxParallelism: 1,
      },
      validationDepth: "full",
      promptVariant: "compact-full-ab-v1",
      worktreeFingerprint: "worktree-fingerprint-1",
      sourceStateFingerprint: "source-fingerprint-1",
      allowedSourceScopeHash: "allowed-source-scope-hash-1",
      completedAt: "2026-06-28T00:10:00.000Z",
      stopReason: "candidate scored below promotion threshold",
      privacy,
    }).status).toBe("completed")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkTargetPacketPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-loop:test",
      measurementSessionId: "measurement:effect-packet-loop:test",
      packetId: "packet-exact-1",
      profile: "effect-full-inventory",
      packetSelectionStrategy: "ranked-safe-effect-packet-queue-v1",
      sourceSnapshot: "effect-packet-queue-base",
      packetCount: 1,
      targetFamilies: ["missingEffectContext"],
      perFamilyLimit: 10,
      itemCount: 1,
      expectedItemCount: 1,
      ruleCounts: [{ value: "missingEffectContext", count: 1 }],
      fixabilityCounts: [{ value: "manual", count: 1 }],
      riskCounts: [{ value: "review-required", count: 1 }],
      safeFixCount: 0,
      validationCommands: ["nx run framework-language-service:typecheck"],
      familyCounts: [{ value: "missingEffectContext", count: 1 }],
      items: [exactTarget],
      rawMessagesStored: false,
      privacy,
    }).items[0]?.reasoningBurden).toBe("cross-file-effect-migration")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkTargetStatusPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-loop:test",
      measurementSessionId: "measurement:effect-packet-loop:test",
      loopId: "effect-packet-loop:test:full-ab",
      loopKind: "full-ab",
      baseline: "codex-raw-effect",
      treatment: "codex-effect-packets",
      correctedClears: 3,
      tokenTotal: 1000,
      improvementMultiple: 12,
      tenXCheckpointStatus: "candidate",
      twentyXGoalStatus: "not-passed",
      reasoningPacketStatus: "candidate",
      precisionAdjustedStatus: "passed",
      holdoutStatus: "not-run",
      negativeControlStatus: "not-run",
      confidence: "medium",
      blockers: ["seeded hidden holdout not run"],
      recommendedNextLoopKind: "audit",
      metrics: {
        exactClears: 3,
        sourceScopeClears: 3,
        reasoningBearingClears: 1,
        reasoningWeightedClears: 6,
        precisionAdjustedReasoningBearingClears: 1,
        reasoningBearingClearsPerMillionTokens: 1000,
        reasoningWeightedClearsPerMillionTokens: 6000,
        precisionAdjustedReasoningBearingMultiple: 12,
        combinedImprovementMultiple: 12,
        autofixOnlyImprovementMultiple: null,
        holdoutConfirmedImprovementMultiple: null,
        allInTokens: 1000,
        cacheNormalizedTokens: 800,
      },
      crossFamilyConfirmation: {
        status: "passed",
        minimumDiagnosticFamilies: 2,
        minimumPacketClasses: 2,
        resolvedDiagnosticFamilyCount: 2,
        targetDiagnosticFamilyCount: 2,
        packetClassCount: 2,
        blockers: [],
      },
      pairedState: {
        comparableLoop: true,
        status: "passed",
        armCount: 2,
        baseCommit: "abc123",
        sourceStateFingerprint: "source-fingerprint-1",
        worktreeFingerprint: "worktree-fingerprint-1",
        dependencyLockHash: "lock-hash-1",
        packetInventoryHash: "packet-inventory-hash-1",
        allowedSourceScopeHash: "allowed-source-scope-hash-1",
        allowedFiles: ["packages/*/*/src/**/*.ts"],
        excludedScopes: ["packages/trellis/runtime/**"],
        arms: [{
          arm: "codex-effect-packets",
          armId: "codex-effect-packets",
          status: "passed",
          baseCommit: "abc123",
          startingHead: "abc123",
          sourceStateFingerprint: "source-fingerprint-1",
          worktreeFingerprint: "worktree-fingerprint-1",
          dependencyLockHash: "lock-hash-1",
          packetInventoryHash: "packet-inventory-hash-1",
          allowedSourceScopeHash: "allowed-source-scope-hash-1",
          blockers: [],
        }, {
          arm: "codex-raw-effect",
          armId: "codex-raw-effect",
          status: "passed",
          baseCommit: "abc123",
          startingHead: "abc123",
          sourceStateFingerprint: "source-fingerprint-1",
          worktreeFingerprint: "worktree-fingerprint-1",
          dependencyLockHash: "lock-hash-1",
          packetInventoryHash: "packet-inventory-hash-1",
          allowedSourceScopeHash: "allowed-source-scope-hash-1",
          blockers: [],
        }],
        blockers: [],
      },
      legacyMetricCaveats: [{
        code: "hidden-diagnostic-clear-mismatch",
        arm: "codex-effect-packets",
        legacyMetric: "hidden diagnostics cleared",
        legacyValue: 5,
        correctedMetric: "source-scope exact packet clears",
        correctedValue: 3,
        detail: "Hidden full-inventory deltas can include incidental cleanup.",
      }],
      resultBreakdown: {
        visibleImprovementMultiple: 12,
        holdoutImprovementMultiple: null,
        combinedImprovementMultiple: 12,
        autofixOnlyImprovementMultiple: null,
        reasoningBearingImprovementMultiple: 12,
        reasoningWeightedImprovementMultiple: 10,
        precisionAdjustedReasoningBearingMultiple: 12,
        medianImprovementMultiple: 12,
        geometricMeanImprovementMultiple: 11,
        worstQuartileImprovementMultiple: 8,
      },
      evidenceFlags: {
        preRegistered: true,
        paired: true,
        holdoutConfirmed: false,
        negativeControlClean: false,
        allInAccounted: true,
        auditPromoted: false,
      },
      reasoningWork: {
        status: "passed",
        reasoningBearingPacketSet: true,
        strategyLabels: ["cross-file-effect-migration"],
        filesInspectedCount: 2,
        diagnosticsConsideredCount: 1,
        validationFailureCount: 0,
        repairAttempts: 1,
        acceptanceRationaleLabels: ["packet-cleared-by-fastpath-validation"],
        refusalRationaleLabels: [],
        blockers: [],
      },
      scorerSelfChecks: [{
        code: "target-item-count",
        status: "passed",
        detail: "Every expected target diagnostic has an exact target item.",
      }],
      aggregateStatistics: {
        medianImprovementMultiple: 12,
        geometricMeanImprovementMultiple: 11,
        worstQuartileImprovementMultiple: 8,
        packetClassCount: 2,
        diagnosticFamilyCount: 2,
      },
      privacy,
    }).recommendedNextLoopKind).toBe("audit")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPacketQueuePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-ab:test",
      measurementSessionId: "measurement:effect-packet-ab:test",
      selectedAt: "2026-06-28T00:00:00.000Z",
      evaluatorId: "trellis-ls effect packet queue",
      profile: "effect-autofix-safe",
      selectionStrategy: "effect-diagnostic-packet-rank-v1",
      packetCount: 1,
      diagnosticCount: 12,
      safeFixCount: 12,
      ruleCounts: [{ value: "effectSucceedWithVoid", count: 12 }],
      fixabilityCounts: [{ value: "safe", count: 12 }],
      riskCounts: [{ value: "safe", count: 1 }],
      packets: [packet],
      privacy,
    }).packets[0]?.context.rawSourceStored).toBe(false)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPacketLifecyclePayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-ab:test",
      measurementSessionId: "measurement:effect-packet-ab:test:opencode-effect-packets",
      arm: "opencode-effect-packets",
      armId: "opencode-effect-packets",
      packetId: packet.packetId,
      ruleName: packet.ruleName,
      profile: packet.profile,
      status: "running",
      startedAt: "2026-06-28T00:01:00.000Z",
      diagnosticCountBefore: 12,
      privacy,
    }).status).toBe("running")

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPacketFixPreviewPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-ab:test",
      measurementSessionId: "measurement:effect-packet-ab:test:opencode-effect-packets",
      arm: "opencode-effect-packets",
      armId: "opencode-effect-packets",
      packetId: packet.packetId,
      ruleName: packet.ruleName,
      profile: packet.profile,
      previewedAt: "2026-06-28T00:02:00.000Z",
      fixCount: 12,
      safeFixCount: 12,
      reviewRequiredFixCount: 0,
      affectedFileCount: 3,
      rawDiffStored: false,
      patchTextStored: false,
      privacy,
    }).rawDiffStored).toBe(false)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPacketApplyPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-ab:test",
      measurementSessionId: "measurement:effect-packet-ab:test:opencode-effect-packets",
      arm: "opencode-effect-packets",
      armId: "opencode-effect-packets",
      packetId: packet.packetId,
      ruleName: packet.ruleName,
      profile: packet.profile,
      appliedAt: "2026-06-28T00:03:00.000Z",
      mode: "write",
      applied: true,
      refused: false,
      stale: false,
      fixCount: 12,
      safeFixCount: 12,
      affectedFileCount: 3,
      rawDiffStored: false,
      patchTextStored: false,
      privacy,
    }).applied).toBe(true)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkPacketValidationPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "effect-packet-ab:test",
      measurementSessionId: "measurement:effect-packet-ab:test:opencode-effect-packets",
      arm: "opencode-effect-packets",
      armId: "opencode-effect-packets",
      packetId: packet.packetId,
      ruleName: packet.ruleName,
      profile: packet.profile,
      validatedAt: "2026-06-28T00:04:00.000Z",
      status: "cleared",
      validationLadder,
      diagnosticCountBefore: 12,
      diagnosticCountAfter: 0,
      validatedClearedCount: 12,
      remainingCount: 0,
      privacy,
    }).validatedClearedCount).toBe(12)

    expect(Schema.decodeUnknownSync(MeasurementBenchmarkReportProjectionPayloadSchema)({
      schemaVersion: 1,
      benchmarkRunId: "recipe-only-ab:test",
      measurementSessionId: "measurement:recipe-only-ab:test",
      reportPath: "reports/tend-opencode-codex-measurement/recipe-only-worktree-ab-benchmark.md",
      inputObservationIds: ["observation-1"],
      inputQuerySummary: {
        source: "framework-runtime-observation-store",
        observationCount: 1,
        observationKindCounts: [{ value: "measurement.benchmark.target-status.summary", count: 1 }],
        targetStatusObservationCount: 1,
        targetPacketObservationCount: 0,
        scorecardObservationCount: 0,
        holdoutObservationCount: 0,
        auditObservationCount: 0,
        reportInputObservationIdsStored: true,
        rawTraceRowsRead: false,
        rawPromptsRead: false,
        fullCommandOutputRead: false,
        rawDiffsRead: false,
      },
      projectedAt: "2026-06-28T00:15:00.000Z",
      privacy,
    }).inputObservationIds).toEqual(["observation-1"])
  })

  it("rejects raw command output and unsafe privacy summaries", () => {
    expect(() =>
      Schema.decodeUnknownSync(MeasurementCommandObservationPayloadSchema)({
        schemaVersion: 1,
        command: "echo unsafe",
        argv: ["echo", "unsafe"],
        cwd: "/workspace/attune",
        startedAt: "2026-06-28T00:00:00.000Z",
        completedAt: "2026-06-28T00:00:01.000Z",
        durationMs: 1000,
        exitCode: 0,
        status: "succeeded",
        stdoutSummary: outputSummary,
        stderrSummary: outputSummary,
        rawOutputStored: true,
      })
    ).toThrow()

    expect(() =>
      Schema.decodeUnknownSync(MeasurementReportProjectionPayloadSchema)({
        reportPath: "reports/tend-opencode-codex-measurement/report.md",
        measurementSessionId: "measurement:test",
        inputObservationIds: [],
        privacy: {
          ...privacy,
          rawPromptsStored: true,
        },
      })
    ).toThrow()

    expect(() =>
      Schema.decodeUnknownSync(MeasurementCodexThreadTelemetryPayloadSchema)({
        schemaVersion: 1,
        benchmarkRunId: "recipe-only-ab:test",
        measurementSessionId: "measurement:recipe-only-ab:test:control",
        arm: "control",
        armId: "control",
        threadId: "thread-1",
        role: "primary",
        capturedAt: "2026-06-28T00:00:00.000Z",
        modelIds: [],
        sessionIds: [{ value: "thread-1", count: 1 }],
        tokenTotal: 0,
        toolCalls: 0,
        commandFamilies: [],
        validationCommandCount: 0,
        forbiddenTrellisCommandCount: 0,
        patchSummary: {
          applyPatchCalls: 1,
          changedFiles: 1,
          rawDiffStored: true,
          patchTextStored: false,
        },
        privacy,
      })
    ).toThrow()
  })

  it("guards local Postgres target-status projection coverage when configured", async () => {
    if (process.env["ATTUNE_RECIPE_STORE_MODE"] !== "local-postgres") {
      expect(measurementStoreConfigFromEnv().mode).toBeDefined()
      return
    }

    const config = measurementStoreConfigFromEnv()
    const observedAt = "2026-06-29T00:00:00.000Z"
    const benchmarkRunId = "effect-packet-postgres-projection-test"
    const measurementSessionId = `measurement:${benchmarkRunId}`
    const recipe = MeasurementObservationRecipe
    const observation = createMeasurementObservation({
      observationId: "measurement-observation-test:target-status:postgres-projection",
      kind: "measurement.benchmark.target-status.summary",
      recipeId: recipe.id,
      observedAt,
      measurementSessionId,
      payload: {
        schemaVersion: 1,
        benchmarkRunId,
        measurementSessionId,
        loopId: `${benchmarkRunId}:quick-turn`,
        loopKind: "quick-turn",
        baseline: "codex-raw-effect",
        treatment: "codex-effect-packets",
        correctedClears: 0,
        tokenTotal: null,
        improvementMultiple: null,
        tenXCheckpointStatus: "not-measured",
        twentyXGoalStatus: "not-measured",
        reasoningPacketStatus: "not-measured",
        precisionAdjustedStatus: "not-measured",
        holdoutStatus: "not-run",
        negativeControlStatus: "not-run",
        confidence: "low",
        blockers: ["guarded local-postgres projection smoke"],
        recommendedNextLoopKind: "quick-turn",
        metrics: {
          exactClears: 0,
          sourceScopeClears: 0,
          reasoningBearingClears: 0,
          reasoningWeightedClears: 0,
          precisionAdjustedReasoningBearingClears: 0,
          reasoningBearingClearsPerMillionTokens: null,
          reasoningWeightedClearsPerMillionTokens: null,
          precisionAdjustedReasoningBearingMultiple: null,
          combinedImprovementMultiple: null,
          autofixOnlyImprovementMultiple: null,
          holdoutConfirmedImprovementMultiple: null,
          allInTokens: null,
          cacheNormalizedTokens: null,
        },
        crossFamilyConfirmation: {
          status: "not-measured",
          minimumDiagnosticFamilies: 2,
          minimumPacketClasses: 2,
          resolvedDiagnosticFamilyCount: 0,
          targetDiagnosticFamilyCount: 0,
          packetClassCount: 0,
          blockers: ["target packet evaluation missing"],
        },
        pairedState: {
          comparableLoop: false,
          status: "not-applicable",
          armCount: 0,
          baseCommit: "abc123",
          sourceStateFingerprint: "source-fingerprint-1",
          worktreeFingerprint: "worktree-fingerprint-1",
          packetInventoryHash: "packet-inventory-hash-1",
          allowedSourceScopeHash: "allowed-source-scope-hash-1",
          allowedFiles: ["packages/*/*/src/**/*.ts"],
          excludedScopes: ["reports/**"],
          arms: [],
          blockers: [],
        },
        legacyMetricCaveats: [],
        resultBreakdown: {
          visibleImprovementMultiple: null,
          holdoutImprovementMultiple: null,
          combinedImprovementMultiple: null,
          autofixOnlyImprovementMultiple: null,
          reasoningBearingImprovementMultiple: null,
          reasoningWeightedImprovementMultiple: null,
          precisionAdjustedReasoningBearingMultiple: null,
          medianImprovementMultiple: null,
          geometricMeanImprovementMultiple: null,
          worstQuartileImprovementMultiple: null,
        },
        evidenceFlags: {
          preRegistered: true,
          paired: false,
          holdoutConfirmed: false,
          negativeControlClean: false,
          allInAccounted: false,
          auditPromoted: false,
        },
        reasoningWork: {
          status: "not-measured",
          reasoningBearingPacketSet: false,
          strategyLabels: [],
          filesInspectedCount: 0,
          diagnosticsConsideredCount: 0,
          validationFailureCount: 0,
          repairAttempts: 0,
          acceptanceRationaleLabels: [],
          refusalRationaleLabels: [],
          blockers: ["loop has no completed reasoning-bearing packet work evidence"],
        },
        scorerSelfChecks: [],
        aggregateStatistics: {
          packetClassCount: 0,
          diagnosticFamilyCount: 0,
        },
        privacy,
      },
    })

    let sink: Awaited<ReturnType<typeof createMeasurementObservationSink>> | undefined
    try {
      sink = await createMeasurementObservationSink(config)
      if (sink.store === undefined) return
      await Effect.runPromise(sink.store.registerRecipe(recipe))
      await Effect.runPromise(recordMeasurementObservation(sink, observation))
      const snapshot = await Effect.runPromise(sink.store.snapshot())
      const found = snapshot.observations.find((item) =>
        item.observationId === observation.observationId &&
        item.observationKind === "measurement.benchmark.target-status.summary"
      )
      expect(found).toBeDefined()
      expect(Schema.decodeUnknownSync(MeasurementBenchmarkTargetStatusPayloadSchema)(found?.payload).benchmarkRunId)
        .toBe(benchmarkRunId)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      if (/connect|econnrefused|timeout|terminating connection/iu.test(message)) {
        expect(message.length).toBeGreaterThan(0)
        return
      }
      throw error
    } finally {
      await sink?.close()
    }
  })
})
