/* @generated by @attune/nx:attune-repair. Do not edit directly. */
/* Materialized package contract; edit ./attune.package.ts and run Nx repair. */
import { Layer, Schema } from "effect"
import {
  OperationKindSchema,
  PackageKindSchema,
  defineOperation,
  definePackageContract,
  definePackageViews,
  defineTypeGuidance,
  touches,
} from "@attune/framework-protocol"
import { createAttuneGenerated } from "./attune.generated.js"

export { PackageContractSchema } from "@attune/framework-protocol"

/**
 * Generated-shape contract customized for @attune/nx itself.
 * The generator grammar package is intentionally hand-authored, but its public
 * boundary is still auditable through the same package-contract surface that it
 * emits for the rest of the repo.
 */
export const PackageViews = definePackageViews({
  reactivityKeys: [
    "attune-nx.generator-plan.changed",
    "attune-nx.generated-diff.changed",
    "attune-nx.provenance.changed",
    "attune-nx.contract-graph.changed",
    "attune-nx.executor-intent.changed",
  ],
  atoms: [
    "generatorPlanAtom",
    "generatedDiffAtom",
    "provenanceAtom",
    "contractGraphAtom",
    "generatorInventoryAtom",
    "executorIntentAtom",
  ],
} as const)

export const AttuneNxOperationError = Schema.Struct({
  code: Schema.String,
  message: Schema.String,
  path: Schema.optional(Schema.String),
})
export type AttuneNxOperationError = Schema.Schema.Type<typeof AttuneNxOperationError>

export const GeneratedFile = Schema.Struct({
  path: Schema.String,
  kind: Schema.Literals(["source", "barrel", "schema", "ledger", "test", "metadata"] as const),
})
export type GeneratedFile = Schema.Schema.Type<typeof GeneratedFile>

export const GeneratorPlanOutput = Schema.Struct({
  files: Schema.Array(GeneratedFile),
  sourceBomUpdated: Schema.Boolean,
  deterministic: Schema.Boolean,
})
export type GeneratorPlanOutput = Schema.Schema.Type<typeof GeneratorPlanOutput>

export const EffectServiceGeneratorInput = Schema.Struct({
  name: Schema.String,
  directory: Schema.optional(Schema.String),
  export: Schema.optional(Schema.Boolean),
  tag: Schema.optional(Schema.String),
  operationId: Schema.optional(Schema.String),
  operationKind: Schema.optional(OperationKindSchema),
  project: Schema.optional(Schema.String),
})
export type EffectServiceGeneratorInput = Schema.Schema.Type<typeof EffectServiceGeneratorInput>

export const PackageContractGeneratorInput = Schema.Struct({
  packageId: Schema.String,
  packageKind: PackageKindSchema,
  sourceRoot: Schema.optional(Schema.String),
  directory: Schema.optional(Schema.String),
  project: Schema.optional(Schema.String),
  operationId: Schema.optional(Schema.String),
  operationKind: Schema.optional(OperationKindSchema),
  operationName: Schema.optional(Schema.String),
})
export type PackageContractGeneratorInput = Schema.Schema.Type<typeof PackageContractGeneratorInput>

export const AtomViewGeneratorInput = Schema.Struct({
  name: Schema.String,
  packageId: Schema.optional(Schema.String),
  operationId: Schema.optional(Schema.String),
  directory: Schema.optional(Schema.String),
  export: Schema.optional(Schema.Boolean),
  reactivityKey: Schema.optional(Schema.String),
  baseAtomId: Schema.optional(Schema.String),
  derivedAtomId: Schema.optional(Schema.String),
  packageViewAtomId: Schema.optional(Schema.String),
  project: Schema.optional(Schema.String),
})
export type AtomViewGeneratorInput = Schema.Schema.Type<typeof AtomViewGeneratorInput>

export const GeneratorInventoryInput = Schema.Struct({
  includeMissingCapabilities: Schema.optional(Schema.Boolean),
})
export type GeneratorInventoryInput = Schema.Schema.Type<typeof GeneratorInventoryInput>

export const GeneratorInventoryOutput = Schema.Struct({
  entries: Schema.Array(Schema.Struct({
    id: Schema.String,
    publicName: Schema.String,
    kind: Schema.Literals(["scaffold", "sync"] as const),
  })),
  capabilityGaps: Schema.Array(Schema.String),
})
export type GeneratorInventoryOutput = Schema.Schema.Type<typeof GeneratorInventoryOutput>

export const PackageContractGraphInferenceInput = Schema.Struct({
  projectName: Schema.String,
  projectRoot: Schema.String,
  sourceRoot: Schema.optional(Schema.String),
  targetNames: Schema.optional(Schema.Array(Schema.String)),
})
export type PackageContractGraphInferenceInput = Schema.Schema.Type<typeof PackageContractGraphInferenceInput>

export const PackageContractGraphInferenceOutput = Schema.Struct({
  contractPath: Schema.String,
  targetSemantics: Schema.Array(Schema.Struct({
    targetName: Schema.String,
    category: Schema.String,
    cacheable: Schema.Boolean,
  })),
  requiredEvidence: Schema.Array(Schema.String),
})
export type PackageContractGraphInferenceOutput = Schema.Schema.Type<typeof PackageContractGraphInferenceOutput>

export const SourceBomProvenanceUpsertInput = Schema.Struct({
  generatorName: Schema.String,
  owningProject: Schema.String,
  projectRoot: Schema.String,
  sourceShapeKind: Schema.String,
  ownedFiles: Schema.Array(Schema.String),
  openspecChangeId: Schema.optional(Schema.String),
})
export type SourceBomProvenanceUpsertInput = Schema.Schema.Type<typeof SourceBomProvenanceUpsertInput>

export const SourceBomProvenanceUpsertOutput = Schema.Struct({
  shardPath: Schema.String,
  optionsHash: Schema.String,
  updated: Schema.Boolean,
})
export type SourceBomProvenanceUpsertOutput = Schema.Schema.Type<typeof SourceBomProvenanceUpsertOutput>

export const ExecutorIntentNormalizationInput = Schema.Struct({
  executor: Schema.Literals(["attune:package-check", "attune:generated", "attune:toolchain"] as const),
  options: Schema.Unknown,
  projectName: Schema.optional(Schema.String),
  targetName: Schema.optional(Schema.String),
})
export type ExecutorIntentNormalizationInput = Schema.Schema.Type<typeof ExecutorIntentNormalizationInput>

export const ExecutorIntentNormalizationOutput = Schema.Struct({
  accepted: Schema.Boolean,
  executionMode: Schema.Literals(["intent-only"] as const),
  diagnostics: Schema.Array(Schema.String),
})
export type ExecutorIntentNormalizationOutput = Schema.Schema.Type<typeof ExecutorIntentNormalizationOutput>

const generatorLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.virtual-tree-only",
  "generator.options-decode",
  "generator.deterministic-output",
  "generator.provenance-recorded",
  "generator.no-untracked-output",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const queryLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const commandLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "side-effect.declared-boundary",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

const policyRuleLaws = [
  "schema.decode",
  "schema.encode",
  "schema.error-decode",
  "determinism.same-input-same-output",
  "side-effect.readonly",
  "policy.finding-schema",
  "policy.deterministic-findings",
  "policy.stable-diagnostic-ids",
  "view.reactivity-key-moves",
  "view.atom-moves",
] as const

export const generateEffectServiceOperation = defineOperation({
  id: "generate-effect-service",
  name: "Generate Effect Service",
  kind: "generator",
  input: EffectServiceGeneratorInput,
  output: GeneratorPlanOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "attune-nx.generator-plan.changed",
      "attune-nx.generated-diff.changed",
      "attune-nx.provenance.changed",
    ],
    atoms: ["generatorPlanAtom", "generatedDiffAtom", "provenanceAtom"],
  } as const),
  laws: generatorLaws,
  generator: {
    name: "@attune/nx:effect-service",
    project: "attune-nx",
    output: "virtual-tree",
  } as const,
} as const)

export const generatePackageContractOperation = defineOperation({
  id: "generate-package-contract",
  name: "Generate Package Contract",
  kind: "generator",
  input: PackageContractGeneratorInput,
  output: GeneratorPlanOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "attune-nx.generator-plan.changed",
      "attune-nx.generated-diff.changed",
      "attune-nx.provenance.changed",
      "attune-nx.contract-graph.changed",
    ],
    atoms: ["generatorPlanAtom", "generatedDiffAtom", "provenanceAtom", "contractGraphAtom"],
  } as const),
  laws: generatorLaws,
  generator: {
    name: "@attune/nx:package-contract",
    project: "attune-nx",
    output: "virtual-tree",
  } as const,
} as const)

export const generateAtomViewOperation = defineOperation({
  id: "generate-atom-view",
  name: "Generate Atom View",
  kind: "generator",
  input: AtomViewGeneratorInput,
  output: GeneratorPlanOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "attune-nx.generator-plan.changed",
      "attune-nx.generated-diff.changed",
      "attune-nx.provenance.changed",
      "attune-nx.contract-graph.changed",
    ],
    atoms: ["generatorPlanAtom", "generatedDiffAtom", "provenanceAtom", "contractGraphAtom"],
  } as const),
  laws: generatorLaws,
  generator: {
    name: "@attune/nx:atom-view",
    project: "attune-nx",
    output: "virtual-tree",
  } as const,
} as const)

export const queryGeneratorInventoryOperation = defineOperation({
  id: "query-generator-inventory",
  name: "Query Generator Inventory",
  kind: "query",
  input: GeneratorInventoryInput,
  output: GeneratorInventoryOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: ["attune-nx.generator-plan.changed"],
    atoms: ["generatorInventoryAtom"],
  } as const),
  laws: queryLaws,
} as const)

export const inferPackageContractGraphOperation = defineOperation({
  id: "infer-package-contract-graph",
  name: "Infer Package Contract Graph",
  kind: "query",
  input: PackageContractGraphInferenceInput,
  output: PackageContractGraphInferenceOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: ["attune-nx.contract-graph.changed"],
    atoms: ["contractGraphAtom"],
  } as const),
  laws: queryLaws,
} as const)

export const upsertSourceBomProvenanceOperation = defineOperation({
  id: "upsert-source-bom-provenance",
  name: "Upsert Source BOM Provenance",
  kind: "command",
  input: SourceBomProvenanceUpsertInput,
  output: SourceBomProvenanceUpsertOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: [
      "attune-nx.generated-diff.changed",
      "attune-nx.provenance.changed",
    ],
    atoms: ["generatedDiffAtom", "provenanceAtom"],
  } as const),
  laws: commandLaws,
} as const)

export const normalizeExecutorIntentOperation = defineOperation({
  id: "normalize-executor-intent",
  name: "Normalize Executor Intent",
  kind: "policy-rule",
  input: ExecutorIntentNormalizationInput,
  output: ExecutorIntentNormalizationOutput,
  error: AttuneNxOperationError,
  views: touches(PackageViews, {
    reactivityKeys: ["attune-nx.executor-intent.changed"],
    atoms: ["executorIntentAtom"],
  } as const),
  laws: policyRuleLaws,
  policy: {
    findingSchema: "ExecutorIntentNormalizationOutput",
    ruleId: "attune-nx/typed-executor-intent",
  } as const,
} as const)

export const PackageContract = definePackageContract({
  packageId: "attune-nx",
  sourceRoot: "packages/attune-nx",
  packageKind: "generator-tooling",
  views: PackageViews,
  services: [] as const,
  operations: [
    generateEffectServiceOperation,
    generatePackageContractOperation,
    generateAtomViewOperation,
    queryGeneratorInventoryOperation,
    inferPackageContractGraphOperation,
    upsertSourceBomProvenanceOperation,
    normalizeExecutorIntentOperation,
  ] as const,
  provenance: {
    generator: "@attune/nx:package-contract",
    customizedFor: "attune-nx generator grammar",
    openspecChangeId: "standardize-effect-package-contracts",
  } as const,
  waivers: [] as const,
} as const)
export type PackageContract = typeof PackageContract

export const PackageLayer = {
  layer: Layer.empty,
  provides: [] as const,
  requires: [] as const,
  metadata: {
    packageId: "attune-nx",
    role: "generator-tooling-runtime",
  },
} as const
export type PackageLayer = typeof PackageLayer

export const PackageTestLayer = {
  layer: Layer.empty,
  provides: [] as const,
  requires: [] as const,
  metadata: {
    packageId: "attune-nx",
    role: "generator-tooling-test-runtime",
  },
} as const
export type PackageTestLayer = typeof PackageTestLayer

const PackageGenerated = createAttuneGenerated({
  PackageContract,
  commandLaws,
  generateAtomViewOperation,
  generateEffectServiceOperation,
  generatePackageContractOperation,
  generatorLaws,
  GeneratorPlanOutput,
  inferPackageContractGraphOperation,
  normalizeExecutorIntentOperation,
  policyRuleLaws,
  queryGeneratorInventoryOperation,
  queryLaws,
  upsertSourceBomProvenanceOperation,
} as const)
export const PackageFuzzHandlers = PackageGenerated.PackageFuzzHandlers
export const PackageProperties = PackageGenerated.PackageProperties
export const PackageTypeGuidance = PackageGenerated.PackageTypeGuidance
export type PackageFuzzHandlers = typeof PackageFuzzHandlers
export type PackageProperties = typeof PackageProperties
export type PackageTypeGuidance = typeof PackageTypeGuidance
